### DISCUSSION TITLE
Trying to write container name in the notification

### DISCUSSION THREAD

**Discussion by lubomben** [crazy-max/diun#1004] [Q&A]
I am trying to write in the notification (via PushOver) the container name where the image wa updated.

I use the following docker-compose.yaml file:
```
version: '3.5'

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - ./data:/data
      - ./diun.yml:/diun.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Europe/Rome
      - LOG_LEVEL=info
      - LOG_JSON=false
    restart: always
    labels:
      - "diun.enable=true"
      - "diun.metadata.container=diun"
```

and this is the notif section in my diun.yml file:
```
notif:
  pushover:
    token: <OMITTED>
    recipient: <OMITTED>
    templateTitle: |
      {{ .Entry.Image }} {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }}
    templateBody: |
      Docker tag {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }} which you subscribed to through {{ .Entry.Provider }} provider {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }} on {{ .Entry.Image.Domain }} registry (container: {{ .Entry.Metadata.Container }}).
```
Note the part "(container: {{ .Entry.Metadata.Container }})" at the end on templateBody.

Following is the message in the notification:
`Docker tag docker.io/diun/testnotif:latest which you subscribed to through file provider is available on docker.io registry (container: ).`
Note the part "(container: )" at the end of the message where I supposed there should be the container name from  the field ".Entry.Metadata.Container".

**Comment by crazy-max** [comment]
See https://github.com/crazy-max/diun/pull/749#issue-1513583653

**Comment by lubomben** [comment]
Yes, tried to put in diun.yml the following from the example to test:

```
templateBody: |
      Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released.

      {{ range $key, $value := .Entry.Metadata }}
      * `{{ $key }}`: `{{ $value }}`
      {{- end }}
```

But I got this in notification:
`Docker tag docker.io/diun/testnotif:latest which you subscribed to through file provider has been released.`

Just a note, don't know if it's important: I use the following command to test:
`docker compose exec diun diun notif test`

It seems that it does not iterate the metadatas... or that there are no metadatas.

**Reply by crazy-max** [reply]
> Yes, tried to put in diun.yml

Hard to know without the full yaml. Can you post it?

**Reply by crazy-max** [reply]
> `docker compose exec diun diun notif test`

Ah right, the `notif test` cmd does not read or set any metadata. You need to test it "live" with your notif provider.

**Comment by lubomben** [comment]
> > `docker compose exec diun diun notif test`
> 
> Ah right, the `notif test` cmd does not read or set any metadata. You need to test it "live" with your notif provider.

I supposed about it and then I have another question... Can I force somehow the check on a container abount a new image availability or I have to wait for it? I am trying how to force this behaviour but I can't find a way... any advice is welcome :)

**Comment by lubomben** [comment]
> > Yes, tried to put in diun.yml
> 
> Hard to know without the full yaml. Can you post it?

here it is:
```
watch:
  workers: 10
  schedule: "0 */6 * * *"
  healthchecks:
    baseURL: https://hc-ping.com/
    uuid: <OMITTED>

providers:
  docker:
    watchByDefault: false
    watchStopped: false

notif:
  pushover:
    token: <OMITTED>
    recipient: <OMITTED>
    templateTitle: |
      {{ .Entry.Image }} {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }}
    templateBody: |
      Docker tag {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }} which you subscribed to through {{ .Entry.Provider }} provider {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }} on {{ .Entry.Image.Domain }} registry (container: {{ .Entry.Metadata.Container }}).
```
