### DISCUSSION TITLE
Diun test notification...

### DISCUSSION THREAD

**Discussion by sblantipodi** [crazy-max/diun#1013] [General]
is there a way to force diun to send an MQTT msg just to test that it is working even if there are no updates?

Thanks!!!!

**Comment by sblantipodi** [comment]
this is my docker-compose for diun
```
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/London"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=1 * * * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_NOTIF_MQTT_SCHEME=mqtt"
      - "DIUN_NOTIF_MQTT_HOST=localhost"
      - "DIUN_NOTIF_MQTT_PORT=1883"
      - "DIUN_NOTIF_MQTT_USERNAME=username"
      - "DIUN_NOTIF_MQTT_PASSWORD=pwd"
      - "DIUN_NOTIF_MQTT_CLIENT=diun"
      - "DIUN_NOTIF_MQTT_TOPIC=docker/diun"
      - "DIUN_NOTIF_MQTT_QOS=0"
    labels:
      - "diun.enable=true"
    restart: unless-stopped
```
