### DISCUSSION TITLE
No notification of new images

### DISCUSSION THREAD

**Discussion by Toshibuck** [crazy-max/diun#1039] [Q&A]
Hello,
I have a problem with the Diun configuration, I don't get any notification when a new Docker image is released.

I don't see any error in the logs.
`Sat, 02 Dec 2023 19:55:39 CET INF Starting Diun version=v4.26.0
Sat, 02 Dec 2023 19:55:39 CET INF Configuration loaded from file: /diun.yml
Sat, 02 Dec 2023 19:55:39 CET INF Configuration loaded from 6 environment variable(s)
Sat, 02 Dec 2023 19:55:39 CET INF Cron triggered
Sat, 02 Dec 2023 19:55:39 CET INF Found 10 image(s) to analyze provider=docker
Sat, 02 Dec 2023 19:55:41 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=10 updated=0
Sat, 02 Dec 2023 19:55:41 CET INF Cron initialized with schedule */15 * * * *
Sat, 02 Dec 2023 19:55:41 CET INF Next run in 4 minutes 18 seconds (2023-12-02 20:00:00.018832925 +0100 CET)
Sat, 02 Dec 2023 20:00:00 CET INF Cron triggered
Sat, 02 Dec 2023 20:00:00 CET INF Found 10 image(s) to analyze provider=docker
Sat, 02 Dec 2023 20:00:01 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=10 updated=0
Sat, 02 Dec 2023 20:00:01 CET INF Next run in 15 minutes 6 seconds (2023-12-02 20:15:06.768475005 +0100 CET)`

Notifications work fine because if I manually update an image, I get a notification.

Each container has its own network and goes through my reverse proxy nginx-proxy-manager.

Perhaps the point that causes me problems and requires special configuration, I don't use the :latest tag.

Thanks for your time and sorry for my bad English, I use a translator.

**Comment by seemedFilm** [comment]
I would be also very happy to know this, since my nginx Prox manager is outdated (installed: 2.10.3) and a new version (2.10.4) is on the docker hub. But I also get the same:
Tue, 05 Dec 2023 21:23:24 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=7 updated=0

**Comment by kaerbr** [comment]
I guess this is related to or even the same question as in https://github.com/crazy-max/diun/discussions/1033 !?

**Comment by seemedFilm** [comment]
Hi, 

I have this compose

```
version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
 
    environment:
      - "TZ=Europe/Paris"
  
    labels:
      - "diun.enable=true"
    restart: always
```

And I have recieved the notification about the NginxProxyManager

Which this is the compose (stripped) of:

```
version: '3'
services:
  NginxManager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: NginxProxyManager

    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:81"]
      interval: 30s
      timeout: 10s
      retries: 5
      
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:

    environment:

```

Maybe a comparement worth
