### DISCUSSION TITLE
Private Registry with Kubernetes Provider

### DISCUSSION THREAD

**Discussion by pew** [crazy-max/diun#1065] [Q&A] [answered]
Hi, I'm wondering how to use Diun with the Kubernetes provider and private registries? I deployed Diun using the [quick start guide](https://crazymax.dev/diun/providers/kubernetes/#quick-start). It seems to work for public images, but for private ones I get this warning:

```
unable to retrieve auth token: invalid username/password: unauthorized" image=ghcr.io/[...]
```

The registry secrets are configured in my k8s environment already, is there a way to make Diun use them instead of providing the username/password separately within the Diun config?

**Comment by pew** [comment, marked as answer]
If k8s is using a [docker config.json](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials) file as a secret, this seems to work in combination with Diun:

for the container part:

```yaml
volumeMounts:
  - mountPath: /root/.docker/
    name: docker-config
    readOnly: true
```

referencing the volume:

```yaml
volumes:
  - name: docker-config
    secret:
      secretName: regcred
      items:
      - key: .dockerconfigjson
        path: config.json
```

this will mount the existing `.dockerconfigjson` secret to the diun container at  `/root/.docker/config.json`
