### DISCUSSION TITLE
Include currently running version into notification template

### DISCUSSION THREAD

**Discussion by fhennig42** [crazy-max/diun#1096] [Q&A]
I want to ask if it is possible to add the currently running version of an Image into the notification template.
For example lets assume my docker-compose looks like this:
```
...
  hello:
    image: fhennig42/hello:1.3.9
    restart: no

  diun:
    image: crazymax/diun:latest
    command: serve
    volumes:
      - "./diun_data:/data"
      - "./diun.yml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Berlin"
    labels:
      - "diun.enable=true"
    restart: always
```
and my diun config looks like this:
```
watch:
  workers: 10
  schedule: "*/1 * * * *"
  jitter: 10s
  firstCheckNotif: true
providers:
  docker:
    watchByDefault: true

defaults:
  watchRepo: true
  maxTags: 2
  sortTags: semver
  includeTags:
    - ^\d+\.\d+\.\d+$

notif:
  mail:
    host: some_host
    port: port
    ssl: true
    username: user
    password: pass
    insecureSkipVerify: true
    from: notification@example.com
    to:
      - me@example.com
    templateTitle: "{{ .Entry.Image }} released"
    templateBody: |
      Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released.
      Current Tag: ???
      {{ range $key, $value := .Entry.Metadata }}
      * `{{ $key }}`: `{{ $value }}`
      {{- end }}
```
In my notification I want to get the `Current Tag` which should show the currently running version of the corresponding image. In the example from above, this should be `hello:1.3.9`

I want to include this to see how large the diff between the "running version" and the "updated version" is.
