### DISCUSSION TITLE
when use file provider i got this error  "Key: 'Config.Providers.File.Filename' Error:Field validation for 'Filename' failed on the 'file' tag"

### DISCUSSION THREAD

**Discussion by Nebulosa-Cat** [crazy-max/diun#1101] [Q&A] [answered]
as title, i got this error when i try to use file to monitor images i'm hosting on other machine.
`diun  | Sun, 18 Feb 2024 09:35:46 CST FTL Cannot load configuration error="Key: 'Config.Providers.File.Filename' Error:Field validation for 'Filename' failed on the 'file' tag"`

my run config:
```yml
version: "3.8"
services:
diun:
    image: crazymax/diun:latest
    container_name: diun
    hostname: Diun@Pi-Server
    command: serve
    volumes:
      - ./docker-data/diun/data:/data
      - ./docker-data/diun/diun.yml:/diun.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Taipei
      - LOG_LEVEL=info
      - LOG_JSON=false
    restart: always
    labels:
      - diun.enable=true
```

my diun config:
```yml
db:
  path: diun.db

watch:
  workers: 10
  schedule: "*/5 * * * *"
  jitter: 30s
  firstCheckNotif: true
  runOnStartup: true

defaults:
  watchRepo: false
  notifyOn:
    - new
    - update
  maxTags: 10
  sortTags: reverse
  includeTags:
    - new
    - latest
  excludeTags:
    - dev

notif:
  discord:
    webhookURL: my-web-hook
    renderFields: true
    timeout: 10s
    templateBody: |    
      Docker tag {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }} which you subscribed to through {{ .Entry.Provider }} provider {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }} on {{ .Entry.Image.Domain }} registry (triggered by {{ .Meta.Hostname }} host).


providers:
  docker:
    watchByDefault: false
    watchStopped: true
  file:
    filename: ./list.yml
```
the list.yml is put in `/home/username/docker-data/diun` (same path with diun's config file)
and i've try put it in `/home/username/docker-data/diun/data` (which is diun.db exist)
and the filename i've try `./list.yml`,`/list.yml`,`/home/username/docker-data/diun/list.yml`.`./diun/list.yml` ... and every i can try

all got same error, is there any config i write it incorrect?
thanks.

**Comment by skwde** [comment, marked as answer]
Maybe a bit late, but maybe it helps others coming here.
I had the same issue.

You have to mount the file into the container.

Here is what I did:

The images to watch are defined in `watch-list.yml` which is in the same directory as the diun config `diun.yml`.

In `diun.yml`

```yml
providers:
  file:
    filename: ./watch-list.yml
```

In my `docker-compose.diun.yml` I have

```yml
    volumes:
      - "./diun.yml:/diun.yml:ro"
      - "./watch-list.yml:/watch-list.yml:ro"
      - "./data:/data"
```
