### DISCUSSION TITLE
diun with compose keeps on restarting

### DISCUSSION THREAD

**Discussion by davidwinter** [crazy-max/diun#1103] [Q&A] [answered]
I have just tried to setup diun with the latest version and docker compose:

```yml
services:
  diun:
    image: crazymax/diun:latest
    command: serve
    volumes:
      - "./data:/data"
      - "./diun.yml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/London"
      - "LOG_LEVEL=debug"
      - "LOG_JSON=false"
    restart: always
```

And:

```yml
providers:
  docker:
    watchStopped: true
    watchByDefault: true

watch:
  firstCheckNotif: true

regopts:
  - name: "docker.io"
    selector: image
    username: ######
    password: ######

notif:
  telegram:
    token: ######
    chatIDs:
      - "######"
```

I've obscured some of my values in the config above, but essentially I received the first notification, but then the container appears to exit and then compose keeps restarting it. In the logs it says:

```
INF Jobs completed added=0 failed=0 skipped=0 unchanged=5 updated=0
```

I'm at a loss - I've not seen others experiencing this by searching GitHub issues and discussions... and I can't see anything obvious.
