### DISCUSSION TITLE
Only receiving notification after image has already been updated

### DISCUSSION THREAD

**Discussion by Circenn5130** [crazy-max/diun#1114] [Q&A] [answered]
I've probably done something wrong, but I can't figure out how to get my notification of a new/updated image. Currently the notice is only received after I've already performed an update, and the notice is of the update that I just performed. 

Ex: 
- jellyfin/jellyfin:10.8.11 > jellyfin/jellyfin:10.8.13 
- Upon next cron I'll get an notice from Diun that jellyfin:10.8.13 is available
```
LOG_LEVEL=info
TZ=America/New_York
DIUN_WATCH_WORKERS=10
DIUN_WATCH_SCHEDULE=0 */6 * * *
DIUN_WATCH_JITTER=30s
DIUN_WATCH_FIRSTCHECKNOTIF=true
DIUN_WATCH_RUNONSTARTUP=true
DIUN_DEFAULTS_NOTIFYON=new,update

DIUN_PROVIDERS_KUBERNETES=true
PROVIDERS_KUBERNETES_NAMESPACES=redacted

DIUN_NOTIF_NTFY_ENDPOINT=https://redacted
DIUN_NOTIF_NTFY_TOPIC=redacted
DIUN_NOTIF_NTFY_PRIORITY=3
DIUN_NOTIF_NTFY_TEMPLATETITLE={{ .Entry.Image }} {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }}
DIUN_NOTIF_NTFY_TEMPLATEBODY=Docker tag {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }} which you subscribed to through {{ .Entry.Provider }} provider {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }} on {{ .Entry.Image.Domain }} registry (triggered by {{ .Meta.Hostname }} host).
```

**Comment by RLalor** [comment]
Maybe set it to notify only and then do the updates manually?
I get webhook notifications daily on any containers needing updates then it's just docker compose pull and docker compose up - d then remove old image.

**Comment by urbaman** [comment]
I seem to have the same problem.

```
          env:
            - name: TZ
              value: "Europe/Rome"
            - name: LOG_LEVEL
              value: "debug"
            - name: LOG_JSON
              value: "false"
            - name: DIUN_WATCH_WORKERS
              value: "20"
            - name: DIUN_WATCH_SCHEDULE
              #value: "0 0 * * 6"
              value: "*/2 * * * *"
            - name: DIUN_WATCH_JITTER
              value: "30s"
            - name: DIUN_PROVIDERS_KUBERNETES
              value: "true"
            - name: DIUN_NOTIF_MAIL_HOST
              value: "mail.urbaman.it"
            - name: DIUN_NOTIF_MAIL_PORT
              value: "587"
            - name: DIUN_NOTIF_MAIL_SSL
              value: "false"
            - name: DIUN_NOTIF_MAIL_LOCALNAME
              value: "diun.domain.com"
            - name: DIUN_NOTIF_MAIL_USERNAME
              value: "k8sadmin@domain.com"
            - name: DIUN_NOTIF_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: diun-secret
                  key: DIUN_NOTIF_MAIL_PASSWORD
            - name: DIUN_NOTIF_MAIL_FROM
              value: "diun@domain.com"
            - name: DIUN_NOTIF_MAIL_TO
              value: "k8sadmin@domain.com"
            - name: DIUN_DEFAULTS_NOTIFYON
              value: "update"
            - name: DIUN_PROVIDERS_KUBERNETES_WATCHBYDEFAULT
              value: "true"
            - name: DIUN_DEFAULTS_SORTTAGS
              value: "semver"
```

- `diun image list` lists all the images on my cluster
- I tested deploying a pod with nginx 1.20 and it did not notify (ok, non on new)
- No notifications on newer images (nginx is at 1.29 or something?)
- I updated the image to 1.21 and it did not notify (it's a new image it seems, not updated)

Is there something I'm doing wrong?
