### DISCUSSION TITLE
How can I configure to ignore updates to certain images？

### DISCUSSION THREAD

**Discussion by hausen1012** [crazy-max/diun#1147] [Q&A]
### Description

I don't want to update certain images frequently, but they are always updating and I want to ignore them. May I ask what I should do? Thank you!

**Comment by ilbarone87** [comment]
> ### Description
> 
> I don't want to update certain images frequently, but they are always updating and I want to ignore them. May I ask what I should do? Thank you!

Have you found the solution to this? I'm interested too.

**Comment by lars-devs** [comment]
You can use the Docker label `diun.enabled`, see [this.](https://crazymax.dev/diun/providers/docker/#watchbydefault) I did it with Tiny Tiny RSS since the Docker setup includes three containers of the same image what sends me three notifs at update. Only the container "backup" will fire notifs, "app" not.

```
services:
  app:
    image: cthulhoo/ttrss-fpm-pgsql-static:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ttrss:/var/www/html
      - ./config.d:/opt/tt-rss/config.d:ro
    depends_on:
      - db
  backups:
    image: cthulhoo/ttrss-fpm-pgsql-static:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ttrss_backups:/backups
      - app:/var/www/html
    depends_on:
      - db
    command: /opt/tt-rss/dcron.sh -f
    labels:
      - "diun.enable=false"
```

Note, that in Diun, i have set `DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true`. If it's `false` in your setup, I guess you need to set `diun.enable=true` for each container, at least according to the documentation.
