### DISCUSSION TITLE
Labels docker compose

### DISCUSSION THREAD

**Discussion by Akenjeru** [crazy-max/diun#1212] [Q&A]
I'm using Docker compose
I want the container name to be displayed in notifications
 labels:
 - "diun.enable=true"
 - "diun.metadata.ctn_names"

Am I using labels correctly?

```
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - "/diun/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_NOTIF_GOTIFY_ENDPOINT=URLmygorif"
      - "DIUN_NOTIF_GOTIFY_TOKEN=myapi" # get your token from Gotify UI
      - "DIUN_NOTIF_GOTIFY_PRIORITY=1"
      - "DIUN_NOTIF_GOTIFY_TIMEOUT=10s"
      - "DIUN_ENTRY_METADATA_CTN_NAMES=diun"
    labels:
      - "diun.enable=true"
      - "diun.metadata=ctn_names"
```

I configure diun to send me notifications in gotify about new versions of docker image, but it sends like this 
![image](https://github.com/crazy-max/diun/assets/38863392/3cc17b93-489c-459a-b8bf-cf49fcb887e5)
I want it to write the name of the container
