### DISCUSSION TITLE
Why does diun notify me even though my image is up to date?

### DISCUSSION THREAD

**Discussion by rafapirotto** [crazy-max/diun#1259] [Q&A]
Before setting up and running diun I updated my tautulli image. Then I started diun and was confused to get a notification about an update when I had just updated it.

What does the db store? The current image? The latest registry one? Both? How does it compare?

Here is my config:

```
  diun:
    hostname: diun
    container_name: diun
    image: crazymax/diun:latest
    command: serve
    volumes:
      - ${ROOT_DIR}/${CONFIG_DIR}/diun:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TIMEZONE}
      - LOG_LEVEL=trace
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=10
      - DIUN_WATCH_SCHEDULE=06 10 * * *
      - DIUN_WATCH_JITTER=30s
      - DIUN_WATCH_RUNONSTARTUP=true
      - DIUN_DEFAULTS_WATCHREPO=false
      - DIUN_DEFAULTS_NOTIFYON=new
      - DIUN_NOTIF_PUSHOVER_TOKEN=${DIUN_NOTIF_PUSHOVER_TOKEN}
      - DIUN_NOTIF_PUSHOVER_RECIPIENT=${DIUN_NOTIF_PUSHOVER_RECIPIENT}
      - DIUN_NOTIF_PUSHOVER_PRIORITY=-1
      - DIUN_NOTIF_PUSHOVER_TEMPLATETITLE={{ .Entry.Image.Path }}:{{ .Entry.Image.Tag }} released
      - DIUN_NOTIF_PUSHOVER_TEMPLATEBODY=Docker tag {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }} is available.
      - DIUN_WATCH_FIRSTCHECKNOTIF=true
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=false
      - DIUN_WATCH_COMPAREDIGEST=true
```

Tautulli is set up like this:

```
  tautulli:
    container_name: tautulli
    image: ${IMAGE_REGISTRY}/tautulli:latest
    volumes:
      - ${ROOT_DIR}/${CONFIG_DIR}/tautulli:/config
    ports:
      - '8181:8181'
    labels:
      - diun.enable=true
```
