### DISCUSSION TITLE
Use name of docker host in templateBody?

### DISCUSSION THREAD

**Discussion by binarydad** [crazy-max/diun#1322] [Q&A]
I'm trying to reference the name of the host within the templateBody for notifications. Basically, in the example below, I want to reference the name of the host in the notification message. I tried `.Host` and `env`, but they don't work when I invoke `diun notif test`. Is this possible? Thanks!

```yaml
# diun.yml
watch:
  workers: 2
  schedule: "0 */6 * * *" # Every 6 hours

notif:
  gotify:
    endpoint: <removed>
    token: <removed>
    priority: 1
    timeout: 10s
    templateTitle: "Image Update"
    templateBody: |
      Docker image {{ .Entry.Image.Path }} has an update available ({{ .Host }}).

providers:
  docker:
    watchByDefault: true
```

**Comment by UnclePhil** [comment]
I had the same problem, but I bypass it with a small docker feature 

```
services:
  diun:
    image: crazymax/diun:latest
    hostname: ${CLUSTER_NAME}-Diun
    command: serve
    volumes:
      - "diun:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      TZ: europe/Brussels
       DIUN_NOTIF_DISCORD_TEMPLATEBODY: '{{ .Entry.Image }} has a new tag  (triggered by {{ .Meta.Hostname }} host).'

```
I force the diun container hostname with the swarm cluster name and then I  use .Meta.Hostname in the templatebody

Working perfectly.

But i still miss the name of the services for each analyzed container.
