### DISCUSSION TITLE
failed to decode configuration from file: yaml: line 5: did not find expected key

### DISCUSSION THREAD

**Discussion by uniquePWD** [crazy-max/diun#1353] [Q&A] [answered]
Docker is:
```
  diun:
    container_name: diun
    image: crazymax/diun:latest
    command: serve
    volumes:
      - /opt/diun:/data
      - /opt/diun/diun.yml:/diun.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Europe/London
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */8 * * *
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
    labels:
      - diun.enable=true
    restart: always
```

Diun.yml is:
```
db:
  path: diun.db

notif:
  gotify:
    endpoint: http://192.168.100.106:1001
    token: [redacted]
    priority: 1
    timeout: 10s
    templateTitle: "{{ .Entry.Image }} {{ if (eq .Entry>
    templateBody: |
      Docker tag {{ .Entry.Image }} which you subscribe>

providers:
  docker:
    watchStopped: true
```

I'm totally at a loss as to what's wrong.

**Comment by crazy-max** [comment, marked as answer]
Double quote looks missing at `templateTitle`:

```yaml
db:
  path: diun.db

notif:
  gotify:
    endpoint: http://192.168.100.106:1001
    token: [redacted]
    priority: 1
    timeout: 10s
    templateTitle: "{{ .Entry.Image }} {{ if (eq .Entry>"
    templateBody: |
      Docker tag {{ .Entry.Image }} which you subscribe>

providers:
  docker:
    watchStopped: true
```

You can also do:

```yaml
db:
  path: diun.db

notif:
  gotify:
    endpoint: http://192.168.100.106:1001
    token: [redacted]
    priority: 1
    timeout: 10s
    templateTitle: >
      {{ .Entry.Image }} {{ if (eq .Entry>
    templateBody: |
      Docker tag {{ .Entry.Image }} which you subscribe>

providers:
  docker:
    watchStopped: true
```
