### DISCUSSION TITLE
Script notification howto

### DISCUSSION THREAD

**Discussion by t4afinn** [crazy-max/diun#863] [Q&A] [answered]
I am not able to make the script notification work with Diun running in docker itself.
It claims that there is no file or folder when i enter a script.
Even adding a simple echo command fails because the command is not in $PATH, i get told.
I dont think its an issue on your side. So i kindly ask if you can provide a working example in the docs.

**Comment by crazy-max** [comment]
@spacedogs-wtf 

> I am not able to make the script notification work with Diun running in docker itself.

Can you show your compose file and diun configuration please?

**Comment by t4afinn** [comment]
```
version: "3.7"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    restart: always
    volumes:
      - /diun/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "TZ=Europe/Berlin"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_FIRSTCHECKNOTIF=true"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_SCRIPT_CMD=echo 'hello'"
```
results in `Script notification failed error=": exec: \"echo 'hello'\": executable file not found in $PATH" image=[...]` for every container.
i also tried to mount a script from the host into diun. i tested several ways to run it (e.g. with set `DIUN_NOTIF_SCRIPT_DIR`) but it always fails too.

**Comment by crazy-max** [comment, marked as answer]
@spacedogs-wtf `echo 'hello'` is not a valid command. If you want to pass args you have to use the `DIUN_NOTIF_SCRIPT_ARGS` env as explained in the [documentation](https://crazymax.dev/diun/notif/script/):

```yaml
version: "3.7"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    restart: always
    volumes:
      - /diun/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "TZ=Europe/Berlin"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_FIRSTCHECKNOTIF=true"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_SCRIPT_CMD=echo"
      - "DIUN_NOTIF_SCRIPT_ARGS=hello"
```
