### DISCUSSION TITLE
Send image to notify telegram

### DISCUSSION THREAD

**Discussion by Vctrsnts** [crazy-max/diun#872] [Q&A]
Hi

My question is possible to send image with alert on Telegram? Because I use the tag ``.Meta.Logo`` and only see in telegram message the url of image.  Or is need to configure the boot with special options?

Because another applications ( flexget ) is possible.

My docker configuration to diun is this:
```
docker-compose.yml
  diun:
    image: crazymax/diun:latest
    container_name: diun
    restart: unless-stopped
    hostname: dasReich
    volumes:
      - ${STORAGE}/config/diun:/data
      - ${STORAGE}/config/diun/diun.yml:/diun.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - "TZ=Europe/Madrid"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
```
And the _diun config_ is this:
```
  db:
      path: diun.db
  watch:
      workers: 20
      schedule: "@weekly"
      firstCheckNotif: true
  providers:
      docker:
        watchByDefault: true
        watchStopped: true
  notif:
      telegram:
        token: token_id
        chatIDs:
          - chat_id
        templateBody: |
          Docker tag [{{ .Meta.Logo }}] - {{ if .Entry.Image.HubLink }}[{{ .Entry.Image }}]({{ .Entry.Image.HubLink }}){{ else }}{{ .Entry.Image }}{{ end }} which you subscribed to through {{ .Entry.Provider }} provider has been {{ if (eq .Entry.Status "new") }}newly added{{ else }}updated{{ end }} on {{ escapeMarkdown .Meta.Hostname }}.
```
Thanks a lot
