### DISCUSSION TITLE
[Support] Need help with excluding a container please

### DISCUSSION THREAD

**Discussion by TheCableGuy99** [crazy-max/diun#891] [Q&A]
Hi,

I need to exclude this from being notified but struggling with the exact syntax:" tag [ghcr.io/dockserver/docker-mount:latest](https://github.com/users/dockserver/packages/container/package/docker-mount) "

This is my docker-compose, please could you tell me how I should enter it?

```yaml
version: "3.5"

services:
  diun:
    container_name: diun
    image: crazymax/diun:latest
    restart: "${RESTARTAPP}"
    hostname: diun
    container_name: diun
    command: serve
    volumes:
      - "${APPFOLDER}/diun/data:/data:rw"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "PUID=${ID}"
      - "PGID=${ID}"
      - "TZ=Europe/London"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_NOTIF_MAIL_HOST=host.domain.co.uk"
      - "DIUN_NOTIF_MAIL_PORT=587"
      - "DIUN_NOTIF_MAIL_SSL=false"
      - "DIUN_NOTIF_MAIL_INSECURESKIPVERIFY=true"
      - "DIUN_NOTIF_MAIL_USERNAME=user@domain.co.uk"
      - "DIUN_NOTIF_MAIL_PASSWORD=aafdsfsccwecew"
      - "DIUN_NOTIF_MAIL_FROM=user@domain.co.uk"
      - "DIUN_NOTIF_MAIL_TO=user@domain.co.uk"
      - DIUN_NOTIF_MAIL_TEMPLATETITLE={{ .Entry.Image }} {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }}
      - DIUN_NOTIF_MAIL_TEMPLATEBODY=Docker tag {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }} which you subscribed to throug>
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_EXCLOUDE_tags
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query"
    labels:
      - diun.enable=true
    restart: always`
```

Thanks for any help.
