### DISCUSSION TITLE
Private docker registry. Requesting bearer token: invalid status code from registry 403 (Forbidden)

### DISCUSSION THREAD

**Discussion by fer0m** [crazy-max/diun#910] [Q&A]
Hi all, it's been a few days, but I can't seem to solve my problem. I have a private docker register, however I get the following errors when running diun: 

```
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] No credentials matching git.myrepo.cloud:5050 found in /run/containers/0/auth.json
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] No credentials matching git.myrepo.cloud:5050 found in /root/.config/containers/auth.json
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] No credentials matching git.myrepo.cloud:5050 found in /root/.docker/config.json
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] No credentials matching git.myrepo.cloud:5050 found in /root/.dockercfg
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] No credentials for git.myrepo.cloud:5050 found
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] No credentials matching git.myrepo.cloud:5050 found in /run/containers/0/auth.json
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] No credentials matching git.myrepo.cloud:5050 found in /root/.config/containers/auth.json
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] No credentials matching git.myrepo.cloud:5050 found in /root/.docker/config.json
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] No credentials matching git.myrepo.cloud:5050 found in /root/.dockercfg
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] No credentials for git.myrepo.cloud:5050 found
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG Registry options will be used image=nginx:latest provider=docker regopt=docker.io
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] No credentials matching docker.io found in /run/containers/0/auth.json
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] No credentials matching docker.io found in /root/.config/containers/auth.json
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] No credentials matching docker.io found in /root/.docker/config.json
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] No credentials matching docker.io found in /root/.dockercfg
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] No credentials for docker.io found
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] Using registries.d directory /etc/containers/registries.d
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] Returning credentials for git.myrepo.cloud:5050/dev/myrepo2-backend/myrepo2-mysql-enterprise from DockerAuthConfig
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image]  No signature storage configuration found for git.myrepo.cloud:5050/dev/myrepo2-backend/myrepo2-mysql-enterprise:v0.0.2, using built-in default file:///var/lib/containers/sigstore
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] Using registries.d directory /etc/containers/registries.d
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] Returning credentials for git.myrepo.cloud:5050/dev/myrepo2-backend/myrepo2-backend-enterprise from DockerAuthConfig
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image]  No signature storage configuration found for git.myrepo.cloud:5050/dev/myrepo2-backend/myrepo2-backend-enterprise:v0.0.9-date-extractor, using built-in default file:///var/lib/containers/sigstore
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] Using registries.d directory /etc/containers/registries.d
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] Returning credentials for docker.io/crazymax/diun from DockerAuthConfig
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image]  No signature storage configuration found for docker.io/crazymax/diun:latest, using built-in default file:///var/lib/containers/sigstore
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] Using registries.d directory /etc/containers/registries.d
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] Using registries.d directory /etc/containers/registries.d
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] Returning credentials for docker.io/docker/compose from DockerAuthConfig
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image]  No signature storage configuration found for docker.io/docker/compose:1.29.2, using built-in default file:///var/lib/containers/sigstore
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] Looking for TLS certificates and private keys in /etc/docker/certs.d/git.myrepo.cloud:5050
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] Returning credentials for docker.io/library/nginx from DockerAuthConfig
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] Looking for TLS certificates and private keys in /etc/docker/certs.d/git.myrepo.cloud:5050
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image]  No signature storage configuration found for docker.io/library/nginx:latest, using built-in default file:///var/lib/containers/sigstore
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image]  crt: /etc/docker/certs.d/git.myrepo.cloud:5050/git.myrepo.cloud.crt
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image]  crt: /etc/docker/certs.d/git.myrepo.cloud:5050/git.myrepo.cloud.crt
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] GET https://registry-1.docker.io/v2/
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] GET https://registry-1.docker.io/v2/
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] GET https://git.myrepo.cloud:5050/v2/
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] GET https://git.myrepo.cloud:5050/v2/
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] GET https://registry-1.docker.io/v2/
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] Ping https://git.myrepo.cloud:5050/v2/ status 401
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] Ping https://git.myrepo.cloud:5050/v2/ status 401
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] GET https://git.myrepo.cloud/jwt/auth?scope=repository%3Adev%2Fmyrepo2-backend%2Fmyrepo2-mysql-enterprise%3Apull&service=container_registry
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK DBG [containers/image] GET https://git.myrepo.cloud/jwt/auth?scope=repository%3Adev%2Fmyrepo2-backend%2Fmyrepo2-backend-enterprise%3Apull&service=container_registry
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: Requesting bearer token: invalid status code from registry 403 (Forbidden)" image=git.myrepo.cloud:5050/dev/myrepo2-backend/myrepo2-backend-enterprise:v0.0.9-date-extractor provider=docker
deploy-diun-1                     | Wed, 28 Jun 2023 12:30:11 MSK WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: Requesting bearer token: invalid status code from registry 403 (Forbidden)" image=git.myrepo.cloud:5050/dev/myrepo2-backend/myrepo2-mysql-enterprise:v0.0.2 provider=docker
```

The part of my dockercompose looks like:
```
diun:
    image: crazymax/diun:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./diun_server.sh:/diun_server.sh"
      - "/etc/docker/certs.d:/etc/docker/certs.d"
    environment:
      - "TZ=Europe/Moscow"
      - "LOG_LEVEL=debug"
      - "LOG_JSON=false"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DOCKER_REGISTRY=${DOCKER_REGISTRY}"
      - "DOCKERHUB_USER=${DOCKERHUB_USER}"
      - "DOCKERHUB_PASS=${DOCKERHUB_PASS}"
      - "DJANGO_AUTH_TOKEN=${DJANGO_AUTH_TOKEN}"
      - "DIUN_PROVIDERS_DOCKER_TLSVERIFY=false"
    entrypoint: ["/bin/sh", "/diun_server.sh"]
    networks:
      - myrepo_network
    dns:
      - 10.250.0.1
```

I generate a configuration file for "diun" and if I go into the container and check it, everything is fine:

```
/ # cat diun.yaml 
watch:
  workers: 20
  schedule: "*/5 * * * *"
  firstCheckNotif: true

regopts:
  - name: "docker.io"
    selector: image
  - name: git.myrepo.cloud:5050
    username: as
    password: mypass

notif:
  webhook:
    endpoint: http://myrepo2-backend-enterprise:8000/graphql
    method: POST
    headers:
      Authorization: test
    timeout: 10s
/ # 
```

Despite this, as you can see in the first log, I get an error. I have tried several options to check, my data is correct and I can log in to the docker in diun container.

```
/ # docker login -u "as" -p "mypass" git.myrepo.cloud:5050
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

I also tried to get my "images" using manual "bear" - authorization, and it worked, too.
Please help me, what am I doing wrong, and where have I not looked yet?
