### ISSUE TITLE
Didn't find any new releases

### ISSUE THREAD

**Issue by maurxce** [crazy-max/diun#1018]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/diun/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I set up diun yesterday, around 8 hours after one of the images I use has received an update, but I didn't get any notification on discord.
Running `diun notif test` works fine.

### Expected behaviour

I receive a message that states there was an update

### Actual behaviour

Nothing happens, DIUN won't find the update

### Steps to reproduce

1. Set up diun
2. Enable `DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT`
3. Create a webhook to discord

### Diun version

4.26.0

### Docker info

```text
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 15
  Running: 15
  Paused: 0
  Stopped: 0
 Images: 16
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-165-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 3.734GiB
 Name: dev
 ID: 48f3ee14-bc25-4ee7-9f1d-c3162d5eb000
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

### Docker Compose config

```yaml
name: update
services:
  diun:
    command:
    - serve
    environment:
      DIUN_NOTIF_DISCORD_MENTIONS: <TAG>
      DIUN_NOTIF_DISCORD_TEMPLATEBODY: '{{ if .Entry.Image.HubLink }}[**{{ .Entry.Image
        }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }}
        has received an update.'
      DIUN_NOTIF_DISCORD_WEBHOOKURL: <URL>
      DIUN_PROVIDERS_DOCKER: "true"
      DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT: "true"
      DIUN_WATCH_JITTER: 30s
      DIUN_WATCH_SCHEDULE: 0 */6 * * *
      DIUN_WATCH_WORKERS: "20"
      TZ: Europe/Berlin
    image: crazymax/diun:4.26.0
    networks:
      default: null
    restart: unless-stopped
    volumes:
    - type: bind
      source: /containers/update/data
      target: /data
      bind:
        create_host_path: true
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      bind:
        create_host_path: true
networks:
  default:
    name: update_default
```

### Logs

```text
Sat, 04 Nov 2023 12:36:23 CET INF Starting Diun version=v4.26.0
Sat, 04 Nov 2023 12:36:23 CET INF Configuration loaded from 9 environment variable(s)
Sat, 04 Nov 2023 12:36:23 CET INF Cron triggered
Sat, 04 Nov 2023 12:36:23 CET INF Found 15 image(s) to analyze provider=docker
Sat, 04 Nov 2023 12:36:24 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=15 updated=0
Sat, 04 Nov 2023 12:36:24 CET INF Cron initialized with schedule 0 */6 * * *
Sat, 04 Nov 2023 12:36:24 CET INF Next run in 5 hours 23 minutes (2023-11-04 18:00:04.427079126 +0100 CET)
Sat, 04 Nov 2023 18:00:04 CET INF Cron triggered
Sat, 04 Nov 2023 18:00:04 CET INF Found 15 image(s) to analyze provider=docker
Sat, 04 Nov 2023 18:00:07 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=15 updated=0
Sat, 04 Nov 2023 18:00:07 CET INF Next run in 6 hours 3 seconds (2023-11-05 00:00:08.009832822 +0100 CET)
Sun, 05 Nov 2023 00:00:08 CET INF Cron triggered
Sun, 05 Nov 2023 00:00:08 CET INF Found 15 image(s) to analyze provider=docker
Sun, 05 Nov 2023 00:00:10 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=15 updated=0
Sun, 05 Nov 2023 00:00:10 CET INF Next run in 6 hours 16 seconds (2023-11-05 06:00:24.293577396 +0100 CET)
Sun, 05 Nov 2023 06:00:24 CET INF Cron triggered
Sun, 05 Nov 2023 06:00:24 CET INF Found 15 image(s) to analyze provider=docker
Sun, 05 Nov 2023 06:00:25 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=15 updated=0
Sun, 05 Nov 2023 06:00:25 CET INF Next run in 5 hours 59 minutes (2023-11-05 12:00:21.99358652 +0100 CET)
```

### Additional info

It's happening to my [Pingvin Share](https://hub.docker.com/r/stonith404/pingvin-share/tags) Container which currently runs on `v0.19.2`, but `v0.20.0` released yesterday
