### ISSUE TITLE
Newer semver image tags notification for `file` provider

### ISSUE THREAD

**Issue by vnghia** [crazy-max/diun#1053]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/diun/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

So I have the same issue as #556 but for `file` provider.

I have `"DIUN_WATCH_FIRSTCHECKNOTIF=false"` and my `file` provider looks like this:
```
- include_tags:
  - ^\d+\.\d+\.\d+$
  max_tags: 5
  name: syncthing/syncthing:1.26.0@sha256:6be23b06ef9bc134028d285bb649a2a5d544e5817f0961abb2476a42deaab0e4
  notify_on:
  - new
  sort_tags: semver
  watch_repo: true
- include_tags:
  - ^\d+\.\d+\.\d+$
  max_tags: 5
  name: restic/restic:0.16.0@sha256:78ccbaddf039176457aabaa4b2f4a67aa177535f7e1a656dcfde18b2d6c2441d
  notify_on:
  - new
  sort_tags: semver
  watch_repo: true
```

### Expected behaviour

`Diun` only notifies about tags that are newer than the current tags. 

### Actual behaviour

`Diun` notifies all tags regardless they are newer than the current tags or not. 

### Steps to reproduce

1. Run `diun` with `file` provider as above.

### Diun version

4.26.0

### Docker info

```text
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 48
  Running: 43
  Paused: 0
  Stopped: 5
 Images: 120
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-88-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.61GiB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Docker Compose config

```yaml
N/A
```

### Logs

```text
Thu, 14 Dec 2023 13:05:46 CET INF New image found image=docker.io/restic/restic:0.16.2 provider=file
Thu, 14 Dec 2023 13:05:47 CET INF New image found image=docker.io/restic/restic:0.15.1 provider=file
Thu, 14 Dec 2023 13:05:47 CET INF New image found image=docker.io/restic/restic:0.15.2 provider=file
Thu, 14 Dec 2023 13:05:47 CET INF New image found image=docker.io/restic/restic:0.16.1 provider=file
Thu, 14 Dec 2023 13:05:54 CET INF New image found image=docker.io/syncthing/syncthing:1.27.1 provider=file
Thu, 14 Dec 2023 13:05:54 CET INF New image found image=docker.io/syncthing/syncthing:1.26.1 provider=file
Thu, 14 Dec 2023 13:05:54 CET INF New image found image=docker.io/syncthing/syncthing:1.27.0 provider=file
Thu, 14 Dec 2023 13:05:54 CET INF New image found image=docker.io/syncthing/syncthing:1.25.0 provider=file
```

### Additional info

It seems that `diun` will notify `max_tags` (in my case: 5) latest tags without checking that if it is newer than the tag in the current `file` provider. I only want it to notify about the newer tags than my current stack.
