### ISSUE TITLE
Diun not found any image.

### ISSUE THREAD

**Issue by vampywiz17** [crazy-max/diun#1072]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/diun/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I set the diun (see the config part) but it not found any image. (include diun) i use docker swarm.

### Expected behaviour

found images

### Actual behaviour

not found anything

### Steps to reproduce

1. set conf
2. restart diun

### Diun version

4.26.0

### Docker info

```text
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 11
  Running: 7
  Paused: 0
  Stopped: 4
 Images: 24
 Server Version: 20.10.23-ce
 Storage Driver: btrfs
  Build Version: Btrfs v4.15
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: edou7744br2h7lshq79tvkvab
  Is Manager: true
  ClusterID: k4cjvzi6zwaz91oohepm4p632
  Managers: 1
  Nodes: 3
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 2
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.51.38.92
  Manager Addresses:
   10.51.38.92:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux oci runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
 runc version: v1.1.5-0-gf19387a6bec4
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.14.21-150500.53-default
 Operating System: openSUSE Leap 15.5
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.764GiB
 Name: hun25-21v
 ID: 5M2D:3EQB:BXTJ:EVT4:YDNJ:XQ42:XWO3:3HYY:ET44:YJQD:CSSR:4Y27
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hun25-21v:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: API is accessible on http://0.0.0.0:2376 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/go/attack-surface/
```

### Docker Compose config

```yaml
version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    command: serve
    volumes:
      - "diun_system_config:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Budapest"
      - "LOG_LEVEL=debug"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_SWARM=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT: true"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  diun_system_config:
    external: true
    name: diun_system_config
```

### Logs

```text
Fri, 12 Jan 2024 06:00:10 CET WRN No image found
Fri, 12 Jan 2024 06:00:10 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=0 updated=0
Fri, 12 Jan 2024 06:00:10 CET INF Next run in 6 hours 6 seconds (2024-01-12 12:00:16.335543674 +0100 CET)
```

### Additional info

Some images in docker hub, other in personal registry.
