### ISSUE TITLE
Feature request: Support for generic push healthchecks 

### ISSUE THREAD

**Issue by ScrumpyJack** [crazy-max/diun#1107]
### Description

There is already a request for [uptime kuma](https://github.com/crazy-max/diun/issues/907) for push healthchecks but this should be more generic.

Generic push healthchecks would be nice as they are mainly just an HTTP GET to an endpoint and will suffice for may push healthcheck needs

```
watch:
  schedule: "0 */6 * * *"
  push_healthcheck:
    url: https://my-monitoring-endpoiint.com/i-am-diun-and-i-am-alive
```
