### ISSUE TITLE
Timezone discrepancy between container and host

### ISSUE THREAD

**Issue by instantdreams** [crazy-max/diun#1131]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/diun/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Date on host reports according to timezone. Date on container reports in UTC.

### Expected behaviour

For timezone to be used by container.

### Actual behaviour

Container `date` command is reporting UTC.

### Steps to reproduce

1. Enable and set docker environment variable `TZ`
2. Add read only volume mount for `/etc/timezone`
3. Add read only volume mount for `/etc/localtime`
4. Start diun container
5. Run command `timedatectl`
6. Run command `docker exec diun-1 timedatectl`
7. Run command `date`
8. Run command `docker exec diun-1 date`

### Diun version

4.26.0

### Docker info

```text
Client: Docker Engine - Community
 Version:    25.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 10
  Running: 10
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 25.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.21-v8+
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 1.855GiB
 Name: id-edge1
 ID: 7HKR:XS7T:KP55:WXII:JDYT:SCR5:EF3N:PHZA:XOAK:EWEP:3J7W:NWFN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Docker Compose config

```yaml
name: diun
networks:
  default:
    name: diun_default
  example-net:
    external: true
    name: example
services:
  diun:
    command: serve
    container_name: diun-1
    domainname: example.com
    environment:
      - TZ=America/Edmonton
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=5
      - DIUN_WATCH_SCHEDULE=10 06 * * 0
      - DIUN_WATCH_JITTER=30s
      - DIUN_WATCH_FIRSTCHECKNOTIF=true
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true
      - DIUN_NOTIF_TELEGRAM_TOKEN=[token]
      - DIUN_NOTIF_TELEGRAM_CHATIDS=[chat-id]
    hostname: diun-1
    image: ghcr.io/crazy-max/diun:latest
    labels:
      - traefik.enable=false
    networks:
      example-net:
        ipv4_address: 192.168.91.231
    restart: unless-stopped
    volumes:
      - bind:
          create_host_path: true
        source: /srv/diun/data
        target: /data
        type: bind
      - bind:
          create_host_path: true
        read_only: true
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
      - bind:
          create_host_path: true
        read_only: true
        source: /etc/timezone
        target: /etc/timezone
        type: bind
      - bind:
          create_host_path: true
        read_only: true
        source: /etc/localtime
        target: /etc/localtime
        type: bind
```

### Logs

```text
diun-1  | Wed, 20 Mar 2024 09:46:53 MDT INF Starting Diun version=v4.26.0
diun-1  | Wed, 20 Mar 2024 09:46:53 MDT INF Configuration loaded from 10 environment variable(s)
diun-1  | Wed, 20 Mar 2024 09:46:53 MDT INF Cron triggered
diun-1  | Wed, 20 Mar 2024 09:46:54 MDT INF Found 10 image(s) to analyze provider=docker
diun-1  | Wed, 20 Mar 2024 09:46:55 MDT INF Jobs completed added=0 failed=0 skipped=0 unchanged=10 updated=0
diun-1  | Wed, 20 Mar 2024 09:46:55 MDT INF Cron initialized with schedule 10 06 * * 0
diun-1  | Wed, 20 Mar 2024 09:46:55 MDT INF Next run in 3 days 20 hours (2024-03-24 06:10:03.337658867 -0600 MDT)
```

### Additional info

Here's the output:

``` BASH
$ timedatectl
               Local time: Wed 2024-03-20 10:12:46 MDT
           Universal time: Wed 2024-03-20 16:12:46 UTC
                 RTC time: n/a
                Time zone: America/Edmonton (MDT, -0600)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

$ docker exec diun-1 timedatectl
OCI runtime exec failed: exec failed: unable to start container process: exec: "timedatectl": executable file not found in $PATH: unknown

$ date
Wed Mar 20 10:13:07 MDT 2024

$ docker exec diun-1 date
Wed Mar 20 16:13:10 UTC 2024
```

I am expecting the result of `docker exec diun-1 date` to match the local container.
