### ISSUE TITLE
ERR Ntfy notification failed error="0 unauthorized: "

### ISSUE THREAD

**Issue by Stitch10925** [crazy-max/diun#1153]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/diun/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I have Diun set up to notify me through ntfy when an update is available. I followed the documentation on how to pass a token for authentication purposes, but I keep getting the following error:

> ERR Ntfy notification failed error="0 unauthorized: "

I am currently running the following versions:

Diun: 4.28
Ntfy: v2.10

My config file looks like this:

`watch:
  schedule: "0 */12 * * *"

defaults:
  watchRepo: false
  sortTags: semver
  notifyOn:
    - new
    - update

notif:
  ntfy:
    endpoint: http://ntfy.example.com
    token: QmFzaWXXXXXXZjSEp2WjXXXXXXXX
    topic: Alerts
    priority: 3
    timeout: 5s

providers:
  swarm:
    watchByDefault: true`n

If I do a post using:
> POST http://ntfy.example.com?auth=QmFzaWXXXXXXZjSEp2WjXXXXXXXX
With the Nfty JSON in the body the message is sent to me

What am I missing in order to get this to work? 

Thanks in advance!

### Expected behaviour

Alert should be sent to Ntfy

### Actual behaviour

Authentication error is returned:

> ERR Ntfy notification failed error="0 unauthorized: "

### Steps to reproduce

Add a Nfty notifier to the Diun configuration file on a Ntfy topic that requires authentication

### Diun version

4.28

### Docker info

```text
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 20.10.20
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 0zraht31fea4n7e13du8kvwls
  Is Manager: true
  ClusterID: mq2a8l3mqq6v7iq6fcfu8jkof
  Managers: 1
  Nodes: 7
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 3
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.1.12
  Manager Addresses:
   192.168.1.12:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: 5fd4c4d144137e991c4acebb2146ab1483a97925
 init version: 
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.15.78-0-lts
 Operating System: Alpine Linux v3.16
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 3.839GiB
 Name: dckrmg01.int.dobbelr.com
 ID: B7MI:XBT3:SUMU:2PYK:H7SX:GQXG:ELRS:NA7Y:UTGO:TCNT:VYRI:LTIQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Docker Compose config

```yaml
version: '3.8'

services:
  app:
    restart: always
    image: crazymax/diun:4.28.0
    command: ["serve", "--config", "/data/diun.yml"]
    hostname: diun.example.com #port 3000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - data:/data
    networks:
    - host
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role==manager
volumes:
  data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nas.example.com,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":/export/Diun"

networks:
  host:
    name: caddy-network
    external: true
```

### Logs

```text
Wed, 17 Apr 2024 22:01:38 UTC INF Starting Diun version=v4.28.0
Wed, 17 Apr 2024 22:01:38 UTC INF Configuration loaded from file: /data/diun.yml
Wed, 17 Apr 2024 22:01:38 UTC INF Configuration loaded from 1 environment variable(s)
Wed, 17 Apr 2024 22:01:38 UTC INF Cron triggered
Wed, 17 Apr 2024 22:01:38 UTC INF Found 32 image(s) to analyze provider=swarm
Wed, 17 Apr 2024 22:01:43 UTC INF New image found image=docker.io/binwiederhier/ntfy:v2.10.0@sha256:c38f96ff95e1f1a099abe1ffef6dbef6e2a5a52751bfe87db40b3a4e40115757 provider=swarm
Wed, 17 Apr 2024 22:01:44 UTC ERR Ntfy notification failed error="0 unauthorized: " image=docker.io/binwiederhier/ntfy:v2.10.0@sha256:c38f96ff95e1f1a099abe1ffef6dbef6e2a5a52751bfe87db40b3a4e40115757
Wed, 17 Apr 2024 22:01:44 UTC INF Jobs completed added=1 failed=0 skipped=0 unchanged=31 updated=0
Wed, 17 Apr 2024 22:01:44 UTC INF Cron initialized with schedule 0 */12 * * *
Wed, 17 Apr 2024 22:01:44 UTC INF Next run in 1 hour 58 minutes (2024-04-18 00:00:09.080407633 +0000 UTC)
```
