### ISSUE TITLE
Support multiple notifications

### ISSUE THREAD

**Issue by Elbandi** [crazy-max/diun#1168]
### Description

It would be nice, if there are more same notifications, and configure different notification for repos.

eg: Nofity differnet slack group (=channels) for portainer/portainer and alpine repo:

```
notif:
  slack:
   - name: devteam
      webhookURL: https://hooks.slack.com/services/ABCD12EFG/HIJK34LMN/01234567890abcdefghij
      renderFields: true
      templateBody: |
        There is a new {{ .Entry.Image }}. Run container build jobs!
   - name: operationteam
      webhookURL: https://hooks.slack.com/services/ABCD12EFG/HIJK34LMN/01234567890abcdefghij
      renderFields: true
      templateBody: |
        There is a new {{ .Entry.Image }}. Upgrade image!
  webhook:
   - name: foo
     ...
   - name: bar
     ...
```
And file provider:
```
- name: alpine
  notif: devteam
  watch_repo: true
- name: docker.io/portainer/portainer
  notif: operationteam
  watch_repo: true
```
