### ISSUE TITLE
 WRN No notifier available

### ISSUE THREAD

**Issue by Chris92ch** [crazy-max/diun#118]
Hello  ! I'm currently trying diun but I have some strange logs when I'm trying to send a test notification to my slack webhook

`Tue, 30 Jun 2020 17:04:38 CEST WRN No notifier available`

#### Notify configuration
I only want to write to a slack channel via a webhook. Here's my config : 

```
db:
  path: diun.db

watch:
  workers: 10
  schedule: "0 * * * *"
  firstCheckNotif: false

notif:
  slack:
    enable:true
    webhookURL: https://hooks.slack.com/services/xxxxxxxx

regopts:
  - name: "docker.io"
    selector: image

providers:
  file:
    filename: /providers.yml

```
And here's my docker compose file : 

```
`version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./diun.yml:/diun.yml"
      - "./providers.yml:/providers.yml"
    environment:
      - "TZ=Europe/Paris"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=10"
      - "DIUN_WATCH_SCHEDULE=0 * * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
    restart: always

`
```

Seems that this configuration isn't enough to be able to send some notifs via slack ... Do you know what's wrong or missing ? 

Best regards and thanks for now
Chris.

**Comment by crazy-max** [comment]
Hi @Chris92ch,

Looking at your config it looks like you're migrating from Diun v2 because your config file is malformed. [`enable` field does not exist since Diun v3](https://crazy-max.github.io/diun/migration/v2-to-v3/#remove-enable-setting-for-notifiers).

If you want to include your Diun config in your compose service you have to set the [env var `CONFIG`](https://crazy-max.github.io/diun/get-started/#diun-cli). See [this section](https://crazy-max.github.io/diun/migration/v3-to-v4/#diunyml-not-loaded-by-default-in-docker-image) for more info.

Checkout the [Quick start with the Docker provider](https://crazy-max.github.io/diun/get-started/#quick-start-with-the-docker-provider) section to get started.

> `Tue, 30 Jun 2020 17:04:38 CEST WRN No notifier available`

And please include all your logs next time ;)

**Comment by Chris92ch** [comment]
Hello @crazy-max 

Thanks for your answer. You're right, the config seems now ok (my logs look better and now find images). Sadly, I still cannot launch a docker exec to test the notifications

` docker exec -it IdOfMyDocker  diun --test-notif `

The only output I got when I try this is 

`Tue, 30 Jun 2020 17:56:23 CEST FTL Cannot initialize Diun error=timeout`

I got no message regarding this notification in the logs. 

This is my current config : 

```
db:
  path: diun.db

watch:
  workers: 10
  schedule: "0 * * * *"
  firstCheckNotif: false

notif:
  slack:
    webhookURL: https://hooks.slack.com/services/WebhookURLxxxxx

regopts:
  - name: "docker.io"
    selector: image

providers:
  file:
    filename: /providers.yml
```

Best regards
Chris.
