### ISSUE TITLE
error="unable to decode into struct, yaml: unmarshal errors:\n  line 12: field watchByDefault not found in type model.PrdDocker"

### ISSUE THREAD

**Issue by PopeRigby** [crazy-max/diun#123]
#### Steps to reproduce this issue

Set the `watchByDefault` field to `true` in `diun.yml`

#### Expected behaviour

Diun should be fine with that value.

#### Actual behaviour

Diun says:

```
error="unable to decode into struct, yaml: unmarshal errors:\n  line 12: field watchByDefault not found in type model.PrdDocker"
```

### Configuration

* Diun version : 4.1.1
* Platform (windows/linux) : Linux
* System info (type `uname -a`) : Linux haddock.cc 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

### `diun.yml`
```
notif:
  webhook:
    endpoint: https://webhooks.t2bot.io/api/v1/matrix/hook/n8F0XbBzfX7Lih1XfaIVoFxSzO6KGf7E3z64uE1uEuwJPHQto5Luvl5PqCYmcGsF
    method: GET
    headers:
      content-type: application/json
      authorization: Token123456
    timeout: 10
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watchByDefault: true

```

### `docker-compose.yml`
```
version: "3.2"
services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    volumes:
      - "$USERDIR/docker/diun/data:/data"
      - "$USERDIR/docker/diun/diun.yml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Paris"
      - "LOG_LEVEL=debug"
      - "LOG_JSON=false"
    restart: always

```

### Logs

```
Sun, 12 Jul 2020 20:39:44 CEST INF Starting Diun 3.0.0
Sun, 12 Jul 2020 20:39:44 CEST FTL Cannot load configuration error="unable to decode into struct, yaml: unmarshal errors:\n  line 12: field watchByDefault not found in type model.PrdDocker"
Sun, 12 Jul 2020 20:39:46 CEST INF Starting Diun 3.0.0
Sun, 12 Jul 2020 20:39:46 CEST FTL Cannot load configuration error="unable to decode into struct, yaml: unmarshal errors:\n  line 12: field watchByDefault not found in type model.PrdDocker"
```
