### ISSUE TITLE
Docker Provider : Remote Manifest error

### ISSUE THREAD

**Issue by stauders** [crazy-max/diun#134]
### Behaviour
https://crazy-max.github.io/diun/faq/#field-dockerswarm-uses-unsupported-type-invalid says this error should happen if I'm using the file provider, but I am using the docker provider. There is no solution for this provider offered in the FAQ

#### Expected behaviour

> No error messages appearing

#### Actual behaviour

> Error message

### Configuration

* Diun version : docker/latest
* Platform (windows/linux) :linux
* System info (type `uname -a`) : Linux LucasVPS 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```yaml
watch:
  workers: 20
  schedule: "*/30 * * * *"
  firstCheckNotif: true
providers:
  docker:
    watchStopped: true
    watchByDefault: true

notif:
  mail:

```

### Logs

```
iun_1  | Fri, 24 Jul 2020 09:00:05 CEST WRN Cannot get remote manifest error="Cannot inspect: Get https://registry-1.docker.io/v2/mailcow/acme/blobs/sha256:8393991e9e665dd02e9961b57ca8d352c2165359f9a2c6203830e529127e1b39: EOF" image=docker.io/mailcow/acme:1.73 provider=docker
diun_1  | Fri, 24 Jul 2020 09:00:05 CEST WRN Cannot get remote manifest error="Cannot inspect: Get https://registry-1.docker.io/v2/mailcow/dovecot/blobs/sha256:7db4dc67d3434b0f1e9e825569947c87dc27f8041f0efacb0565411b19ee01d6: EOF" image=docker.io/mailcow/dovecot:1.128 provider=docker

```
