### ISSUE TITLE
Loading secrets from file not working

### ISSUE THREAD

**Issue by jey3dee** [crazy-max/diun#1358]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/crazy-max/diun/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [x] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

I suspect a bug in loading username and password from file, as required by the SMTP notification. This may be related to [Unsupported external secret #799](https://github.com/crazy-max/diun/issues/799). I'm running Diun with Docker Compose:

```
secrets:
  smtp_password:
    file: $DOCKERDIR/secrets/smtp_password

services:
  diun:
    container_name: diun
    image: crazymax/diun:4.29.0
    restart: unless-stopped
    command: serve
    networks:
      - web_proxy
      - socket_proxy
    volumes:
      - $DOCKERDIR/data/diun:/data
    secrets:
      - smtp_user
      - smtp_password
    environment:
      - TZ=$TZ
      - LOG_LEVEL=debug
      - LOG_JSON=false
      - DIUN_NOTIF_MAIL_HOST=${MAIL_HOST}
      - DIUN_NOTIF_MAIL_PORT=587
      - DIUN_NOTIF_MAIL_SSL=false
      - DIUN_NOTIF_MAIL_INSECURESKIPVERIFY=false
      - DIUN_NOTIF_MAIL_LOCALNAME=${HOSTNAME}
      - DIUN_NOTIF_MAIL_FROM=${MAIL_USER}
      - DIUN_NOTIF_MAIL_TO=${MAIL_USER}
      - DIUN_NOTIF_MAIL_USERNAME=${MAIL_USER}
      - DIUN_NOTIF_MAIL_PASSWORDFILE=/run/secrets/smtp_password
      #- DIUN_NOTIF_MAIL_PASSWORD=mysupersafepassword
      - DIUN_NOTIF_MAIL_TEMPLATETITLE="{{ .Entry.Image }} released"
      - DIUN_NOTIF_MAIL_TEMPLATEBODY="Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released."
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_ENDPOINT=tcp://docker-socket-proxy:2375
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
```

For testing the notification, I use `diun notif test` inside the running docker container. When I specify the password with `DIUN_NOTIF_MAIL_PASSWORD`, as shown in the commented line above, it works and a test email is sent. As soon as I use `DIUN_NOTIF_MAIL_PASSWORDFILE`, I get the following error:

`diun: error: rpc error: code = Unknown desc = 535 5.7.8 Error: authentication failed: `

This is the corresponding entry in the `mail.log` on the receiving mail server:

```
Feb  4 11:50:01 yyy postfix/submission/smtpd[27927]: warning: xxx: SASL PLAIN authentication failed:
Feb  4 11:50:01 yyy postfix/submission/smtpd[27927]: disconnect from xxx ehlo=2 starttls=1 auth=0/1 quit=1 unknown=0/1 commands=4/6
```

The same happens when I use `DIUN_NOTIF_MAIL_USERNAMEFILE`. I verified that the password in the file via `cat -e /run/secrets/smtp_password`, it is correct and has no additional line breaks etc. I set the access rights to 777 for testing:

```
drwxr-xr-x    2 root     root        4.0K Feb  4 12:28 .
drwxr-xr-x    1 root     root        4.0K Feb  4 12:28 ..
-rwxrwxrwx    1 root     root          65 Feb  4 12:11 smtp_password
-rwxrwxrwx    1 root     root          24 Feb  4 12:26 smtp_user
```

Since it works with directly specifying the password, the password in the mounted secret file seems to be correct, the access rights seem to be correct and it works with the password being specified directly, I conclude that there is a bug here.

Can you please confirm?

### Expected behaviour

The SMTP notification should be sent when the password is specified via a file.

### Actual behaviour

No SMTP notification is sent when the password is specified via a file, only when it is specified directly.

### Steps to reproduce

1. Create the file with the secret.
2. Execute the above docker compose file.
3. `docker exec -it diun sh`
4. `diun notif test`

### Diun version

4.29.0

### Docker info

```text
Client: Docker Engine - Community
 Version:    27.5.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.3
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.32.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 14
  Running: 3
  Paused: 0
  Stopped: 11
 Images: 36
 Server Version: 27.5.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc version: v1.2.4-0-g6c52b3f
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-52-generic
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 31.27GiB
 Name: j-desktop
 ID: 2747a7ae-93bb-44bd-8163-1fac079c1b5a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Docker Compose config

```yaml
name: compose                                                                                                                                                                                                                                                                                                                                                                       
services: 
  diun:
    command:
      - serve
    container_name: diun
    environment:
      DIUN_NOTIF_MAIL_FROM: xxxxx
      DIUN_NOTIF_MAIL_HOST: xxxxx
      DIUN_NOTIF_MAIL_INSECURESKIPVERIFY: "false"
      DIUN_NOTIF_MAIL_LOCALNAME: xxxxx
      DIUN_NOTIF_MAIL_PASSWORDFILE: /run/secrets/smtp_password
      DIUN_NOTIF_MAIL_PORT: "587"
      DIUN_NOTIF_MAIL_SSL: "false"
      DIUN_NOTIF_MAIL_TEMPLATEBODY: '"Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released."'
      DIUN_NOTIF_MAIL_TEMPLATETITLE: '"{{ .Entry.Image }} released"'
      DIUN_NOTIF_MAIL_TO: xxxxx
      DIUN_NOTIF_MAIL_USERNAME: xxxxx
      DIUN_PROVIDERS_DOCKER: "true"
      DIUN_PROVIDERS_DOCKER_ENDPOINT: tcp://docker-socket-proxy:2375
      DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT: "true"
      DIUN_WATCH_JITTER: 30s
      DIUN_WATCH_SCHEDULE: 0 */6 * * *
      DIUN_WATCH_WORKERS: "20"
      LOG_JSON: "false"
      LOG_LEVEL: debug
      TZ: Europe/Berlin
    image: crazymax/diun:4.29.0
    networks:
      socket_proxy: null
      web_proxy: null
    restart: unless-stopped
    secrets:
      - source: smtp_user
        target: /run/secrets/smtp_user
      - source: smtp_password
        target: /run/secrets/smtp_password
    volumes:
      - type: bind
        source: /docker/data/diun
        target: /data
        bind:
          create_host_path: true
  docker-socket-proxy:
    container_name: docker-socket-proxy
    environment:
      CONTAINERS: "1"
      IMAGES: "1"
    image: lscr.io/linuxserver/socket-proxy:1.26.2-r4-ls41
    networks:
      socket_proxy: null
    read_only: true
    restart: unless-stopped
    tmpfs:
      - /run
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
        bind:
          create_host_path: true
networks:
  socket_proxy:
    name: socket_proxy
    driver: bridge
  web_proxy:
    name: compose_web_proxy
    driver: bridge
secrets:
  smtp_password:
    name: compose_smtp_password
    file: /docker/secrets/smtp_password
  smtp_user:
    name: compose_smtp_user
    file: /docker/secrets/smtp_user
```

### Logs

```text
Attaching to diun, docker-socket-proxy
docker-socket-proxy  | 
docker-socket-proxy  | ───────────────────────────────────────
docker-socket-proxy  | 
docker-socket-proxy  |       ██╗     ███████╗██╗ ██████╗
docker-socket-proxy  |       ██║     ██╔════╝██║██╔═══██╗
docker-socket-proxy  |       ██║     ███████╗██║██║   ██║
docker-socket-proxy  |       ██║     ╚════██║██║██║   ██║
docker-socket-proxy  |       ███████╗███████║██║╚██████╔╝
docker-socket-proxy  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
docker-socket-proxy  | 
docker-socket-proxy  |     Brought to you by linuxserver.io
docker-socket-proxy  | ───────────────────────────────────────
docker-socket-proxy  | ───────────────────────────────────────
docker-socket-proxy  | 
docker-socket-proxy  | To support LSIO projects visit:
docker-socket-proxy  | https://www.linuxserver.io/donate/
docker-socket-proxy  | 
docker-socket-proxy  | ───────────────────────────────────────
docker-socket-proxy  | Linuxserver.io version: 1.26.2-r4-ls41
docker-socket-proxy  | Build-date: 2025-02-03T20:44:51+00:00
docker-socket-proxy  | ───────────────────────────────────────
docker-socket-proxy  |     
docker-socket-proxy  | [ls.io-init] done.
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m [32mINF[0m [1mgithub.com/crazy-max/diun/v4/cmd/serve.go:38[0m[36m >[0m [1mStarting Diun[0m [36mversion=[0mv4.29.0
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/config/config.go:43[0m[36m >[0m No configuration file found
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m [32mINF[0m [1mgithub.com/crazy-max/diun/v4/internal/config/config.go:56[0m[36m >[0m [1mConfiguration loaded from 18 environment variable(s)[0m
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/cmd/serve.go:55[0m[36m >[0m {
diun                 |   "db": {
diun                 |     "path": "/data/diun.db"
diun                 |   },
diun                 |   "watch": {
diun                 |     "workers": 20,
diun                 |     "schedule": "0 */6 * * *",
diun                 |     "jitter": 30000000000,
diun                 |     "firstCheckNotif": false,
diun                 |     "runOnStartup": true,
diun                 |     "compareDigest": true
diun                 |   },
diun                 |   "defaults": {
diun                 |     "watchRepo": false,
diun                 |     "notifyOn": [
diun                 |       "new",
diun                 |       "update"
diun                 |     ],
diun                 |     "sortTags": "reverse"
diun                 |   },
diun                 |   "notif": {
diun                 |     "mail": {
diun                 |       "host": "xxxxx",
diun                 |       "port": 587,
diun                 |       "ssl": false,
diun                 |       "insecureSkipVerify": false,
diun                 |       "localName": "xxxxx",
diun                 |       "username": "xxxxx",
diun                 |       "passwordFile": "/run/secrets/smtp_password",
diun                 |       "from": "xxxxx",
diun                 |       "to": [
diun                 |         "xxxxx"
diun                 |       ],
diun                 |       "templateTitle": "\"{{ .Entry.Image }} released\"",
diun                 |       "templateBody": "\"Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released.\""
diun                 |     }
diun                 |   },
diun                 |   "providers": {
diun                 |     "docker": {
diun                 |       "endpoint": "tcp://docker-socket-proxy:2375",
diun                 |       "tlsVerify": true,
diun                 |       "watchByDefault": true,
diun                 |       "watchStopped": false
diun                 |     }
diun                 |   }
diun                 | }
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/notif/client.go:93[0m[36m >[0m 1 notifier(s) created
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/db/client.go:52[0m[36m >[0m 5 entries found in manifest bucket
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/db/client.go:73[0m[36m >[0m Current database version: 2
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m [32mINF[0m [1mgithub.com/crazy-max/diun/v4/internal/app/diun.go:142[0m[36m >[0m [1mCron triggered[0m
docker-socket-proxy  | 172.22.0.3 - - [04/Feb/2025:12:02:20 +0000] "HEAD /_ping HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
docker-socket-proxy  | 172.22.0.3 - - [04/Feb/2025:12:02:20 +0000] "GET /v1.47/version HTTP/1.1" 200 822 "-" "Go-http-client/1.1"
docker-socket-proxy  | 172.22.0.3 - - [04/Feb/2025:12:02:20 +0000] "GET /v1.47/containers/json?filters=%7B%22status%22%3A%7B%22running%22%3Atrue%7D%7D HTTP/1.1" 200 7951 "-" "Go-http-client/1.1"
docker-socket-proxy  | 172.22.0.3 - - [04/Feb/2025:12:02:20 +0000] "GET /v1.47/images/crazymax/diun:4.29.0/json HTTP/1.1" 200 2256 "-" "Go-http-client/1.1"
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/provider/docker/container.go:93[0m[36m >[0m Validate image [36mctn_id=[0m6f710b312d1c443ac19dad806b585220e70201c1db96bc178b76f2d31dbdb380 [36mctn_image=[0mcrazymax/diun:4.29.0 [36mctn_labels=[0m{"com.docker.compose.config-hash":"2218a89b6c24e0bd662dd134c25eed10d6b3a123e9bf6f377a04f1ab965f80ca","com.docker.compose.container-number":"1","com.docker.compose.depends_on":"","com.docker.compose.image":"sha256:d404f13e22b537b00d034b4719e0dcd4abcb191b1dcf35c22bc357ad7d3fde79","com.docker.compose.oneoff":"False","com.docker.compose.project":"compose","com.docker.compose.project.config_files":"/docker/compose/main.yml","com.docker.compose.project.working_dir":"/docker/compose","com.docker.compose.replace":"366a6b8083f57e17971eab029d66f47f4a5d7334cabb36a5e9f697d15dbc34c8","com.docker.compose.service":"diun","com.docker.compose.version":"2.32.3","org.opencontainers.image.created":"2024-12-19T17:20:18.783Z","org.opencontainers.image.description":"Docker image update notifier","org.opencontainers.image.licenses":"MIT","org.opencontainers.image.revision":"1ca5d37370a57965fa55979d9e9aa4e177ddf193","org.opencontainers.image.source":"https://github.com/crazy-max/diun","org.opencontainers.image.title":"Diun","org.opencontainers.image.url":"https://github.com/crazy-max/diun","org.opencontainers.image.vendor":"CrazyMax","org.opencontainers.image.version":"4.29.0"} [36mprovider=[0mdocker
docker-socket-proxy  | 172.22.0.3 - - [04/Feb/2025:12:02:20 +0000] "GET /v1.47/images/ghcr.io/open-webui/open-webui:main/json HTTP/1.1" 200 5342 "-" "Go-http-client/1.1"
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/provider/docker/container.go:93[0m[36m >[0m Validate image [36mctn_id=[0mab26a031fd90df9c7d1dd5531f59915f854de11c28af573826d4742f41148ff5 [36mctn_image=[0mghcr.io/open-webui/open-webui:main [36mctn_labels=[0m{"com.docker.compose.config-hash":"469cc1b10e7fce8a02cac0729ad2077a12eb71b75e94555c8bb6946b829a466c","com.docker.compose.container-number":"1","com.docker.compose.depends_on":"ollama:service_started:false","com.docker.compose.image":"sha256:adb86c02cf4b2dca5b62156213a53ed3fca827b4c1fd99a3d616f9623df7193c","com.docker.compose.oneoff":"False","com.docker.compose.project":"ollama","com.docker.compose.project.config_files":"/home/joachim/docker/ollama/docker-compose.yaml","com.docker.compose.project.working_dir":"/home/joachim/docker/ollama","com.docker.compose.service":"ollama-webui","com.docker.compose.version":"2.26.1","org.opencontainers.image.created":"2024-05-09T00:21:43.028Z","org.opencontainers.image.description":"User-friendly WebUI for LLMs (Formerly Ollama WebUI)","org.opencontainers.image.licenses":"MIT","org.opencontainers.image.revision":"90503be2edef1a1f7ce2074286b6316d5cb8868a","org.opencontainers.image.source":"https://github.com/open-webui/open-webui","org.opencontainers.image.title":"open-webui","org.opencontainers.image.url":"https://github.com/open-webui/open-webui","org.opencontainers.image.version":"main"} [36mprovider=[0mdocker
docker-socket-proxy  | 172.22.0.3 - - [04/Feb/2025:12:02:20 +0000] "GET /v1.47/images/lscr.io/linuxserver/socket-proxy:1.26.2-r4-ls41/json HTTP/1.1" 200 3204 "-" "Go-http-client/1.1"
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/provider/docker/container.go:93[0m[36m >[0m Validate image [36mctn_id=[0m9cf9501a8103034986df9d0372351620adbdcc846a4c5b46620932e78c3cff94 [36mctn_image=[0mlscr.io/linuxserver/socket-proxy:1.26.2-r4-ls41 [36mctn_labels=[0m{"build_version":"Linuxserver.io version:- 1.26.2-r4-ls41 Build-date:- 2025-02-03T20:44:51+00:00","com.docker.compose.config-hash":"3db9618b195723ed3292ac040db87e1eb6de58eb26fbf78523019c5407d19d18","com.docker.compose.container-number":"1","com.docker.compose.depends_on":"","com.docker.compose.image":"sha256:04f1b409b37ff218b460a1e6aba8bb80c0c1311aff074c2a629b6a13fdcae89a","com.docker.compose.oneoff":"False","com.docker.compose.project":"compose","com.docker.compose.project.config_files":"/docker/compose/main.yml","com.docker.compose.project.working_dir":"/docker/compose","com.docker.compose.replace":"82173a18792bf60df4d6b20fa17d59926c66bb6a7a604fb0efd9e538ab4ce800","com.docker.compose.service":"docker-socket-proxy","com.docker.compose.version":"2.32.3","maintainer":"thespad","org.opencontainers.image.authors":"linuxserver.io","org.opencontainers.image.created":"2025-02-03T20:44:51+00:00","org.opencontainers.image.description":"The Socket Proxy is a security-enhanced proxy which allows you to apply access rules to the Docker socket, limiting the attack surface for containers such as watchtower or Traefik that need to use it.","org.opencontainers.image.documentation":"https://docs.linuxserver.io/images/docker-socket-proxy","org.opencontainers.image.licenses":"GPL-3.0-only","org.opencontainers.image.ref.name":"375734e6aa976f5d1fd1f95c3ab86a2050153727","org.opencontainers.image.revision":"375734e6aa976f5d1fd1f95c3ab86a2050153727","org.opencontainers.image.source":"https://github.com/linuxserver/docker-socket-proxy","org.opencontainers.image.title":"Socket-proxy","org.opencontainers.image.url":"https://github.com/linuxserver/docker-socket-proxy/packages","org.opencontainers.image.vendor":"linuxserver.io","org.opencontainers.image.version":"1.26.2-r4-ls41"} [36mprovider=[0mdocker
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m [32mINF[0m [1mgithub.com/crazy-max/diun/v4/internal/provider/docker/docker.go:41[0m[36m >[0m [1mFound 3 image(s) to analyze[0m [36mprovider=[0mdocker
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] Loading registries configuration "/etc/containers/registries.conf"
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] No credentials matching docker.io found in /run/containers/0/auth.json
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] No credentials matching docker.io found in /root/.config/containers/auth.json
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] No credentials matching docker.io found in /root/.docker/config.json
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] No credentials matching docker.io found in /root/.dockercfg
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] No credentials for docker.io found
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] No credentials matching ghcr.io found in /run/containers/0/auth.json
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] No credentials matching ghcr.io found in /root/.config/containers/auth.json
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] No credentials matching ghcr.io found in /root/.docker/config.json
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] No credentials matching ghcr.io found in /root/.dockercfg
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] No credentials for ghcr.io found
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] Using registries.d directory /etc/containers/registries.d
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] Returning credentials for docker.io/crazymax/diun from DockerAuthConfig
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image]  No signature storage configuration found for docker.io/crazymax/diun:4.29.0, using built-in default file:///var/lib/containers/sigstore
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] No credentials matching lscr.io found in /run/containers/0/auth.json
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] No credentials matching lscr.io found in /root/.config/containers/auth.json
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] No credentials matching lscr.io found in /root/.docker/config.json
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] No credentials matching lscr.io found in /root/.dockercfg
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] No credentials for lscr.io found
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] GET https://registry-1.docker.io/v2/
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] Using registries.d directory /etc/containers/registries.d
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] Returning credentials for ghcr.io/open-webui/open-webui from DockerAuthConfig
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image]  No signature storage configuration found for ghcr.io/open-webui/open-webui:main, using built-in default file:///var/lib/containers/sigstore
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] Looking for TLS certificates and private keys in /etc/docker/certs.d/ghcr.io
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] Using registries.d directory /etc/containers/registries.d
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] Returning credentials for lscr.io/linuxserver/socket-proxy from DockerAuthConfig
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image]  No signature storage configuration found for lscr.io/linuxserver/socket-proxy:1.26.2-r4-ls41, using built-in default file:///var/lib/containers/sigstore
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] Looking for TLS certificates and private keys in /etc/docker/certs.d/lscr.io
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] GET https://lscr.io/v2/
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] GET https://ghcr.io/v2/
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] Ping https://ghcr.io/v2/ status 401
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] GET https://ghcr.io/token?scope=repository%3Aopen-webui%2Fopen-webui%3Apull&service=ghcr.io
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] Ping https://lscr.io/v2/ status 401
diun                 | [90mTue, 04 Feb 2025 13:02:20 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] GET https://ghcr.io/token?scope=repository%3Alinuxserver%2Fsocket-proxy%3Apull&service=ghcr.io
diun                 | [90mTue, 04 Feb 2025 13:02:21 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] Ping https://registry-1.docker.io/v2/ status 401
diun                 | [90mTue, 04 Feb 2025 13:02:21 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] GET https://auth.docker.io/token?scope=repository%3Acrazymax%2Fdiun%3Apull&service=registry.docker.io
diun                 | [90mTue, 04 Feb 2025 13:02:21 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] Increasing token expiration to: 60 seconds
diun                 | [90mTue, 04 Feb 2025 13:02:21 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] HEAD https://ghcr.io/v2/open-webui/open-webui/manifests/main
diun                 | [90mTue, 04 Feb 2025 13:02:21 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] Increasing token expiration to: 60 seconds
diun                 | [90mTue, 04 Feb 2025 13:02:21 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] HEAD https://lscr.io/v2/linuxserver/socket-proxy/manifests/1.26.2-r4-ls41
diun                 | [90mTue, 04 Feb 2025 13:02:21 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/app/job.go:218[0m[36m >[0m No changes [36mimage=[0mghcr.io/open-webui/open-webui:main [36mprovider=[0mdocker
diun                 | [90mTue, 04 Feb 2025 13:02:21 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/app/job.go:225[0m[36m >[0m Manifest saved to database [36mimage=[0mghcr.io/open-webui/open-webui:main [36mprovider=[0mdocker
diun                 | [90mTue, 04 Feb 2025 13:02:21 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/app/job.go:218[0m[36m >[0m No changes [36mimage=[0mlscr.io/linuxserver/socket-proxy:1.26.2-r4-ls41 [36mprovider=[0mdocker
diun                 | [90mTue, 04 Feb 2025 13:02:21 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/app/job.go:225[0m[36m >[0m Manifest saved to database [36mimage=[0mlscr.io/linuxserver/socket-proxy:1.26.2-r4-ls41 [36mprovider=[0mdocker
diun                 | [90mTue, 04 Feb 2025 13:02:21 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/logging/logger.go:74[0m[36m >[0m [containers/image] HEAD https://registry-1.docker.io/v2/crazymax/diun/manifests/4.29.0
diun                 | [90mTue, 04 Feb 2025 13:02:21 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/app/job.go:218[0m[36m >[0m No changes [36mimage=[0mdocker.io/crazymax/diun:4.29.0 [36mprovider=[0mdocker
diun                 | [90mTue, 04 Feb 2025 13:02:21 CET[0m DBG [1mgithub.com/crazy-max/diun/v4/internal/app/job.go:225[0m[36m >[0m Manifest saved to database [36mimage=[0mdocker.io/crazymax/diun:4.29.0 [36mprovider=[0mdocker
diun                 | [90mTue, 04 Feb 2025 13:02:21 CET[0m [32mINF[0m [1mgithub.com/crazy-max/diun/v4/internal/app/diun.go:192[0m[36m >[0m [1mJobs completed[0m [36madded=[0m0 [36mfailed=[0m0 [36mskipped=[0m0 [36munchanged=[0m3 [36mupdated=[0m0
diun                 | [90mTue, 04 Feb 2025 13:02:21 CET[0m [32mINF[0m [1mgithub.com/crazy-max/diun/v4/internal/app/diun.go:118[0m[36m >[0m [1mCron initialized with schedule 0 */6 * * *[0m
diun                 | [90mTue, 04 Feb 2025 13:02:21 CET[0m [32mINF[0m [1mgithub.com/crazy-max/diun/v4/internal/app/diun.go:122[0m[36m >[0m [1mNext run in 4 hours 57 minutes (2025-02-04 18:00:08.052962578 +0100 CET)[0m
```

### Additional info

_No response_
