### ISSUE TITLE
Cannot get remote Manifest installation Docker-compose

### ISSUE THREAD

**Issue by sljdhl** [crazy-max/diun#137]
### Behaviour
Problem with installation, cannot gget remote manifest. Test notification works. 

### Configuration

* Diun version : 4.2.0
* Platform (windows/linux) : Linux
* System info (type `uname -a`) :  Linux mediaserver 5.0.0-38-generic #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```yaml
# paste your YAML configuration file here and remove sensitive data
version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    volumes:
      - "/home/docker/diun/data:/data"
      - "./diun.yml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Stockholm"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    restart: always

---
watch:
  workers: 20
  schedule: "*/30 * * * *"
  firstCheckNotif: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watchByDefault: true

notif:
  discord:
    webhookURL: https://discordapp.com/api/webhooks/XXX
    timeout: 10s
```

### Logs

```
`diun    | Wed, 29 Jul 2020 20:33:12 CEST WRN Cannot get remote manifest error="Cannot create image closer: Error reading manifest 97df12fa9319e80eaf163f0ace0827a2ae5cb822dedc014710f72e38868fc724 in docker.io/library/sha256: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"`
