### ISSUE TITLE
Add ability to specify image cache repositories in regopts

### ISSUE THREAD

**Issue by vrga** [crazy-max/diun#1386]
### Description

Basically, i'm hosting docker-registries running in cache mode in my local network for use with multiple upstream registries (`docker.io`, `ghcr.io`, `quay.io` specifically)
I'd like to configure diun to target my local caches rather than the upstreams.

current configuration is like this example, but obviously, this does not work:
```yaml
  regopts:
    - name:     'registry-cache-docker.example.com'
      selector: 'docker.io'
    - name:     'registry-cache-ghcr.example.com'
      selector: 'ghcr.io'
    - name:     'registry-cache-quay.example.com'
      selector: 'quay.io'
```

I'm not a 100% sure if this is just a mistake on my reading of the docs, but basically, the idea would be to override the `docker.io` part of `docker.io/chrislusf/seaweedfs:3.85` for example and redirect the check to my cache.

If this is actually already possible, could a documentation example be provided please?
Apologies if its a nonsensical request 😅
