### ISSUE TITLE
Wrong image found when sorting by semver

### ISSUE THREAD

**Issue by jkbach** [crazy-max/diun#1419]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/crazy-max/diun/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

### Description

Using the `file` provider with the following config, `docker.io/pihole/pihole`, returns an old semver image instead of the latest.

```yaml
- name: pihole/pihole
  watch_repo: true
  max_tags: 1
  sort_tags: semver
  include_tags:
     - ^\d+\.\d+\.\d+$
```

### Expected behaviour

Should return the newest semver version that matches my `include_tags`. In the case of `pihole`, this is [`2025.04.0`](https://hub.docker.com/layers/pihole/pihole/2025.04.0/images/sha256-c0cffcddafb5c91e194e2c0bd3575e3a29efe5170384224a94f44e14e80869fb).

### Actual behaviour

Actually returns a much older version [`2023.11.0`](https://hub.docker.com/layers/pihole/pihole/2023.11.0).

### Steps to reproduce

1. Create a minimal config:
   ```yaml
   # docker-compose.yaml
   services:
     diun:
       image: crazymax/diun:4.29.0
       command: serve
       volumes:
         - './data:/data'
         - "./diun.yml:/etc/diun/diun.yml:ro"
         - "./watch-config.yml:/etc/diun/watch-config.yml:ro"
       environment:
         - "TZ=Asia/Taipei"
         - "LOG_LEVEL=debug"
       restart: unless-stopped

   ```
   ```yaml
   # diun.yml

   watch:
     # Run every friday at 5pm
     schedule: "0 17 * * 5"
     firstCheckNotif: true

   providers:
     file:
     filename: /etc/diun/watch-config.yml
   ```

   ```yaml
   # watch-config.yml

   - name: pihole/pihole
     watch_repo: true
     max_tags: 1
     sort_tags: semver
     include_tags:
       - ^\d+\.\d+\.\d+$
   ```
2. `docker compose up`
3. Observe that `diun` finds the older version `2023.11.0` instead of `2025.04.0`

### Diun version

4.29.0

### Docker info

```text
Client: Docker Engine - Community
 Version:    28.2.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.24.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.36.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 9
  Running: 6
  Paused: 0
  Stopped: 3
 Images: 11
 Server Version: 28.2.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: local
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.21-v8+
 Operating System: Raspbian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 1.806GiB
 Name: pipsqueak
 ID: d6e5946e-9e38-462d-b0e5-046069ca1c65
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
```

### Docker Compose config

```yaml
name: diun
services:
  diun:
    command:
      - serve
    environment:
      LOG_CALLER: "true"
      LOG_LEVEL: debug
      TZ: Asia/Taipei
    image: crazymax/diun:4.29.0
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: /home/pi/service-configs/diun/data
        target: /data
        bind:
          create_host_path: true
      - type: bind
        source: /home/pi/service-configs/diun/diun.yml
        target: /etc/diun/diun.yml
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /home/pi/service-configs/diun/watch-config.yml
        target: /etc/diun/watch-config.yml
        read_only: true
        bind:
          create_host_path: true
networks:
  default:
    name: diun_default
```

### Logs

```text
[+] Running 2/2
 ✔ Network diun_default   Created                                        0.2s 
 ✔ Container diun-diun-1  Recreated                                      0.4s 
Attaching to diun-1
diun-1  | Fri, 30 May 2025 12:08:46 CST INF github.com/crazy-max/diun/v4/cmd/serve.go:38 > Starting Diun version=v4.29.0
diun-1  | Fri, 30 May 2025 12:08:46 CST INF github.com/crazy-max/diun/v4/internal/config/config.go:45 > Configuration loaded from file: /etc/diun/diun.yml
diun-1  | Fri, 30 May 2025 12:08:46 CST INF github.com/crazy-max/diun/v4/internal/config/config.go:56 > Configuration loaded from 1 environment variable(s)
diun-1  | Fri, 30 May 2025 12:08:46 CST DBG github.com/crazy-max/diun/v4/cmd/serve.go:55 > {
diun-1  |   "db": {
diun-1  |     "path": "/data/diun.db"
diun-1  |   },
diun-1  |   "watch": {
diun-1  |     "workers": 10,
diun-1  |     "schedule": "0 17 * * 5",
diun-1  |     "jitter": 30000000000,
diun-1  |     "firstCheckNotif": true,
diun-1  |     "runOnStartup": true,
diun-1  |     "compareDigest": true
diun-1  |   },
diun-1  |   "defaults": {
diun-1  |     "watchRepo": false,
diun-1  |     "notifyOn": [
diun-1  |       "new",
diun-1  |       "update"
diun-1  |     ],
diun-1  |     "sortTags": "reverse"
diun-1  |   },
diun-1  |   "providers": {
diun-1  |     "file": {
diun-1  |       "filename": "/etc/diun/watch-config.yml"
diun-1  |     }
diun-1  |   }
diun-1  | }
diun-1  | Fri, 30 May 2025 12:08:46 CST WRN github.com/crazy-max/diun/v4/internal/notif/client.go:42 > No notifier available
diun-1  | Fri, 30 May 2025 12:08:46 CST DBG github.com/crazy-max/diun/v4/internal/db/client.go:52 > 0 entries found in manifest bucket
diun-1  | Fri, 30 May 2025 12:08:46 CST DBG github.com/crazy-max/diun/v4/internal/db/client.go:73 > Current database version: 1
diun-1  | Fri, 30 May 2025 12:08:46 CST INF github.com/crazy-max/diun/v4/internal/db/migrate.go:29 > Database migration v2...
diun-1  | Fri, 30 May 2025 12:08:46 CST INF github.com/crazy-max/diun/v4/internal/app/diun.go:142 > Cron triggered
diun-1  | Fri, 30 May 2025 12:08:46 CST INF github.com/crazy-max/diun/v4/internal/provider/file/file.go:41 > Found 1 image(s) to analyze provider=file
diun-1  | Fri, 30 May 2025 12:08:46 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] Loading registries configuration "/etc/containers/registries.conf"
diun-1  | Fri, 30 May 2025 12:08:46 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] No credentials matching docker.io found in /run/containers/0/auth.json
diun-1  | Fri, 30 May 2025 12:08:46 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] No credentials matching docker.io found in /root/.config/containers/auth.json
diun-1  | Fri, 30 May 2025 12:08:46 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] No credentials matching docker.io found in /root/.docker/config.json
diun-1  | Fri, 30 May 2025 12:08:46 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] No credentials matching docker.io found in /root/.dockercfg
diun-1  | Fri, 30 May 2025 12:08:46 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] No credentials for docker.io found
diun-1  | Fri, 30 May 2025 12:08:46 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] Using registries.d directory /etc/containers/registries.d
diun-1  | Fri, 30 May 2025 12:08:46 CST DBG github.com/crazy-max/diun/v4/internal/app/job.go:182 > Tag not included image=docker.io/pihole/pihole:latest provider=file
diun-1  | Fri, 30 May 2025 12:08:46 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] Returning credentials for docker.io/pihole/pihole from DockerAuthConfig
diun-1  | Fri, 30 May 2025 12:08:46 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image]  No signature storage configuration found for docker.io/pihole/pihole:latest, using built-in default file:///var/lib/containers/sigstore
diun-1  | Fri, 30 May 2025 12:08:46 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io
diun-1  | Fri, 30 May 2025 12:08:46 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] GET https://registry-1.docker.io/v2/
diun-1  | Fri, 30 May 2025 12:08:47 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] Ping https://registry-1.docker.io/v2/ status 401
diun-1  | Fri, 30 May 2025 12:08:47 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] GET https://auth.docker.io/token?scope=repository%3Apihole%2Fpihole%3Apull&service=registry.docker.io
diun-1  | Fri, 30 May 2025 12:08:48 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] GET https://registry-1.docker.io/v2/pihole/pihole/tags/list
diun-1  | Fri, 30 May 2025 12:08:48 CST DBG github.com/crazy-max/diun/v4/internal/app/job.go:137 > 108 tag(s) found in repository. 1 will be analyzed (1 max, 48 not included, 0 excluded). image=docker.io/pihole/pihole:latest
diun-1  | Fri, 30 May 2025 12:08:48 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] Using registries.d directory /etc/containers/registries.d
diun-1  | Fri, 30 May 2025 12:08:48 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] Returning credentials for docker.io/pihole/pihole from DockerAuthConfig
diun-1  | Fri, 30 May 2025 12:08:48 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image]  No signature storage configuration found for docker.io/pihole/pihole:2023.11.0, using built-in default file:///var/lib/containers/sigstore
diun-1  | Fri, 30 May 2025 12:08:48 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io
diun-1  | Fri, 30 May 2025 12:08:48 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] GET https://registry-1.docker.io/v2/
diun-1  | Fri, 30 May 2025 12:08:49 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] Ping https://registry-1.docker.io/v2/ status 401
diun-1  | Fri, 30 May 2025 12:08:49 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] GET https://auth.docker.io/token?scope=repository%3Apihole%2Fpihole%3Apull&service=registry.docker.io
diun-1  | Fri, 30 May 2025 12:08:49 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] HEAD https://registry-1.docker.io/v2/pihole/pihole/manifests/2023.11.0
diun-1  | Fri, 30 May 2025 12:08:50 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] Using registries.d directory /etc/containers/registries.d
diun-1  | Fri, 30 May 2025 12:08:50 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] Trying to access "docker.io/pihole/pihole:2023.11.0"
diun-1  | Fri, 30 May 2025 12:08:50 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] Returning credentials for docker.io/pihole/pihole from DockerAuthConfig
diun-1  | Fri, 30 May 2025 12:08:50 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image]  No signature storage configuration found for docker.io/pihole/pihole:2023.11.0, using built-in default file:///var/lib/containers/sigstore
diun-1  | Fri, 30 May 2025 12:08:50 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io
diun-1  | Fri, 30 May 2025 12:08:50 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] GET https://registry-1.docker.io/v2/
diun-1  | Fri, 30 May 2025 12:08:51 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] Ping https://registry-1.docker.io/v2/ status 401
diun-1  | Fri, 30 May 2025 12:08:51 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] GET https://auth.docker.io/token?scope=repository%3Apihole%2Fpihole%3Apull&service=registry.docker.io
diun-1  | Fri, 30 May 2025 12:08:51 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] GET https://registry-1.docker.io/v2/pihole/pihole/manifests/2023.11.0
diun-1  | Fri, 30 May 2025 12:08:52 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] Content-Type from manifest GET is "application/vnd.docker.distribution.manifest.list.v2+json"
diun-1  | Fri, 30 May 2025 12:08:52 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] GET https://registry-1.docker.io/v2/pihole/pihole/manifests/sha256:4d11cfd13f07c0242df02fb04aaaf51079c69c33586074a0937b6616a79e8017
diun-1  | Fri, 30 May 2025 12:08:52 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] Content-Type from manifest GET is "application/vnd.docker.distribution.manifest.v2+json"
diun-1  | Fri, 30 May 2025 12:08:52 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] Downloading /v2/pihole/pihole/blobs/sha256:1e5167d1e8cf0aa908ca3893bd186e391e1283764088b4af89f121765722f47f
diun-1  | Fri, 30 May 2025 12:08:52 CST DBG github.com/crazy-max/diun/v4/internal/logging/logger.go:74 > [containers/image] GET https://registry-1.docker.io/v2/pihole/pihole/blobs/sha256:1e5167d1e8cf0aa908ca3893bd186e391e1283764088b4af89f121765722f47f
diun-1  | Fri, 30 May 2025 12:08:52 CST INF github.com/crazy-max/diun/v4/internal/app/job.go:212 > New image found image=docker.io/pihole/pihole:2023.11.0 provider=file
diun-1  | Fri, 30 May 2025 12:08:52 CST DBG github.com/crazy-max/diun/v4/internal/app/job.go:225 > Manifest saved to database image=docker.io/pihole/pihole:2023.11.0 provider=file
diun-1  | Fri, 30 May 2025 12:08:52 CST INF github.com/crazy-max/diun/v4/internal/app/diun.go:192 > Jobs completed added=1 failed=0 skipped=1 unchanged=0 updated=0
diun-1  | Fri, 30 May 2025 12:08:52 CST INF github.com/crazy-max/diun/v4/internal/app/diun.go:118 > Cron initialized with schedule 0 17 * * 5
diun-1  | Fri, 30 May 2025 12:08:52 CST INF github.com/crazy-max/diun/v4/internal/app/diun.go:122 > Next run in 4 hours 51 minutes (2025-05-30 17:00:20.804267015 +0800 CST)
```

### Additional info

The surprising log from the DEBUG run is here:
```
diun-1  | Fri, 30 May 2025 12:10:49 CST DBG [containers/image] GET https://registry-1.docker.io/v2/pihole/pihole/tags/list
diun-1  | Fri, 30 May 2025 12:10:50 CST DBG 108 tag(s) found in repository. 1 will be analyzed (1 max, 48 not included, 0 excluded). image=docker.io/pihole/pihole:latest
```

It appears to only look at tag `latest`, even though my `include_tags` config is specifying the semver format.

I suspect I'm misunderstanding how the filtering is working, since diun seems to be pulling the tag based on the `name: pihole/pihole` field of my file provider config, which assumes `latest` since I haven't specified a tag. Is this expected behavior? And if so, how can I get diun to alert on new semver tags?
