### ISSUE TITLE
Email notifications not working

### ISSUE THREAD

**Issue by ludipq** [crazy-max/diun#150]
## Behaviour
Added configuration for SMTP as per the documentation. When running diun --test-notif this is the output:

> Sat, 15 Aug 2020 18:40:57 CEST INF Starting Diun version=4.4.0
> Sat, 15 Aug 2020 18:40:57 CEST INF Configuration loaded from file: /etc/diun/diun.yaml
> Sat, 15 Aug 2020 18:40:57 CEST INF Configuration loaded from 5 environment variable(s)
> **Sat, 15 Aug 2020 18:41:07 CEST FTL Cannot initialize Diun error=timeout**

Using the same SMTP settings on [SMTPer](https://www.smtper.net) works fine.

### Steps to reproduce this issue

1. Add email config to diun.yaml
2.  Run `diun --test-notif` in console

### Expected behaviour

I guess a test email will be sent, or a message saying that it's working?

### Actual behaviour
Sat, 15 Aug 2020 18:41:07 CEST FTL Cannot initialize Diun error=timeout

## Configuration

* Diun version : 4.4.0
* Platform (windows/linux) : Linux (Synology NAS)
* System info (type `uname -a`) : Linux 8888cd4520f2 3.10.105 #25426 SMP Wed Jul 8 03:19:33 CST 2020 x86_64 GNU/Linux

> Paste your configuration files here
* diun config file

```
notif:
  mail:
    host: send.one.com
    port: 587
    ssl: false
    insecureSkipVerify: false
    username: xxx
    password: xxx
    from: xxx
    to: xxx
```

* environment variables

![1](https://user-images.githubusercontent.com/32069841/90317593-eada0a80-df2a-11ea-9cc0-ba8bd8f94b01.JPG)

### Logs

```
# paste logs here (set log-level to debug and enable log-caller)
```
Log from where?
