### ISSUE TITLE
Reload config on change

### ISSUE THREAD

**Issue by adhawkins** [crazy-max/diun#16]
### Behaviour

Config file should be reloaded if it changes

#### Steps to reproduce this issue

1. Start container
2. Allow check to run
3. Make config change
4. Expect new config to be picked up on next run

#### Expected behaviour

New config used on next run

#### Actual behaviour

Existing config used

### Configuration

* Diun version : 1.4.1
* Platform (windows/linux) : linux

```yml
db:
  path: /data/diun.db

watch:
  workers: 10
  schedule: "0 0 * * * *"

notif:
  mail:
    enable: true
    host: localmail.gently.org.uk
    port: 25
    ssl: false
    insecure_skip_verify: false
    username:
    password:
    from: diun@gently.org.uk
    to: andy@gently.org.uk

image:
  - name: linuxserver/nginx
  - name: crazymax/diun:latest
  - name: linuxserver/sonarr:preview
  - name: linuxserver/nzbget
  - name: linuxserver/transmission
  - name: linuxserver/unifi-controller
  - name: linuxserver/duplicati:latest
  - name: marginal/get_iplayer
```
