### ISSUE TITLE
Discord Notifications Not Working in Kubernetes

### ISSUE THREAD

**Issue by Pwhitcomb** [crazy-max/diun#190]
## Behaviour
Container will throw Fatal Error - "Failed to decode configuration from environment variables: Failed to decode configuration from environment variables: field not found, node: webhook"
### Steps to reproduce this issue

1.Start Kubernetes deployment from example on website.
2. Add Discord Notification WebhookURL
3. Pod will restart itself

### Expected behaviour

> Pod should restart with Discord Notification enabled and continue normally.

### Actual behaviour

> Fatal Error is generated and Pod refuses to start

## Configuration

* Diun version : 4.6.0
* Platform (windows/linux) : Linux 
* System info (type `uname -a`) : Linux k3s-1 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

> Paste your configuration files here
> * k8s deployment configuration
```
kind: ClusterRoleBinding
metadata:
  name: diun
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: diun
subjects:
  - kind: ServiceAccount
    name: diun
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: diun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diun
  template:
    metadata:
      labels:
        app: diun
      annotations:
        diun.enable: "true"
        diun.watch_repo: "true"
    spec:
      serviceAccountName: diun
      containers:
        - name: diun
          image: crazymax/diun:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "America/Los_Angeles"
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_JSON
              value: "false"
            - name: DIUN_WATCH_WORKERS
              value: "20"
            - name: DIUN_WATCH_SCHEDULE
              value: "0 */6 * * *"
            - name: DIUN_PROVIDERS_KUBERNETES
              value: "true"
            - name: DIUN_NOTIF_DISCORD_WEBHOOK
              value: REDACTED
          volumeMounts:
            - mountPath: "/data"
              name: "data"
      restartPolicy: Always
      volumes:
        # Set up a data directory for diun
        # For production usage, you should consider using PV/PVC instead(or simply using storage like NAS)
        # For more details, please see https://kubernetes.io/docs/concepts/storage/volumes/
        - name: "data"
          hostPath:
            path: "/home/phil/diun"
            type: Directory
```

### Logs

```
  Starting Diun 4.6.0 
  No configuration file found 
  Cannot load configuration  

```
