### ISSUE TITLE
Telegram notification shows weird date/time?

### ISSUE THREAD

**Issue by keppo070** [crazy-max/diun#191]
Docker tag docker.io/crazymax/diun:latest (https://hub.docker.com/r/crazymax/diun) which you subscribed to through docker provider has been newly added on 83869905fc70.

I would suspect some kind of date instead of 83869905fc70

**Comment by crazy-max** [comment]
@keppo070 `83869905fc70` is the hostname. In your case it looks like the container ID. You can change it with `--name mycontainer` for `docker run` command or `container_name: mycontainer` for `docker-compose`.

**Comment by keppo070** [comment]
It is indeed the container ID. I suspected it was a time/date stamp. I use docker-compose and I have given the container a name but the telegram notification uses the container ID. 

I have included my docker-compose file

```
version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Paris"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=10"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_FIRSTCHECKNOTIF=true"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true"
      - "DIUN_NOTIF_TELEGRAM_TOKEN=123:abc"
      - "DIUN_NOTIF_TELEGRAM_CHATIDS=456"
      - "DIUN_WATCH_HEALTHCHECKS_BASEURL=https://hc-ping.com"
      - "DIUN_WATCH_HEALTHCHECKS_UUID=a-b-c-d-e"
    labels:
      - "diun.enable=true"
    restart: unless-stopped
```

docker ps -a
```
b0fd87dedfe0        crazymax/diun:latest      "diun"                   25 hours ago        Up 25 hours                                                                                            diun
```
