### ISSUE TITLE
Docker container reporting wrong timezone

### ISSUE THREAD

**Issue by accountForIssues** [crazy-max/diun#202]
## Behaviour
Diun is working under the assumption that the current timezone is CEST (UTC +2). So, the cron jobs and alerts fire an hour early.

### Steps to reproduce this issue
Run Diun as usual.

### Expected behaviour
Diun detects the correct timezone.

## Configuration

* Diun version : 4.6.1 (docker)
* Platform (windows/linux) : linux 
* System info (type `uname -a`) : Linux 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux

> * docker-compose.yml
```
version: "3.5"

services:
  diun:
    image: crazymax/diun
    container_name: diun
    hostname: diun
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Copenhagen"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_GOTIFY_ENDPOINT=domain.com"
      - "DIUN_NOTIF_GOTIFY_TOKEN=token1234"
      - "DIUN_NOTIF_GOTIFY_PRIORITY=4"
      - "DIUN_NOTIF_GOTIFY_TIMEOUT=30s"

    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
    restart: always
```

### Relevant commands and logs

```
debian@server:~/docker/diun$ date
Fri 30 Oct 2020 01:11:09 PM CET

debian@server:~/docker/diun$ docker exec -it diun date
Fri Oct 30 13:11:46 CET 2020

debian@server:~/docker/diun$ docker logs diun
Fri, 30 Oct 2020 14:11:35 CEST INF Starting Diun version=4.6.1
Fri, 30 Oct 2020 14:11:35 CEST INF Configuration loaded from 10 environment variable(s)
Fri, 30 Oct 2020 14:11:35 CEST INF Cron triggered
Fri, 30 Oct 2020 14:11:35 CEST INF Found 20 image(s) to analyze provider=docker
Fri, 30 Oct 2020 14:11:48 CEST INF Jobs completed added=0 failed=0 unchanged=70 updated=0
Fri, 30 Oct 2020 14:11:48 CEST INF Cron initialized with schedule 0 */6 * * *
Fri, 30 Oct 2020 14:11:48 CEST INF Next run in 3 hours (2020-10-30 18:00:00 +0200 CEST)

```

Am I doing something wrong ?
