### ISSUE TITLE
DIUN cannot find self update

### ISSUE THREAD

**Issue by mribeiro** [crazy-max/diun#205]
## Behaviour

- A new diun version was pushed to tag latest (https://hub.docker.com/r/crazymax/diun) but there's no notification about.
- Also see a 401 in logs. Could it be the issue?

### Steps to reproduce this issue

1. Installed diun:latest from https://hub.docker.com/r/crazymax/diun . Currently running 4.6.1 (installed a couple of days ago)
2. Ran container
3. New version was tagged in latest
4. Diun cron triggered

### Expected behaviour

> A new version should be detected.

### Actual behaviour

> No new version detected (and some 401 UNAUTHORIZED printed in logs)

## Configuration

* Diun version : 4.6.1
* Platform (windows/linux) : linux (docker)
* System info (type `uname -a`) : Linux Mothership 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

> Paste your configuration files here
> * docker-compose.yml (just the diun part)

```
diun:
    image: crazymax/diun:latest
    container_name: diun
    volumes:
      - /home/mothership/docker/containers-data/diun/config:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Lisbon
      - LOG_LEVEL=debug
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true
      - DIUN_NOTIF_TELEGRAM_TOKEN=*****
      - DIUN_NOTIF_TELEGRAM_CHATIDS=*****
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=false"
    restart: always
```

### Logs

(trimmed them a bit showing only the diun related logs and not other containers)

```
Mon, 02 Nov 2020 12:00:00 WEST INF Cron triggered
Mon, 02 Nov 2020 12:00:00 WEST INF Found 8 image(s) to analyze provider=docker
Mon, 02 Nov 2020 12:00:00 WEST DBG [containers/image] Trying to access "docker.io/crazymax/diun:latest"
Mon, 02 Nov 2020 12:00:00 WEST DBG [containers/image] Returning credentials from DockerAuthConfig
Mon, 02 Nov 2020 12:00:00 WEST DBG [containers/image] Using registries.d directory /etc/containers/registries.d for sigstore configuration
Mon, 02 Nov 2020 12:00:00 WEST DBG [containers/image]  No signature storage configuration found for docker.io/crazymax/diun:latest
Mon, 02 Nov 2020 12:00:00 WEST DBG [containers/image] Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io
Mon, 02 Nov 2020 12:00:00 WEST DBG [containers/image] GET https://registry-1.docker.io/v2/
Mon, 02 Nov 2020 12:00:00 WEST DBG [containers/image] Ping https://registry-1.docker.io/v2/ status 401
Mon, 02 Nov 2020 12:00:00 WEST DBG [containers/image] GET https://auth.docker.io/token?scope=repository%3Acrazymax%2Fdiun%3Apull&service=registry.docker.io
Mon, 02 Nov 2020 12:00:01 WEST DBG [containers/image] GET https://registry-1.docker.io/v2/crazymax/diun/manifests/latest
Mon, 02 Nov 2020 12:00:01 WEST DBG [containers/image] Content-Type from manifest GET is "application/vnd.docker.distribution.manifest.list.v2+json"
Mon, 02 Nov 2020 12:00:04 WEST DBG [containers/image] Downloading /v2/crazymax/diun/blobs/sha256:24563f9d4c8b6529ee89b6db3f7b02cfb1f2df98d25464adabd44e7fa842079c
Mon, 02 Nov 2020 12:00:04 WEST DBG [containers/image] GET https://registry-1.docker.io/v2/crazymax/diun/blobs/sha256:24563f9d4c8b6529ee89b6db3f7b02cfb1f2df98d25464adabd44e7fa842079c
Mon, 02 Nov 2020 12:00:05 WEST DBG No changes image=docker.io/crazymax/diun:latest provider=docker
Mon, 02 Nov 2020 12:00:05 WEST INF Jobs completed added=0 failed=0 unchanged=8 updated=0
Mon, 02 Nov 2020 12:00:05 WEST INF Next run in 5 hours (2020-11-02 18:00:00 +0100 WEST)
```
