### ISSUE TITLE
Docker volume not creating any files?

### ISSUE THREAD

**Issue by mouzzampk2014** [crazy-max/diun#216]
Hi, need little help. I am using this compose and I am sure we don't need this volume `./data:/data` because it doesn't create any files inside the container but just an empty folder?
```
  diun:
    image: ghcr.io/crazy-max/diun:latest
    hostname: ${DOCKERHOSTNAME}
    container_name: diun
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true
    labels:
      - diun.enable=true
      - diun.watch_repo=true
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
```
Thank you

**Comment by crazy-max** [comment]
@mouzzampk2014 

> I am using this compose and I am sure we don't need this volume `./data:/data`

We need it to store Bolt database where images manifests are saved (see [db config](https://crazymax.dev/diun/config/db/)). For the Docker image [it defaults to `/data/diun.db`](https://github.com/crazy-max/diun/blob/a1a4c439ff44ea0f619472803c0a4d6b55de9b20/Dockerfile#L36).

Maybe an error occurred when the container is launched and that's why there is no database. Can you show your logs of diun container please?

**Comment by mouzzampk2014** [comment]
Thank you @crazy-max here is the logs https://pastebin.com/PLg6RAnX

And that's my exact docker-compose. Thank you
```
  diun:
    image: ghcr.io/crazy-max/diun:latest
    hostname: ${DOCKERHOSTNAME}
    container_name: diun
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true
      - DIUN_NOTIF_DISCORD_WEBHOOKURL=
    labels:
      - diun.enable=true
      - diun.watch_repo=true
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/diun:/config
      - /var/run/docker.sock:/var/run/docker.sock
```
