### ISSUE TITLE
Cannot get image digest

### ISSUE THREAD

**Issue by zewelor** [crazy-max/diun#221]
### Steps to reproduce this issue

1. run diun with docker provider
2.
3.

### Expected behaviour

> Tell me what should happen

No warn

### Actual behaviour

> Tell me what happens instead

I get following error for all images added to monitor
```
WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: Head \"https://registry-1.docker.io/v2/crazymax/diun/manifests/
latest\": context deadline exceeded" image=docker.io/crazymax/diun:latest provider=docker
```

## Configuration

* Diun version : 4.8.0
* Platform (windows/linux) : linux
* System info (type `uname -a`) : Linux x1 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

> Paste your configuration files here
> * docker-compose.yml
> * k8s deployment configuration
> * environment variables
> * diun config file
> * ...

```
  diun:
    image: crazymax/diun:latest
    container_name: diun
    restart: always
    depends_on:
      - docker-socket-proxy-ro-minimal
    volumes:
      - ${DOCKER_DATA_DIR}/diun:/data
      - /etc/ssl:/etc/ssl:ro
    networks:
      docker-socket-proxy-ro-minimal:
    secrets:
      - dockerhub_username
      - dockerhub_password
    environment:
      <<: *conf
      LOG_LEVEL: info
      LOG_JSON: "false"
      DIUN_WATCH_WORKERS: "20"
      DIUN_WATCH_SCHEDULE: "0 */6 * * *"
      DIUN_PROVIDERS_DOCKER: "true"
      DIUN_PROVIDERS_DOCKER_WATCHSTOPPED: "true"
      DIUN_PROVIDERS_DOCKER_ENDPOINT: "tcp://docker-socket-proxy-ro-minimal:2375"
      DIUN_REGOPTS_DH_NAME: "docker.io"
      DIUN_REGOPTS_DH_SELECTOR: "image"
      DIUN_REGOPTS_DH_USERNAMEFILE: "/var/run/secrets/dockerhub_username"
      DIUN_REGOPTS_DH_PASSWORDFILE: "/var/run/secrets/dockerhub_password"
    labels:
      - "diun.enable=true"
```

### Logs

```
# paste logs here (set log-level to debug and enable log-caller)
```
