### ISSUE TITLE
Not receiving notification about image updates

### ISSUE THREAD

**Issue by mouzzampk2014** [crazy-max/diun#222]
Hi, I am not seeing any errors or any issues but I am also not been notified which images recently received updates. I only get one discord notification about `diun` image update is available but not for other services. Not sure what I am missing. Thank you
```
  diun:
    image: ghcr.io/crazy-max/diun:latest
    hostname: ${DOCKERHOSTNAME}
    container_name: diun
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true
      - DIUN_NOTIF_DISCORD_WEBHOOKURL=https://discord.com/api/webhooks/6905/Hyygx47jKLqx6ZD
    labels:
      - diun.enable=true
      - diun.watch_repo=true
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/diun:/data
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by crazy-max** [comment]
@mouzzampk2014 You have to [enable Diun for each container/service through Docker labels](https://crazymax.dev/diun/providers/docker/#docker-labels) or you can [watchByDefault](https://crazymax.dev/diun/providers/docker/#watchbydefault) with `DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true` env var. Also `- /etc/localtime:/etc/localtime:ro` will do nothing here azs timezone is managed through Diun. Same for `PUID` and `PGID`. These env vars don't exist. I suggest the following compose:

```yaml
  diun:
    image: ghcr.io/crazy-max/diun:latest
    hostname: ${DOCKERHOSTNAME}
    container_name: diun
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_NOTIF_DISCORD_WEBHOOKURL=https://discord.com/api/webhooks/6905/Hyygx47jKLqx6ZD
    restart: unless-stopped
    volumes:
      - ${DOCKERCONFDIR}/diun:/data
      - /var/run/docker.sock:/var/run/docker.sock
```
