### ISSUE TITLE
Kubernetes daemonset sends multiple notifications

### ISSUE THREAD

**Issue by mzac** [crazy-max/diun#233]
## Behavior
It seems that when running diun on kubernetes that if you are running a daemonset (pods running on all nodes) that notifications are sent out for the same image for all nodes.  Example, I have pihole running on 3 nodes in my cluster as a daemonset and I get 3 notifications. Does this also mean that it is talking to dockerhub 3 times and bumping that new rate limit too?

Note: So as not to cause confusion, I am not running diun as a daemonset but as a deployment, pihole is the daemonset.

### Steps to reproduce this issue

1. Setup daemonset on kubernetes
2. Run diun job
3. Receive multiple notifications

### Expected behavior
Only one notification should be sent similar to a deployment with multiple pods running.

### Actual behavior
Multiple notifications are sent

## Configuration

* Diun version : 4.9.0
* Platform (windows/linux) : linux
* System info (type `uname -a`) : 
Linux k3s-pi1 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: diun
  name: diun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diun
  template:
    metadata:
      labels:
        app: diun
      annotations:
        diun.enable: "true"
        diun.watch_repo: "true"
    spec:
      serviceAccountName: diun
      containers:
        - name: diun
          image: crazymax/diun:4.9.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "America/Montreal"
            - name: LOG_LEVEL
              value: "debug"
            - name: LOG_JSON
              value: "false"
            - name: CONFIG
              value: "/data/diun.yml"
            - name: DIUN_PROVIDERS_KUBERNETES
              value: "true"
            - name: DIUN_PROVIDERS_KUBERNETES_WATCHBYDEFAULT
              value: "true"
          volumeMounts:
            - mountPath: "/data"
              name: diun-data
            - name: diun-config
              mountPath: /data/diun.yml
              subPath: diun.yml
      restartPolicy: Always
      volumes:
      - name: diun-data
        nfs:
          server: 192.168.0.6
          path: /volume1/k3s/diun
      - name: diun-config
        configMap:
            name: diun-config
      nodeSelector:
        kubernetes.io/arch: arm
        node-role.kubernetes.io/pi: ""
```
