### ISSUE TITLE
[Question] Issue running a custom script as a notification

### ISSUE THREAD

**Issue by Cellane** [crazy-max/diun#238]
Similar to #215, I’m very sorry but I seem to be unable to configure Diun to trigger a custom script when a new image is discovered in Docker registry. I have configured Diun like so:

`/etc/diun/diun.yaml`:
```yaml
db:
  path: diun.db

watch:
  workers: 5
  schedule: "* * * * *"
  healthchecks:
    uuid: 18db1b68-b6a3-444b-baa7-d10e77c9b2ff

notif:
  script:
    cmd: "sh"
    args:
      -  "/etc/diun/notify.sh"

providers:
  file:
    filename: /etc/diun/config.yml
```

`/etc/diun/config.yml`
```yaml
- name: bitwardenrs/server
  watch_repo: true
  include_tags:
    - ^[0-9]+.*
  exclude_tags:
    - latest.*
    - testing.*
    - multidb.*
    - .*alpine
```

`/etc/diun/notify.sh` (`chmod +x` was run from host system)
```sh
#!/bin/sh

env > /etc/diun/output
apk add curl

if [ "${DIUN_ENTRY_STATUS}" -ne "new" ]; then
    return 0
fi

VERSION=$(echo "${DIUN_ENTRY_IMAGE}" | sed 's/.*://')

curl -X "POST" "https://drone.milanvit.net/api/repos/Cellane/bitwardenrs-websockets/builds?VERSION=${VERSION}" -H "Authorization: super-secret"
```

The content of the `/etc/diun` directory is mounted from the host system, as I’m running Diun in a Docker container (using an official image). If I enter the container manually via `docker container exec -it diun.web.1 sh` and invoke `/etc/diun/nofify.sh`, the script gets executed correctly (and the `output` file generated on third line in the `notify.sh` script appears in host system as a “proof” of execution).

However, no matter how many times I flush Diun’s database (to forget known tags) and restart Diun, it seems that the custom script never executes, as I can see that my Drone CI instance was not pinged by `curl` and neither can I observe the `output` file being generated on the host system.

Please tell me what I’m doing wrong if you’d be so kind 🙇‍♂️

(For the record, I think I have tried any sensible combination of arguments in the `diun.yml` file, incl.: `cmd: "/etc/diun/notify.sh"`, `cmd: "notify.sh", dir:  "/etc/diun"` and `cmd: "/bin/sh" args: ["/etc/diun/notify.sh"]`)

**Comment by crazy-max** [comment]
@Cellane 

Have you tried with:

```yaml
notif:
  script:
    cmd: "sh"
    args:
      - "-c"
      -  "/etc/diun/notify.sh"
```

**Comment by Cellane** [comment]
Wow, lightning-fast response, thank you so much! 🙇‍♂️
I have not tried that until now, but it seems that it’s also not working, unfortunately…

**Comment by Cellane** [comment]
I forgot to mention that Docker logs don’t show any errors, unfortunately…

![obrazek](https://user-images.githubusercontent.com/171604/101871446-e9fa7200-3bc6-11eb-9afa-ee19c0cb9b4d.png)

**Comment by crazy-max** [comment]
@Cellane Ok thanks I will make some tests on my own, keep you in touch.

**Comment by crazy-max** [comment]
@Cellane I've made some tests and I cannot reproduce your issue.

```yaml
# ./diun.yml
watch:
  workers: 5
  firstCheckNotif: true
  schedule: "* * * * *"

notif:
  script:
    cmd: "sh"
    args:
      - "./notif.sh"

providers:
  file:
    filename: ./images.yml
```

```yaml
# ./images.yml
- name: alpine
  platform:
    os: linux
    arch: amd64
- name: docker.io/crazymax/diun:latest
  platform:
    os: linux
    arch: amd64
```

```bash
# ./notif.sh
env|sort
```

### From command line

```shell
$ diun --config diun.yml --log-level debug
Fri, 18 Dec 2020 20:39:42 CET INF Starting Diun version=4.9.0
Fri, 18 Dec 2020 20:39:42 CET INF Configuration loaded from file: /tmp/diun/diun.yml
Fri, 18 Dec 2020 20:39:42 CET DBG No DIUN_* environment variables defined
Fri, 18 Dec 2020 20:39:42 CET DBG {
  "db": {
    "path": "diun.db"
  },
  "watch": {
    "workers": 5,
    "schedule": "0 * * * *",
    "firstCheckNotif": true,
    "compareDigest": true
  },
  "notif": {
    "script": {
      "cmd": "sh",
      "args": [
        "./notif.sh"
      ]
    }
  },
  "providers": {
    "file": {
      "filename": "./images.yml"
    }
  }
}
Fri, 18 Dec 2020 20:39:42 CET DBG 1 notifier(s) created
Fri, 18 Dec 2020 20:39:42 CET DBG 0 entries found in manifest bucket
Fri, 18 Dec 2020 20:39:42 CET DBG Current database version: 1
Fri, 18 Dec 2020 20:39:42 CET INF Database migration v2...
Fri, 18 Dec 2020 20:39:42 CET INF Cron triggered
Fri, 18 Dec 2020 20:39:42 CET INF Found 2 image(s) to analyze provider=file
...
...
Fri, 18 Dec 2020 20:39:46 CET INF New image found image=docker.io/crazymax/diun:latest provider=file
Fri, 18 Dec 2020 20:39:46 CET DBG Manifest saved to database image=docker.io/crazymax/diun:latest provider=file
Fri, 18 Dec 2020 20:39:46 CET DBG Sending script notification... image=docker.io/crazymax/diun:latest
Fri, 18 Dec 2020 20:39:46 CET DBG DIUN_ENTRY_CREATED=2020-11-16 21:49:33.696725064 +0000 UTC
DIUN_ENTRY_DIGEST=sha256:fc3a8904e77e887ccd0061b7c0700806ff32af0f56b5b9545aead75177c79bf8
DIUN_ENTRY_HUBLINK=https://hub.docker.com/r/crazymax/diun
DIUN_ENTRY_IMAGE=docker.io/crazymax/diun:latest
DIUN_ENTRY_MIMETYPE=application/vnd.docker.distribution.manifest.list.v2+json
DIUN_ENTRY_PLATFORM=linux/amd64
DIUN_ENTRY_PROVIDER=file
DIUN_ENTRY_STATUS=new
DIUN_HOSTNAME=[REDACTED]
DIUN_VERSION=4.9.0
...
[REDACTED]
...
Fri, 18 Dec 2020 20:39:46 CET INF New image found image=docker.io/library/alpine:latest provider=file
Fri, 18 Dec 2020 20:39:46 CET DBG Manifest saved to database image=docker.io/library/alpine:latest provider=file
Fri, 18 Dec 2020 20:39:46 CET DBG Sending script notification... image=docker.io/library/alpine:latest
Fri, 18 Dec 2020 20:39:46 CET DBG DIUN_ENTRY_CREATED=2020-12-17 00:19:42.11518025 +0000 UTC
DIUN_ENTRY_DIGEST=sha256:3c7497bf0c7af93428242d6176e8f7905f2201d8fc5861f45be7a346b5f23436
DIUN_ENTRY_HUBLINK=https://hub.docker.com/_/alpine
DIUN_ENTRY_IMAGE=docker.io/library/alpine:latest
DIUN_ENTRY_MIMETYPE=application/vnd.docker.distribution.manifest.list.v2+json
DIUN_ENTRY_PLATFORM=linux/amd64
DIUN_ENTRY_PROVIDER=file
DIUN_ENTRY_STATUS=new
DIUN_HOSTNAME=[REDACTED]
DIUN_VERSION=4.9.0
...
[REDACTED]
...
Fri, 18 Dec 2020 20:39:46 CET INF Jobs completed added=2 failed=0 unchanged=0 updated=0
Fri, 18 Dec 2020 20:39:46 CET INF Cron initialized with schedule 0 * * * *
Fri, 18 Dec 2020 20:39:46 CET INF Next run in 20 minutes (2020-12-18 21:00:00 +0100 CET)
```

### From compose

```yaml
version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    volumes:
      - "./data:/data"
      - "./diun.yml:/diun.yml:ro"
      - "./images.yml:/images.yml:ro"
      - "./notif.sh:/notif.sh:ro"
    environment:
      - "LOG_LEVEL=debug"
    restart: always
```

```shell
$ docker-compose up
diun_1  | Fri, 18 Dec 2020 19:50:31 UTC INF Starting Diun version=4.9.0
diun_1  | Fri, 18 Dec 2020 19:50:31 UTC INF Configuration loaded from file: /diun.yml
diun_1  | Fri, 18 Dec 2020 19:50:31 UTC INF Configuration loaded from 1 environment variable(s)
diun_1  | Fri, 18 Dec 2020 19:50:31 UTC DBG {
diun_1  |   "db": {
diun_1  |     "path": "/data/diun.db"
diun_1  |   },
diun_1  |   "watch": {
diun_1  |     "workers": 5,
diun_1  |     "schedule": "0 * * * *",
diun_1  |     "firstCheckNotif": true,
diun_1  |     "compareDigest": true
diun_1  |   },
diun_1  |   "notif": {
diun_1  |     "script": {
diun_1  |       "cmd": "sh",
diun_1  |       "args": [
diun_1  |         "./notif.sh"
diun_1  |       ]
diun_1  |     }
diun_1  |   },
diun_1  |   "providers": {
diun_1  |     "file": {
diun_1  |       "filename": "./images.yml"
diun_1  |     }
diun_1  |   }
diun_1  | }
diun_1  | Fri, 18 Dec 2020 19:50:31 UTC DBG 1 notifier(s) created
diun_1  | Fri, 18 Dec 2020 19:50:31 UTC DBG 0 entries found in manifest bucket
diun_1  | Fri, 18 Dec 2020 19:50:31 UTC DBG Current database version: 1
diun_1  | Fri, 18 Dec 2020 19:50:31 UTC INF Database migration v2...
diun_1  | Fri, 18 Dec 2020 19:50:31 UTC INF Cron triggered
diun_1  | Fri, 18 Dec 2020 19:50:31 UTC INF Found 2 image(s) to analyze provider=file
...
...
diun_1  | Fri, 18 Dec 2020 19:50:35 UTC INF New image found image=docker.io/library/alpine:latest provider=file
diun_1  | Fri, 18 Dec 2020 19:50:35 UTC DBG Manifest saved to database image=docker.io/library/alpine:latest provider=file
diun_1  | Fri, 18 Dec 2020 19:50:35 UTC DBG Sending script notification... image=docker.io/library/alpine:latest
diun_1  | Fri, 18 Dec 2020 19:50:35 UTC DBG DIUN_DB_PATH=/data/diun.db
diun_1  | DIUN_ENTRY_CREATED=2020-12-17 00:19:42.11518025 +0000 UTC
diun_1  | DIUN_ENTRY_DIGEST=sha256:3c7497bf0c7af93428242d6176e8f7905f2201d8fc5861f45be7a346b5f23436
diun_1  | DIUN_ENTRY_HUBLINK=https://hub.docker.com/_/alpine
diun_1  | DIUN_ENTRY_IMAGE=docker.io/library/alpine:latest
diun_1  | DIUN_ENTRY_MIMETYPE=application/vnd.docker.distribution.manifest.list.v2+json
diun_1  | DIUN_ENTRY_PLATFORM=linux/amd64
diun_1  | DIUN_ENTRY_PROVIDER=file
diun_1  | DIUN_ENTRY_STATUS=new
diun_1  | DIUN_HOSTNAME=3166a971dba4
diun_1  | DIUN_VERSION=4.9.0
diun_1  | HOME=/root
diun_1  | HOSTNAME=3166a971dba4
diun_1  | LOG_LEVEL=debug
diun_1  | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
diun_1  | PWD=/
diun_1  | SHLVL=1
diun_1  | Fri, 18 Dec 2020 19:50:35 UTC INF New image found image=docker.io/crazymax/diun:latest provider=file
diun_1  | Fri, 18 Dec 2020 19:50:35 UTC DBG Manifest saved to database image=docker.io/crazymax/diun:latest provider=file
diun_1  | Fri, 18 Dec 2020 19:50:35 UTC DBG Sending script notification... image=docker.io/crazymax/diun:latest
diun_1  | Fri, 18 Dec 2020 19:50:35 UTC DBG DIUN_DB_PATH=/data/diun.db
diun_1  | DIUN_ENTRY_CREATED=2020-11-16 21:49:33.696725064 +0000 UTC
diun_1  | DIUN_ENTRY_DIGEST=sha256:fc3a8904e77e887ccd0061b7c0700806ff32af0f56b5b9545aead75177c79bf8
diun_1  | DIUN_ENTRY_HUBLINK=https://hub.docker.com/r/crazymax/diun
diun_1  | DIUN_ENTRY_IMAGE=docker.io/crazymax/diun:latest
diun_1  | DIUN_ENTRY_MIMETYPE=application/vnd.docker.distribution.manifest.list.v2+json
diun_1  | DIUN_ENTRY_PLATFORM=linux/amd64
diun_1  | DIUN_ENTRY_PROVIDER=file
diun_1  | DIUN_ENTRY_STATUS=new
diun_1  | DIUN_HOSTNAME=3166a971dba4
diun_1  | DIUN_VERSION=4.9.0
diun_1  | HOME=/root
diun_1  | HOSTNAME=3166a971dba4
diun_1  | LOG_LEVEL=debug
diun_1  | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
diun_1  | PWD=/
diun_1  | SHLVL=1
diun_1  | Fri, 18 Dec 2020 19:50:35 UTC INF Jobs completed added=2 failed=0 unchanged=0 updated=0
diun_1  | Fri, 18 Dec 2020 19:50:35 UTC INF Cron initialized with schedule 0 * * * *
diun_1  | Fri, 18 Dec 2020 19:50:35 UTC INF Next run in 9 minutes (2020-12-18 20:00:00 +0000 UTC)
```

Some hints:
* Check chmod of `notify.sh` (`chmod +x notify.sh`)
* Set log level to debug
* Try `diun --test-notif --log-level debug`
* Set `firstCheckNotif: true` for testing
