### ISSUE TITLE
unable to spin diun:latest on raspberry pi zero W

### ISSUE THREAD

**Issue by hugalafutro** [crazy-max/diun#242]
I run diun without problems on several raspberry's 3 and 4, recently I came into possession of raspberry pi zero W but diun won't run there. Container gets created, seemingly starts but actually doesn't. The only thing in container log is:
```
Attaching to diun
diun exited with code 132
```
`docker-compose.yml`:
```
version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    hostname: bedroom_diun
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/London"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=5"
      - "DIUN_WATCH_SCHEDULE=0 12 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_TELEGRAM_TOKEN=<redacted>"
      - "DIUN_NOTIF_TELEGRAM_CHATIDS=<redacted>"
```
Docker version 20.10.0, build 7287ab3
docker-compose version 1.27.4, build unknown
(same on all raspberrys)

`uname -a` on the rpi0 W
Linux bedroom 5.4.79+ #1373 Mon Nov 23 13:18:15 GMT 2020 armv6l GNU/Linux
