### ISSUE TITLE
Cannot load configuration error="Key: 'Config.Providers.File.Filename' Error:Field validation for 'Filename' failed on the 'file' tag"

### ISSUE THREAD

**Issue by maguilara** [crazy-max/diun#243]
## Behaviour
Fails to load configuration for providers (?) and simply keeps rebooting itself. It's on a docker container
### Steps to reproduce this issue

1. Create both "custom-images.yml" and docker-compose files
2. Launch it using docker-compose -f diun.yml up -d
3. Crash (indefinitely)

### Expected behaviour

Launch correctly, I followed this sort of recipe found the docs: https://crazymax.dev/diun/user-guides/docker-file-providers/

### Actual behaviour
 Crashes.
## Configuration

* Diun version :  4.9.0
* Platform (windows/linux) : Linux (raspberry pi 4 8gb)
* System info (type `uname -a`) : Linux raspberrypi 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux
docker-compose file:

```
version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    network_mode: host
    volumes:
      - "${ROOT_DOCKER}/diun/data:/data"
      - "${ROOT_DOCKER}/diun//custom-images.yml:/custom-images.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=${TZ}"
      - DIUN_DB_PATH=diun.db
      - "LOG_LEVEL=debug"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_PROVIDERS_FILE_FILENAME=/custom-images.yml"
    restart: unless-stopped

```
ROOT_DOCKER and TZ are enviroment variables found in a .env file, replace with appropriate settings on your system.
custom-images.yml file:
```
- name: ghcr.io/linuxserver/radarr
- name: ghcr.io/linuxserver/sonarr
- name: ghcr.io/linuxserver/bazarr
- name: ghcr.io/linuxserver/jackett
- name: ghcr.io/linuxserver/transmission
- name: ghcr.io/linuxserver/jellyfin
- name: docker.io/pihole/pihole
- name: docker.io/organizr/organizr
- name: docker.io/toddrob/searcharr
```
I understand that this way, diun will inspect by default only "latest" tag
Config/enviromental variables are all in the docker-compose file
I added DIUN_DB_PATH simply because it may be needed (?), but even if I add it, it still crashes.

### Logs
```
Creating diun ... done
Attaching to diun
diun    | Wed, 16 Dec 2020 22:50:46 -05 INF Starting Diun version=4.9.0
diun    | Wed, 16 Dec 2020 22:50:46 -05 DBG No configuration file found
diun    | Wed, 16 Dec 2020 22:50:46 -05 INF Configuration loaded from 6 environment variable(s)
diun    | Wed, 16 Dec 2020 22:50:46 -05 FTL Cannot load configuration error="Key: 'Config.Providers.File.Filename' Error:Field validation for 'Filename' failed on the 'file' tag"
```
