### ISSUE TITLE
Kubernetes support?

### ISSUE THREAD

**Issue by mzac** [crazy-max/diun#25]
Have you considered adding Kubernetes as a provider?  Or since a lot of kubernetes installs run on docker would you just point it to all your hosts?

**Comment by crazy-max** [comment]
Looks ok to me, thanks for your input.

**Comment by crazy-max** [comment]
@mzac Kubernetes provider is available through release `4.0.0-beta.3` if you want to try out. Documentation is available [here](https://github.com/crazy-max/diun/blob/v4/doc/providers/kubernetes.md#about).

**Comment by mzac** [comment]
Wow!!! This looks great!  Looking forward to giving it a try!

**Comment by mzac** [comment]
Hmm.. I got it up and running but I'm getting errors.  Something isn't working right

```
Thu, 18 Jun 2020 09:16:53 EDT INF Starting Diun version=4.0.0-beta.3
Thu, 18 Jun 2020 09:16:54 EDT WRN No notifier available
Thu, 18 Jun 2020 09:16:54 EDT INF Cron triggered
Thu, 18 Jun 2020 09:16:54 EDT ERR Cannot list Kubernetes pods error="pods is forbidden: User \"system:serviceaccount:diun:diun\" cannot list resource \"pods\" in API group \"\" at the cluster scope" provider=kubernetes
Thu, 18 Jun 2020 09:16:54 EDT WRN No image found
Thu, 18 Jun 2020 09:16:54 EDT INF Cron initialized with schedule */30 * * * *
Thu, 18 Jun 2020 09:16:54 EDT INF Next run in 13 minutes (2020-06-18 09:30:00 -0400 EDT)
```

**Comment by crazy-max** [comment]
@mzac Looking at your rbac, the service account `system:serviceaccount:diun:diun` is not allowed to list pods in **all** namespaces (default). Try to set `DIUN_PROVIDERS_KUBERNETES_NAMESPACES=diun` env var.

**Comment by mzac** [comment]
Ok I added it and redployed but still getting an error

```
    Environment:
      TZ:                                    America/Montreal
      LOG_LEVEL:                             info
      LOG_JSON:                              false
      DIUN_WATCH_WORKERS:                    20
      DIUN_WATCH_SCHEDULE:                   */30 * * * *
      DIUN_PROVIDERS_KUBERNETES:             true
      DIUN_PROVIDERS_KUBERNETES_NAMESPACES:  diun
```

```
Thu, 18 Jun 2020 13:39:45 EDT INF Starting Diun version=4.0.0-beta.3
Thu, 18 Jun 2020 13:39:46 EDT WRN No notifier available
Thu, 18 Jun 2020 13:39:46 EDT INF Cron triggered
Thu, 18 Jun 2020 13:39:46 EDT ERR Cannot list Kubernetes pods error="pods is forbidden: User \"system:serviceaccount:diun:diun\" cannot list resource \"pods\" in API group \"\" in the namespace \"diun\"" provider=kubernetes
Thu, 18 Jun 2020 13:39:46 EDT WRN No image found
Thu, 18 Jun 2020 13:39:46 EDT INF Cron initialized with schedule */30 * * * *
Thu, 18 Jun 2020 13:39:46 EDT INF Next run in 20 minutes (2020-06-18 14:00:00 -0400 EDT)
```

**Comment by mzac** [comment]
Ah found it!

This is what I had:
```
# --------------------------------------------------------------------------------
# Cluster Role Binding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: diun
  name: diun
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: diun
subjects:
  - kind: ServiceAccount
    name: diun
    namespace: default
```

changed it to:
```
# --------------------------------------------------------------------------------
# Cluster Role Binding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: diun
  name: diun
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: diun
subjects:
  - kind: ServiceAccount
    name: diun
    namespace: diun
```
^^^ the namespace in the subject.

```
Thu, 18 Jun 2020 13:55:41 EDT INF Starting Diun version=4.0.0-beta.3
Thu, 18 Jun 2020 13:55:41 EDT WRN No notifier available
Thu, 18 Jun 2020 13:55:41 EDT INF Cron triggered
Thu, 18 Jun 2020 13:55:41 EDT INF Found 1 image(s) to analyze provider=kubernetes
Thu, 18 Jun 2020 13:55:43 EDT INF New image found image=docker.io/crazymax/diun:4.0.0-beta.3 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:2.1.0 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:latest provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:3.0.0 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:3.0.0-beta.2 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:2.2.0 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:edge provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:3.0.0-beta.1 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:2.4.0 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:3.0.0-beta.3 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:2.6.1 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:nightly provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:2.3.0 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:2.6.0 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:4.0.0-beta.1 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:2.5.0 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:4.0.0-beta.2 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:2.2.1 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:3.0.0-beta.4 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:3.0.0-beta.5 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:1.2.0 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:0.4.1 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:1.3.0 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:0.4.0 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:0.3.1 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:1.0.0 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:1.1.0 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:0.3.2 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:0.5.0 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:1.0.2 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:1.0.1 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:0.3.0 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:0.2.0 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:0.1.1 provider=kubernetes
Thu, 18 Jun 2020 13:55:44 EDT INF New image found image=docker.io/crazymax/diun:2.0.0 provider=kubernetes
Thu, 18 Jun 2020 13:55:45 EDT INF New image found image=docker.io/crazymax/diun:0.1.0 provider=kubernetes
Thu, 18 Jun 2020 13:55:45 EDT INF New image found image=docker.io/crazymax/diun:1.4.1 provider=kubernetes
Thu, 18 Jun 2020 13:55:45 EDT INF New image found image=docker.io/crazymax/diun:1.4.0 provider=kubernetes
Thu, 18 Jun 2020 13:55:45 EDT INF Cron initialized with schedule */30 * * * *
Thu, 18 Jun 2020 13:55:45 EDT INF Next run in 4 minutes (2020-06-18 14:00:00 -0400 EDT)
```

**Comment by crazy-max** [comment]
@mzac Good catch!

**Comment by mzac** [comment]
> @mzac Good catch!

Thx, now I just need to figure out how to make it watch the rest of my containers (all in different name spaces) and send me notifications!

**Comment by crazy-max** [comment]
@mzac Yeah I think you have to create a "wide" serviceAccount in your cluster to allow that.

**Comment by crazy-max** [comment]
@mzac This should work:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: diun
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diun
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: diun
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: diun
subjects:
  - kind: ServiceAccount
    name: diun
    namespace: default
```

See also https://stackoverflow.com/a/55594676/514571
