### ISSUE TITLE
Multiple Docker Providers

### ISSUE THREAD

**Issue by cjr222** [crazy-max/diun#257]
I searched the docs, FAQ and open issues but couldn't find an answer to this. Can you use multiple docker providers, if so what is the yaml format?
I've tried both of the following formats and while it doesn't error out, it only pulls one of the docker hosts images.

```yaml
providers:
  docker:
    endpoint:
  docker:
    endpoint:
```

AND

```yaml
providers:
  docker:
    endpoint:
    endpoint:
```
