### ISSUE TITLE
get notification, but no new image available

### ISSUE THREAD

**Issue by hugalafutro** [crazy-max/diun#261]
Hi, 3rd day in a row I got an notification `Docker tag docker.io/library/mongo:3 (https://hub.docker.com/_/mongo) which you subscribed to through docker provider has been updated on vm-docker_diun.`, however when I go to the vm and try to pull new image there ain't none.

relevant `docker-compose.yml`:
```
version: '2'

services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:3
    container_name: graylog_db
    volumes:
      - ./mongo_data:/data/db
    restart: unless-stopped

  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
    container_name: graylog_es
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1024m
    restart: unless-stopped

  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:4.0
    container_name: graylog
    volumes:
      - ./graylog_data:/usr/share/graylog/data
    environment:
      - GRAYLOG_PASSWORD_SECRET=<redacted>
      # Password hash from: echo -n "Enter Password: " && head -1 </dev/stdin | tr -d '\n' | sha256sum | cut -d" " -f1
      - GRAYLOG_ROOT_PASSWORD_SHA2=<redacted>
      - GRAYLOG_HTTP_EXTERNAL_URI=http://192.168.1.249:9000/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # windows syslog TCP
      - 5044:5044
      # Syslog UDP
      - 5140:5140/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    restart: unless-stopped
```
