### ISSUE TITLE
I only get updates for diun image

### ISSUE THREAD

**Issue by myInstagramAlternative** [crazy-max/diun#267]
### Steps to reproduce this issue

> 1. I don't know, could u please check my configuration? Maybe it is my fault :)
btw. I used boltBrowser CLI to recheck database but there is  only diun

### Expected behaviour

> I should get update notifications for all images that are used by containers?

### Actual behaviour

> I only get update notifications for diun image

## Configuration

* Diun version : 4.11.0
* Platform (windows/linux) : linux
* System info (type `uname -a`) :  5.4.83-v7l+  armv7l

> * docker-compose.yml
```
version: "2.9"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    volumes:
      - "/srv/dev-disk-by-uuid-fa8fb7e0-1928-4476-be7/docker/diun/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Belgrade"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true"
      - "CONFIG=/data/diun.yml"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
    restart: always
```

> * environment variables
```
TZ | Europe/Belgrade
LOG_LEVEL | info
LOG_JSON | false
DIUN_WATCH_WORKERS | 20
DIUN_WATCH_SCHEDULE | 0 */6 * * *
DIUN_PROVIDERS_DOCKER | true
DIUN_PROVIDERS_DOCKER_WATCHSTOPPED | true
CONFIG | /data/diun.yml
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DIUN_DB_PATH | /data/diun.db
```

> * diun config file
```
db:
  path: /data/diun.db

watch:
  workers: 10
  schedule: "0 */6 * * *"
  firstCheckNotif: false

notif:
  pushover:
    token: token
    recipient: recipient

regopts:
  - name: "docker.io"
    selector: image
    username: username
    password: password

providers:
  docker:
    watchStopped: true
```

### Logs
```
Wed, 03 Feb 2021 18:01:31 CET INF Next run in 5 hours (2021-02-04 00:00:00 +0100 CET)


Thu, 04 Feb 2021 00:00:00 CET INF Cron triggered


Thu, 04 Feb 2021 00:00:06 CET INF Found 1 image(s) to analyze provider=docker


Thu, 04 Feb 2021 00:00:14 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=58 updated=0


Thu, 04 Feb 2021 00:00:14 CET INF Next run in 5 hours (2021-02-04 06:00:00 +0100 CET)


Thu, 04 Feb 2021 06:00:01 CET INF Cron triggered


Thu, 04 Feb 2021 06:00:02 CET INF Found 1 image(s) to analyze provider=docker


Thu, 04 Feb 2021 06:00:10 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=58 updated=0


Thu, 04 Feb 2021 06:00:10 CET INF Next run in 5 hours (2021-02-04 12:00:00 +0100 CET)


Thu, 04 Feb 2021 12:00:00 CET INF Cron triggered


Thu, 04 Feb 2021 12:00:00 CET INF Found 1 image(s) to analyze provider=docker


Thu, 04 Feb 2021 12:00:08 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=58 updated=0


Thu, 04 Feb 2021 12:00:08 CET INF Next run in 5 hours (2021-02-04 18:00:00 +0100 CET)


Thu, 04 Feb 2021 18:00:00 CET INF Cron triggered


Thu, 04 Feb 2021 18:00:00 CET INF Found 1 image(s) to analyze provider=docker


Thu, 04 Feb 2021 18:00:18 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=58 updated=0


Thu, 04 Feb 2021 18:00:18 CET INF Next run in 5 hours (2021-02-05 00:00:00 +0100 CET)


Fri, 05 Feb 2021 00:00:01 CET INF Cron triggered


Fri, 05 Feb 2021 00:00:09 CET INF Found 1 image(s) to analyze provider=docker


Fri, 05 Feb 2021 00:00:17 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=58 updated=0


Fri, 05 Feb 2021 00:00:17 CET INF Next run in 5 hours (2021-02-05 06:00:00 +0100 CET)


Fri, 05 Feb 2021 06:00:00 CET INF Cron triggered


Fri, 05 Feb 2021 06:00:02 CET INF Found 1 image(s) to analyze provider=docker


Fri, 05 Feb 2021 06:00:10 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=58 updated=0


Fri, 05 Feb 2021 06:00:10 CET INF Next run in 5 hours (2021-02-05 12:00:00 +0100 CET)


Fri, 05 Feb 2021 12:00:00 CET INF Cron triggered


Fri, 05 Feb 2021 12:00:01 CET INF Found 1 image(s) to analyze provider=docker


Fri, 05 Feb 2021 12:00:09 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=58 updated=0


Fri, 05 Feb 2021 12:00:09 CET INF Next run in 5 hours (2021-02-05 18:00:00 +0100 CET)


Fri, 05 Feb 2021 18:00:00 CET INF Cron triggered


Fri, 05 Feb 2021 18:00:00 CET INF Found 1 image(s) to analyze provider=docker


Fri, 05 Feb 2021 18:00:08 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=58 updated=0


Fri, 05 Feb 2021 18:00:08 CET INF Next run in 5 hours (2021-02-06 00:00:00 +0100 CET)


Sat, 06 Feb 2021 00:00:00 CET INF Cron triggered


Sat, 06 Feb 2021 00:00:03 CET INF Found 1 image(s) to analyze provider=docker


Sat, 06 Feb 2021 00:00:17 CET INF Image update found image=docker.io/crazymax/diun:edge provider=docker


Sat, 06 Feb 2021 00:00:19 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=57 updated=1


Sat, 06 Feb 2021 00:00:19 CET INF Next run in 5 hours (2021-02-06 06:00:00 +0100 CET)


Sat, 06 Feb 2021 06:00:01 CET INF Cron triggered


Sat, 06 Feb 2021 06:00:10 CET INF Found 1 image(s) to analyze provider=docker


Sat, 06 Feb 2021 06:00:18 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=58 updated=0


Sat, 06 Feb 2021 06:00:18 CET INF Next run in 5 hours (2021-02-06 12:00:00 +0100 CET)


Sat, 06 Feb 2021 12:00:00 CET INF Cron triggered


Sat, 06 Feb 2021 12:00:02 CET INF Found 1 image(s) to analyze provider=docker


Sat, 06 Feb 2021 12:00:10 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=57 updated=0


Sat, 06 Feb 2021 12:00:10 CET INF Next run in 5 hours (2021-02-06 18:00:00 +0100 CET)


Sat, 06 Feb 2021 14:51:34 CET WRN Caught signal terminated


Sat, 06 Feb 2021 15:42:23 CET INF Starting Diun version=4.11.0


Sat, 06 Feb 2021 15:42:25 CET INF Configuration loaded from file: /data/diun.yml


Sat, 06 Feb 2021 15:42:25 CET INF Configuration loaded from 5 environment variable(s)


Sat, 06 Feb 2021 15:42:29 CET INF Cron triggered


Sat, 06 Feb 2021 15:42:32 CET INF Found 1 image(s) to analyze provider=docker


Sat, 06 Feb 2021 15:42:46 CET WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: error pinging docker registry registry-1.docker.io: Get \"https://registry-1.docker.io/v2/\": net/http: TLS handshake timeout" image=docker.io/crazymax/diun:latest provider=docker


Sat, 06 Feb 2021 15:42:46 CET ERR Cannot list tags from registry error="error pinging docker registry registry-1.docker.io: Get \"https://registry-1.docker.io/v2/\": net/http: TLS handshake timeout" image=crazymax/diun:latest provider=docker


Sat, 06 Feb 2021 15:42:46 CET INF Jobs completed added=0 failed=1 skipped=0 unchanged=0 updated=0


Sat, 06 Feb 2021 15:42:46 CET INF Cron initialized with schedule 0 */6 * * *


Sat, 06 Feb 2021 15:42:46 CET INF Next run in 2 hours (2021-02-06 18:00:00 +0100 CET)


Sat, 06 Feb 2021 18:00:00 CET INF Cron triggered


Sat, 06 Feb 2021 18:00:00 CET INF Found 1 image(s) to analyze provider=docker


Sat, 06 Feb 2021 18:00:08 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=58 updated=0


Sat, 06 Feb 2021 18:00:08 CET INF Next run in 5 hours (2021-02-07 00:00:00 +0100 CET)


Sun, 07 Feb 2021 00:00:00 CET INF Cron triggered


Sun, 07 Feb 2021 00:00:00 CET INF Found 1 image(s) to analyze provider=docker


Sun, 07 Feb 2021 00:00:08 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=56 updated=0


Sun, 07 Feb 2021 00:00:08 CET INF Next run in 5 hours (2021-02-07 06:00:00 +0100 CET)


Sun, 07 Feb 2021 06:00:00 CET INF Cron triggered


Sun, 07 Feb 2021 06:00:01 CET INF Found 1 image(s) to analyze provider=docker


Sun, 07 Feb 2021 06:00:09 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=56 updated=0


Sun, 07 Feb 2021 06:00:09 CET INF Next run in 5 hours (2021-02-07 12:00:00 +0100 CET)


Sun, 07 Feb 2021 12:00:00 CET INF Cron triggered


Sun, 07 Feb 2021 12:00:00 CET INF Found 1 image(s) to analyze provider=docker


Sun, 07 Feb 2021 12:00:07 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=56 updated=0


Sun, 07 Feb 2021 12:00:07 CET INF Next run in 5 hours (2021-02-07 18:00:00 +0100 CET)
```
