### ISSUE TITLE
does not update containers :-/

### ISSUE THREAD

**Issue by aocana** [crazy-max/diun#279]
Hi, 

I have diun installed under the following settings. Apparently it is working correctly, but I don't really think it doesn't update the containers with new images, I base this on the fact that when I do a manual upgrade it updates the container.

here the compose of diun:

```
version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    volumes:
      - "/user/diun/data:/data"
      - "/user/diun/./diun.yml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Paris"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_PROVIDERS_SWARM=true"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true"      
    restart: always
    
```

here .yml setup:
```

root@SERVER:# more diun.yml 
watch:
  compareDigest: true
  workers: 10
  schedule: "0 */6 * * *"
  firstCheckNotif: false

  healthchecks:
    baseURL: https://hc-ping.com/
    uuid: eb095278-f28d-4332d-87fb-7b7232371a6SDaa

regopts:
  - name: "docker.io"
    selector: image
    username:  PRIVATE_INFO
    password:  PRIVATE_INFO

providers:
  docker:
    watchByDefault: true
    watchStopped: true
  swarm:
    watchByDefault: true

notif:
  telegram:
    token: PRIVATE_INFO
    chatIDs:
      -  PRIVATE_INFO
      -
```

I receive these messages, but the image of the container remains with the old one:

`Docker tag docker.io/CONTAINER_N/CONTAINER_N:latest (https://hub.docker.com/r/CONTAINER_N/CONTAINER_N) which you subscribed to through docker provider has been updated on 7efb4bb9a65e.
`

Any idea why it doesn't update me, maybe I have some wrong value ?
