### ISSUE TITLE
High Memory Usage?

### ISSUE THREAD

**Issue by agrider** [crazy-max/diun#293]
## Behaviour
I'm new to Diun, so this may just be user error, or even just misaligned expectations, but it seems like my Diun instance is using an inordinate amount of memory for the task it is performing. I have configured Diun as below with the intention of having Diun monitor containers which I have pinned to specific versions and do not want auto-updated but do want to know when new versions are pushed to their respective repos, and have it monitoring roughly 35 containers/repos right now. 

I started up the container last night and went to bed, when I got up this morning and checked my Grafana monitoring I noted that the container steadily grew in memory usage all the way up to 3 GB (which is my default container mem_limit) and though it has gone back down slightly, has leveled out at 1.83 GB steady state. Watchtower, which I was using previously alone, by contrast regularly sits at around 20 MB of usage steady state, and I've never seen it go above 50 MB. 

Is anyone able to help me understand what I am doing wrong or why it should be using this much memory? 
### Steps to reproduce this issue

1. Deploy Diun with the following compose and env (sanitized)
```yaml
  diun: 
    << : *defaultsWithNetwork
    image: crazymax/diun
    container_name: diun
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./diun/data:/data
    environment:
      - *timezone
    env_file: ./diun/diun.env
    labels:
      com.centurylinklabs.watchtower.enable: "true"

x-service-defaults-with-network: 
  &defaultsWithNetwork
  restart: unless-stopped
  mem_limit: 3g
  cpus: "2.0"
  cpu_shares: 1024
  networks: &network
    - generalbridge
````

````
LOG_LEVEL=info
LOG_JSON=false
DIUN_WATCH_WORKERS=20
DIUN_WATCH_SCHEDULE=2 0,5,12,17 * * *
DIUN_PROVIDERS_DOCKER=true
DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true
DIUN_NOTIF_GOTIFY_ENDPOINT=https://sanitized.somedomain.com
DIUN_NOTIF_GOTIFY_TOKEN=sanitized.validtokenhere
DIUN_NOTIF_GOTIFY_PRIORITY=1
DIUN_NOTIF_GOTIFY_TIMEOUT=15s
````

2. Configure containers with the following labels.
```yaml
    diun.enable: "true"
    diun.watch_repo: "true"
````

### Expected behaviour

I expected monitoring memory usage to be quite low, certainly below 250 MB, since the similar service watchtower idles at about 30 MB.

### Actual behaviour

See screenshot of Grafana, usage climbs over about 6 hours and then, after hitting mem_limit, comes back down to idle at about 1.83 GB.

![Diun_Grafana](https://user-images.githubusercontent.com/1875171/110245673-d773a880-7f29-11eb-95fa-63ff069742b2.png)

## Configuration

* Diun version : 
* Platform (windows/linux) : Linux via Docker on latest tag
* System info (type `uname -a`) : 

> Paste your configuration files here
> * docker-compose.yml
> * k8s deployment configuration
> * environment variables
> * diun config file
> * ...

### Logs

```
# paste logs here (set log-level to debug and enable log-caller)
```
