### ISSUE TITLE
Notification for unupdated image

### ISSUE THREAD

**Issue by hugalafutro** [crazy-max/diun#299]
## Behaviour
Getting notification for updated image of `docker.io/library/mongo:3` but when I go to update the container no new image to pull is available.

### Steps to reproduce this issue

1. Have Diun
2. Have docker.io/library/mongo:3 container
3. ???

### Expected behaviour

No notification for un-updated container

### Actual behaviour

Getting notification for image that is not updated.

## Configuration

* Diun version : 4.13.0
* Platform (windows/linux) : linux
* System info (type `uname -a`) : Linux vm-docker 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

relevant docker-compose:
```
version: '2'

services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:3
    container_name: graylog_db
    volumes:
      - ./mongo_data:/data/db
    restart: unless-stopped

  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
    container_name: graylog_es
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2048m
    restart: unless-stopped

  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:4.0
    container_name: graylog
    volumes:
      - ./graylog_data:/usr/share/graylog/data
    environment:
      - GRAYLOG_PASSWORD_SECRET=somethingsomethingredacted
      # Password hash from: echo -n "Enter Password: " && head -1 </dev/stdin | tr -d '\n' | sha256sum | cut -d" " -f1
      - GRAYLOG_ROOT_PASSWORD_SHA2=somethingsomethingredacted
      - GRAYLOG_HTTP_EXTERNAL_URI=http://192.168.1.249:9000/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # windows syslog TCP
      - 5044:5044
      # Syslog UDP
      - 5140:5140/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    restart: unless-stopped

```
### Logs

```
diun    | Wed, 10 Mar 2021 15:30:52 UTC INF Starting Diun version=4.13.0
diun    | Wed, 10 Mar 2021 15:30:52 UTC INF Configuration loaded from 8 environment variable(s)
diun    | Wed, 10 Mar 2021 15:30:52 UTC INF Cron triggered
diun    | Wed, 10 Mar 2021 15:30:54 UTC INF Found 15 image(s) to analyze provider=docker
diun    | Wed, 10 Mar 2021 15:30:57 UTC INF Jobs completed added=0 failed=0 skipped=0 unchanged=15 updated=0
diun    | Wed, 10 Mar 2021 15:30:57 UTC INF Cron initialized with schedule 0 12 * * *
diun    | Wed, 10 Mar 2021 15:30:57 UTC INF Next run in 20 hours (2021-03-11 12:00:00 +0000 GMT)
diun    | Thu, 11 Mar 2021 12:00:00 UTC INF Cron triggered
diun    | Thu, 11 Mar 2021 12:00:00 UTC INF Found 15 image(s) to analyze provider=docker
diun    | Thu, 11 Mar 2021 12:00:04 UTC INF New image found image=docker.io/linuxserver/sonarr:latest provider=docker
diun    | Thu, 11 Mar 2021 12:00:04 UTC INF Image update found image=docker.io/linuxserver/jackett:latest provider=docker
diun    | Thu, 11 Mar 2021 12:00:04 UTC INF Image update found image=docker.io/library/mongo:3 provider=docker
diun    | Thu, 11 Mar 2021 12:00:04 UTC INF Jobs completed added=1 failed=0 skipped=0 unchanged=12 updated=2
diun    | Thu, 11 Mar 2021 12:00:04 UTC INF Next run in 23 hours (2021-03-12 12:00:00 +0000 GMT)
```

I know they're not debug logs, but this happens like once a month only and I always forget about enabling the debug logs. Let me know if you need those and I'll enable them and wait another month or so.
