### ISSUE TITLE
Line break character on gotify secret

### ISSUE THREAD

**Issue by dcasado** [crazy-max/diun#300]
## Behaviour

Secret created for gotify notifications have a line break character. I used secrets in more services and this has never happened. I also tried to create the secret from another system and the same appened.

When I go inside the container and do a cat of the secret, it doesn't show this character and there is a new line but I get the same behaviour with secrets from other services.

### Steps to reproduce this issue

1. Create a secret with gotify token
2. Wait until diun sends notification
3. Token fails to authenticate

### Expected behaviour

Token should be equal to the one entered when the secret was created. Without the `%0A` character

### Actual behaviour

The token that is sent to gotify has an extra line break character at the end. Traefik and gotify logs show `/message?token=...MP%0A`

## Configuration

* Diun version : 4.13.0
* Platform (windows/linux) : linux
* System info (type `uname -a`) : Linux node1-raspi4-2g 5.4.0-1029-raspi #32-Ubuntu SMP PREEMPT Thu Feb 4 23:00:55 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

docker-compose.yaml

``` yaml

secrets:
  diun_gotify_token:
    external: true

services:
  app:
    image: crazymax/diun:4.13.0
    environment:
      - TZ=Europe/Madrid
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 0 3 ? * *
      - DIUN_PROVIDERS_SWARM=true
      - DIUN_PROVIDERS_SWARM_WATCHBYDEFAULT=true
      - DIUN_NOTIF_GOTIFY_ENDPOINT=https://gotify
      - DIUN_NOTIF_GOTIFY_TOKENFILE=/run/secrets/diun_gotify_token
      - DIUN_NOTIF_GOTIFY_PRIORITY=1
      - DIUN_NOTIF_GOTIFY_TIMEOUT=10s
    secrets:
      - source: diun_gotify_token
        target: /run/secrets/diun_gotify_token
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "diun.watch_repo=true"
        - "diun.include_tags=^[0-9]+.*"
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
```

Secret from diun

```
/ # cat /run/secrets/diun_gotify_token
...MP
/ #
```
Secret from other service

```
/ # cat /run/secrets/other_secret
...34
/ #
```

#### Diun logs
```
diun_app.1.bg5r9bi0cyc9@node1-raspi4-2g    | Wed, 10 Mar 2021 18:22:15 CET INF New image found image=docker.io/b4bz/homer:21.03.2 provider=swarm
diun_app.1.bg5r9bi0cyc9@node1-raspi4-2g    | Wed, 10 Mar 2021 18:22:15 CET ERR Gotify notification failed error="401 Unauthorized: you need to provide a valid access token or user credentials to access this api" image=docker.io/b4bz/homer:21.03.2
```
#### Traefik logs
```
"POST /message?token=...MP%0A HTTP/2.0" 401 141 "-" "-" 1586 "gotify_https@docker" "http://10.0.0.2:8085" 3ms
```

I will set the logs to debug and update the issue with the new details.
