### ISSUE TITLE
FEATURE REQUEST: Use diun.enable=false for WatchByDefault[true

### ISSUE THREAD

**Issue by derekoharrow** [crazy-max/diun#306]
At present, you can set DIUN to either watch all containers by default, or to ignore all containers by default and only monitor those where diun.enable=true is set (i.e. watch all, or only watch specific containers).

It would be great to have the opposite also possible - watch all containers by default, but exclude and where diun.enable is set to false (i.e. watch by default, but allow exclusions).

This could be done by having DIUN check for diun.enable=false when using watch by default, and excluding those from the checks.

Thanks

**Comment by crazy-max** [comment]
@derekoharrow `diun.enable=false` should already work.

**Comment by derekoharrow** [comment]
> @derekoharrow `diun.enable=false` should already work.

Hmmm. Doesn't seem to be for me.

Here's my DIUN config (in docker compose):

```
  diun:
    container_name: diun
    image: crazymax/diun:latest
    volumes:
      - "/data/appdata/docker/diun:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/London"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=5"
      - "DIUN_WATCH_SCHEDULE=0 0 */6 ? * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "diun.enable=true"
      - "DIUN_NOTIF_PUSHOVER_TOKEN=XXXXXXXXXXXXXXX"
      - "DIUN_NOTIF_PUSHOVER_RECIPIENT=XXXXXXXXXXXXXX"
      - "DIUN_NOTIF_MQTT_HOST=mqtt.lan"
      - "DIUN_NOTIF_MQTT_TOPIC=docker/diun"
      - "DIUN_NOTIF_MQTT_CLIENT=diun"
      - "DIUN_NOTIF_MQTT_SCHEME=mqtt"
      - "DIUN_NOTIF_MQTT_PORT=1883"
    restart: unless-stopped
```

Here's an extract of the docker compose for a container I don't want notifications for:

```
  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal
    environment: 
      - AUTOHEAL_CONTAINER_LABEL=all
      - PUID=${PUID}
      - PGID=${PGID}
      - "diun.enable=false"
    volumes:
      - /etc/hosts:/etc/hosts:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
```

As you can see, I've specified **diun.enable=false**, but I still get notifications from diun about this container (and others) every day.
