### ISSUE TITLE
Cannot get remote manifest error="Cannot get image digest from HEAD request

### ISSUE THREAD

**Issue by steakhutzeee** [crazy-max/diun#310]
### Expected behaviour

Images should be checked.

### Actual behaviour

Sometimes i got this errors in the logs for most of my images, some checks go well, some not:

`WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: Head \"https://ghcr.io/v2/linuxserver/mariadb/manifests/latest\": dial tcp: lookup ghcr.io on 127.0.0.11:53: read udp 127.0.0.1:33756->127.0.0.11:53: i/o timeout" 
`
## Configuration

* Diun version : 4.14.0
* Platform (windows/linux) : Linux
* System info (type `uname -a`) : Linux DK 4.14.222-odroidxu4 #1 SMP PREEMPT Mon Mar 8 07:50:47 UTC 2021 armv7l GNU/Linux

> Paste your configuration files here

```
version: "3.5"
services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    environment:
      - TZ=Europe/Rome
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_NOTIF_MAIL_HOST=smtp.gmail.com
      - DIUN_NOTIF_MAIL_PORT=465
      - DIUN_NOTIF_MAIL_SSL=true
      - DIUN_NOTIF_MAIL_LOCALNAME=localhost
      - DIUN_NOTIF_MAIL_USERNAME=hidden
      - DIUN_NOTIF_MAIL_PASSWORD=hidden
      - DIUN_NOTIF_MAIL_FROM=hidden
      - DIUN_NOTIF_MAIL_TO=hidden
    volumes:
      - /srv/dev-disk-by-label-HC2/AppData/Diun/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
networks:
    default:
      external:
        name: my-net
```

### Logs

```
today at 00:00  Mon, 29 Mar 2021 00:00:18 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: Head \"https://ghcr.io/v2/linuxserver/pwndrop/manifests/latest\": dial tcp: lookup ghcr.io on 127.0.0.11:53: read udp 127.0.0.1:33756->127.0.0.11:53: i/o timeout" image=ghcr.io/linuxserver/pwndrop:latest provider=docker
today at 00:00  Mon, 29 Mar 2021 00:00:18 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: Head \"https://ghcr.io/v2/linuxserver/papermerge/manifests/latest\": dial tcp: lookup ghcr.io on 127.0.0.11:53: read udp 127.0.0.1:33756->127.0.0.11:53: i/o timeout" image=ghcr.io/linuxserver/papermerge:latest provider=docker
today at 00:00  Mon, 29 Mar 2021 00:00:18 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: Head \"https://ghcr.io/v2/linuxserver/mariadb/manifests/latest\": dial tcp: lookup ghcr.io on 127.0.0.11:53: read udp 127.0.0.1:33756->127.0.0.11:53: i/o timeout" image=ghcr.io/linuxserver/mariadb:latest provider=docker
today at 00:00  Mon, 29 Mar 2021 00:00:18 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: Head \"https://ghcr.io/v2/linuxserver/duplicati/manifests/latest\": dial tcp: lookup ghcr.io on 127.0.0.11:53: read udp 127.0.0.1:33756->127.0.0.11:53: i/o timeout" image=ghcr.io/linuxserver/duplicati:latest provider=docker
today at 00:00  Mon, 29 Mar 2021 00:00:18 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: Head \"https://ghcr.io/v2/linuxserver/librespeed/manifests/latest\": dial tcp: lookup ghcr.io on 127.0.0.11:53: read udp 127.0.0.1:33756->127.0.0.11:53: i/o timeout" image=ghcr.io/linuxserver/librespeed:latest provider=docker
today at 00:00  Mon, 29 Mar 2021 00:00:18 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: Head \"https://ghcr.io/v2/linuxserver/wireguard/manifests/latest\": dial tcp: lookup ghcr.io on 127.0.0.11:53: read udp 127.0.0.1:33756->127.0.0.11:53: i/o timeout" image=ghcr.io/linuxserver/wireguard:latest provider=docker
today at 00:00  Mon, 29 Mar 2021 00:00:18 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: Head \"https://ghcr.io/v2/linuxserver/mariadb/manifests/latest\": dial tcp: lookup ghcr.io on 127.0.0.11:53: read udp 127.0.0.1:33756->127.0.0.11:53: i/o timeout" image=ghcr.io/linuxserver/mariadb:latest provider=docker
today at 00:00  Mon, 29 Mar 2021 00:00:18 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: Head \"https://ghcr.io/v2/linuxserver/qbittorrent/manifests/latest\": dial tcp: lookup ghcr.io on 127.0.0.11:53: read udp 127.0.0.1:33756->127.0.0.11:53: i/o timeout" image=ghcr.io/linuxserver/qbittorrent:latest provider=docker
today at 00:00  Mon, 29 Mar 2021 00:00:18 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: Head \"https://ghcr.io/v2/linuxserver/bookstack/manifests/latest\": dial tcp: lookup ghcr.io on 127.0.0.11:53: read udp 127.0.0.1:33756->127.0.0.11:53: i/o timeout" image=ghcr.io/linuxserver/bookstack:latest provider=docker
today at 00:00  Mon, 29 Mar 2021 00:00:18 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: Head \"https://ghcr.io/v2/linuxserver/heimdall/manifests/latest\": dial tcp: lookup ghcr.io on 127.0.0.11:53: read udp 127.0.0.1:33756->127.0.0.11:53: i/o timeout" image=ghcr.io/linuxserver/heimdall:latest provider=docker
today at 00:00  Mon, 29 Mar 2021 00:00:18 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: Head \"https://ghcr.io/v2/linuxserver/snapdrop/manifests/latest\": dial tcp: lookup ghcr.io on 127.0.0.11:53: read udp 127.0.0.1:33756->127.0.0.11:53: i/o timeout" image=ghcr.io/linuxserver/snapdrop:latest provider=docker
today at 00:00  Mon, 29 Mar 2021 00:00:22 CEST INF Image update found image=docker.io/amir20/dozzle:latest provider=docker
today at 00:00  Mon, 29 Mar 2021 00:00:23 CEST INF Jobs completed added=0 failed=11 skipped=0 unchanged=5 updated=1
today at 00:00  Mon, 29 Mar 2021 00:00:23 CEST INF Next run in 5 hours (2021-03-29 06:00:00 +0200 CEST)
```
