### ISSUE TITLE
No Discord notifications are being sent other than test-notif

### ISSUE THREAD

**Issue by DerRockWolf** [crazy-max/diun#313]
### Steps to reproduce this issue

1. Startup the container with my `docker-compose.yml`
2. Wait
3. See issue

### Expected behaviour

> I should receive a notification about new image version

### Actual behaviour

> I don't receive notification abount any new image version

## Configuration

* Diun version : 4.14.0
* Platform (windows/linux) : linux
* System info (type `uname -a`) : `Linux hostname 5.4.0-1032-raspi #35-Ubuntu SMP PREEMPT Fri Mar 19 20:52:40 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`

docker-compose.yml:
```
version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Berlin"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=10"
      - "DIUN_WATCH_SCHEDULE=*/5 * * * *" # changed to test
      - "DIUN_NOTIF_DISCORD_WEBHOOKURL=REMOVED"
      - "DIUN_NOTIF_DISCORD_MENTIONS=<@REMOVED_ID>"
      - "DIUN_NOTIF_DISCORD_TIMEOUT=10s"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
    restart: always
```

### Logs

[diun_logs.txt](https://github.com/crazy-max/diun/files/6222726/diun_logs.txt)

### Additional Information:
* I'm receiving notifications if I run `docker-compose exec diun diun --test-notif`
* I'm not sure if this issue is specific to the Discord notif
* In the meantime I'll try to configure different notifs
