### ISSUE TITLE
Profiler volume enforced even when unused or path changed

### ISSUE THREAD

**Issue by TheSpad** [crazy-max/diun#343]
## Behaviour

Profiler volume is defined in the [Dockerfile](https://github.com/crazy-max/diun/blob/master/Dockerfile#L45) which means that even if it's not used, or the path is changed to something other than /profiler, docker creates a volume for that path.

### Steps to reproduce this issue

1. Start diun without a host mount for /profiler, or change the path using `PROFILER_PATH`
2. Inspect the mounted volumes: `docker inspect -f '{{ json .Mounts }}' diun | python3 -m json.tool`
3. See docker-created volume for /profiler

### Expected behaviour

`/profiler` should not be a hard-coded volume as it needlessly dumps data onto the host filesystem and will end up with multiple volumes over time as the container is recreated.

### Actual behaviour

`/profiler` is a hard-coded volume in the Dockerfile

## Configuration

* Diun version : v4.15.2
* Platform (windows/linux) : Linux
* System info (type `uname -a`) : Linux docker2 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

compose
```yaml
services:
  diun:
    image: ghcr.io/crazy-max/diun:latest
    container_name: diun
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Europe/London
      - LOG_LEVEL=info
      - DIUN_NOTIF_TELEGRAM_TOKEN=${TGRAMAPI}
      - DIUN_NOTIF_TELEGRAM_CHATIDS=${TGRAMCHAT}
      - DIUN_NOTIF_DISCORD_WEBHOOKURL=${DISCORDURL}
      - DIUN_NOTIF_DISCORD_MENTIONS=${DISCORDMENTIONS}
      - DIUN_DB_PATH=diun.db
      - DIUN_WATCH_WORKERS=10
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true
      - DIUN_REGOPTS_0_NAME=docker.io
      - DIUN_REGOPTS_0_SELECTOR=image
      - DIUN_REGOPTS_0_USERNAME=${DOCKERIO_USERNAME}
      - DIUN_REGOPTS_0_PASSWORD=${DOCKERIO_PASSWORD}
    restart: always
    labels:
      - diun.enable=true
```

$ docker inspect -f '{{ json .Mounts }}' diun | python3 -m json.tool 
```json
[
    {
        "Type": "bind",
        "Source": "/var/run/docker.sock",
        "Destination": "/var/run/docker.sock",
        "Mode": "ro",
        "RW": false,
        "Propagation": "rprivate"
    },
    {
        "Type": "volume",
        "Name": "diun_data",
        "Source": "/var/lib/docker/volumes/diun_data/_data",
        "Destination": "/data",
        "Driver": "local",
        "Mode": "rw",
        "RW": true,
        "Propagation": ""
    },
    {
        "Type": "volume",
        "Name": "f78931bc15f99855e6aa33d5bc7effada7d06cc94f2538f28b54ae5585590015",
        "Source": "/var/lib/docker/volumes/f78931bc15f99855e6aa33d5bc7effada7d06cc94f2538f28b54ae5585590015/_data",
        "Destination": "/profiler",
        "Driver": "local",
        "Mode": "",
        "RW": true,
        "Propagation": ""
    }
]
```
