### ISSUE TITLE
Error "No such image" for some images on Swarm

### ISSUE THREAD

**Issue by sadmin91** [crazy-max/diun#350]
## Behaviour
I have installed Diun on my Docker Swarm cluster.
With the last version (4.15.2), when Diun analyze start (on container startup or on schedule), error "No such image" appears for some images on my Swarm services (no error with image on my file provider).

### Steps to reproduce this issue

1.Deploy Diun on Swarm cluster

### Expected behaviour

No error should appears

### Actual behaviour

Error during Diun analyze.

## Configuration

* Diun version : 4.15.2
* Platform (windows/linux) : Linux (raspberry)
* System info (type `uname -a`) : Linux xxx 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l GNU/Linux
* Docker Service Definition
```docker
docker service create \
--name diun \
--hostname diun \
--network my-network \
--constraint node.role==manager \
--env "TZ=Europe/Paris" \
--env "CONFIG=/diun.yml" \
--env "LOG_LEVEL=info" \
--env "LOG_JSON=false" \
--mount "type=bind,source=/swarmData/diun/data,destination=/data,readonly=false" \
--mount "type=bind,source=/swarmData/diun/diun.yml,destination=/diun.yml,readonly=true" \
--mount "type=bind,source=/swarmData/diun/fileProvider.yml,destination=/fileProvider.yml,readonly=true" \
--mount "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock,readonly=true" \
--label diun.enable=true \
crazymax/diun
```
* Diun Config File:
```
db:
  path: diun.db

watch:
  workers: 5
  schedule: "0 0 * * *"
  firstCheckNotif: false

notif:
  mail:
    host: xxx
    port: xxx
    ssl: true
    insecureSkipVerify: false
    username: xxx
    password: xxx
    from: xxx
    to: xxx

providers:
  swarm:
    apiVersion: "1.39"
    watchByDefault: false
  file:
    filename: /fileProvider.yml
```
* Diun File Provider:
```
- name: phpmyadmin
- name: nodered/node-red
- name: linuxserver/smokeping
- name: homeassistant/raspberrypi4-homeassistant:stable
- name: openzwave/ozwdaemon
- name: kunde21/gitea-arm
  platform:
    os: linux
    arch: arm64
- name: mariadb
  platform:
    os: linux
    arch: arm64
    variant: v8
- name: tobi312/php:7.4-fpm-nginx-alpine-arm
- name: crazymax/firefox-syncserver
  watch_repo: true
- name: jenkins/jenkins:lts
```

### Logs

See debug log content:
```
Thu, 29 Apr 2021 13:43:43 CEST INF Starting Diun version=4.15.2
Thu, 29 Apr 2021 13:43:43 CEST INF Configuration loaded from file: /diun.yml
Thu, 29 Apr 2021 13:43:43 CEST INF Configuration loaded from 1 environment variable(s)
Thu, 29 Apr 2021 13:43:43 CEST DBG {
  "db": {
    "path": "/data/diun.db"
  },
  "watch": {
    "workers": 5,
    "schedule": "0 0 * * *",
    "firstCheckNotif": false,
    "compareDigest": true
  },
  "notif": {
    "mail": {
      "host": "xxx",
      "port": xxx,
      "ssl": true,
      "insecureSkipVerify": false,
      "localName": "localhost",
      "username": "xxx",
      "password": "xxx",
      "from": "xxx",
      "to": "xxx"
    }
  },
  "providers": {
    "swarm": {
      "apiVersion": "1.39",
      "tlsVerify": true,
      "watchByDefault": false
    },
    "file": {
      "filename": "/fileProvider.yml"
    }
  }
}
Thu, 29 Apr 2021 13:43:43 CEST DBG 1 notifier(s) created
Thu, 29 Apr 2021 13:43:43 CEST DBG 20 entries found in manifest bucket
Thu, 29 Apr 2021 13:43:43 CEST DBG Current database version: 2
Thu, 29 Apr 2021 13:43:43 CEST INF Cron triggered
Thu, 29 Apr 2021 13:43:43 CEST ERR Cannot inspect image error="Error: No such image: willfarrell/autoheal:latest@sha256:c4f83d20651d427a86d31c4584338a7d59528a61e54b9461874717333a11b4b3" ctn_image=willfarrell/autoheal:latest@sha256:c4f83d20651d427a86d31c4584338a7d59528a61e54b9461874717333a11b4b3 provider=swarm svc_name=autoheal
Thu, 29 Apr 2021 13:43:43 CEST ERR Cannot inspect image error="Error: No such image: bitwardenrs/server:latest@sha256:29a6be94a187198eef4a4bbe3bbd0ca1568c0cc9d460721e63f213a731de9f06" ctn_image=bitwardenrs/server:latest@sha256:29a6be94a187198eef4a4bbe3bbd0ca1568c0cc9d460721e63f213a731de9f06 provider=swarm svc_name=bitwarden
```
