### ISSUE TITLE
Diun creates diun.db directory

### ISSUE THREAD

**Issue by snakuzzo** [crazy-max/diun#358]
## Behaviour

Container terminated after few seconds.
profiler creates a `/data/data.db/` directory and later it try to open db `/data/diun.db`

### Steps to reproduce this issue

1. Just create the container with my config

### Expected behaviour

> Tell me what should happen

### Actual behaviour

> Tell me what happens instead

## Configuration

* Diun version : 
* Platform (windows/linux) : linux
* System info (type `uname -a`) : Linux TS-251D 4.14.24-qnap

```
services:

  diun:
    image: crazymax/diun:latest
    container_name: diun
    environment:
      - "TZ=Europe/Rome"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_SCHEDULE=0/20 * * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=false"
      - "DIUN_NOTIF_MQTT_HOST=${HOST_IP}"
      - "DIUN_NOTIF_MQTT_PORT=${MOSQUITTO_PORT}"
      - "DIUN_NOTIF_MQTT_USERNAME=${MOSQUITTO_USER}"
      - "DIUN_NOTIF_MQTT_PASSWORD=${MOSQUITTO_PASSWORD}"
      - "DIUN_NOTIF_MQTT_CLIENT=diun"
      - "DIUN_NOTIF_MQTT_TOPIC=diun-watcher"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_SLACK_WEBHOOKURL=https://hooks.slack.com/services/xxxxxxxxxxxxxxxxxxxxxxx"
      - "PROFILER=mem"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "diun.enable=true"
      - "diun.include.tags=latest"
    restart: always
```

### Logs

```
[user1@TS-251D diun-compose]$ docker-compose up diun  
Recreating diun ... done
Attaching to diun
diun              | Sun, 02 May 2021 22:49:16 CEST INF Starting Diun version=4.15.0
diun              | Sun, 02 May 2021 22:49:16 CEST INF Configuration loaded from 12 environment variable(s)
diun              | 2021/05/02 22:49:16 profile: memory profiling enabled (rate 4096), /data/diun.db/mem.pprof
diun              | Sun, 02 May 2021 22:49:16 CEST FTL Cannot initialize Diun error="open /data/diun.db: is a directory"
diun exited with code 1
```
