### ISSUE TITLE
Notification message not clear enough

### ISSUE THREAD

**Issue by zilexa** [crazy-max/diun#417]
## Behaviour
Running diun monthly, I get emails per image that has been updated. 2 questions:
1) It says the image has been updated on [name of my server]. I suppose it means diun has downloaded a newer version for me. If I would recreate the container (manually), it would use the newer image, correct?
2) I can't find the reported digest. For example, diun ran this morning:
_Diun 🔔 notificationDocker tag docker.io/hotio/scrutiny:latest which you subscribed to through docker provider has been updated on Obelix.This image has been updated at Jun 17, 2021 17:39:15 UTC with digest sha256:65f27219f9c5cf40860cd9ed2669b161136a08edac0c25c8eb78557aad245279 for linux/amd64 platform._ 

When I check docker.io/hotio/scrutiny:latest
https://hub.docker.com/r/hotio/scrutiny/tags?page=1&ordering=last_updated
I cannot find sha256:65f27219f9c5cf40860cd9ed2669b161136a08edac0c25c8eb78557aad245279 for linux/amd64 anywhere.

### Steps to reproduce this issue
1. Simply run it after you have a container (for example scrutiny) up and running.

### Expected behaviour
The correct digest for Scrutiny latest amd64: :sha256:b2d3cee51281ab37f3da89cbf7008e67633dea510f3132a8fcb6bff086a99e38

### Actual behaviour
A digest I cannot find anywhere: sha256:65f27219f9c5cf40860cd9ed2669b161136a08edac0c25c8eb78557aad245279 for linux/amd64

## Configuration

* Diun version : 4.15.2
* Platform: Ubuntu Budgie 21.04
* System info: `Linux Obelix 5.11.0-22-generic #23-Ubuntu SMP Thu Jun 17 00:34:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

diun.yml:
```
notif:
  mail:
    host: mail.smtp2go.com
    port: 587
    ssl: false
    insecureSkipVerify: true
    username: 
    password: 
    from: 
    to: 

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watchByDefault: true
    watchStopped: true
```

snippet of my docker-compose.yml (using v2.3):
```
##____________________ Scrutiny [Management/monitoring]
  scrutiny:
    container_name: scrutiny
    image: hotio/scrutiny
    restart: always
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    devices:
      - "/dev/nvme0n1"
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
      - "/dev/sdd"
      - "/dev/sde" 
    networks: 
      - management
    #entrypoint: CMD
    environment:
      mode: web
      PUID: $PUID
      PGID: $PGID
      UMASK: 002
      TZ: $TZ
      API_ENDPOINT: http://scrutiny-web:8080
    volumes:
      - /run/udev:/run/udev:ro
      - $DOCKERDIR/scrutiny/config:/config
    ports:
      - "8001:8080"
```
