### ISSUE TITLE
raise  excpetion "no locks available"

### ISSUE THREAD

**Issue by hsz1273327** [crazy-max/diun#435]
## Behaviour

Init error when using diun in swarm. 

## Configuration

* Diun version :  4.19.0,4.18.0 4.16.1
* Platform (windows/linux) : arm64/linux(raspberry pi with 64 bit ubuntu  20.04 TLS)

> Paste your configuration files here
> * docker-compose.yml

```yaml
version: "3.8"

services:
  swarm-cronjob:
    image: crazymax/swarm-cronjob:1.9.0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      TZ: Asia/Shanghai
      LOG_LEVEL: info
      LOG_JSON: "true"
    deploy:
      labels:
        - "diun.enable=true"
        - "diun.watch_repo=true"
      placement:
        constraints:
          - node.role == manager
  diun:
    image: crazymax/diun:4.19.0
    command: serve
    volumes:
      - "diun-data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      TZ: Asia/Shanghai
      LOG_LEVEL: info
      LOG_JSON: "true"
      DIUN_WATCH_WORKERS: 20
      DIUN_WATCH_SCHEDULE: 0 */6 * * *
      DIUN_PROVIDERS_SWARM: "true"
      DIUN_PROVIDERS_SWARM_TLSVERIFY: "false"
      DIUN_NOTIF_MAIL_HOST: smtp.exmail.qq.com
      DIUN_NOTIF_MAIL_PORT: 587
      DIUN_NOTIF_MAIL_SSL: "true"
      DIUN_NOTIF_MAIL_LOCALNAME: xxx
      DIUN_NOTIF_MAIL_USERNAME: xxxxxxxxxxxxx
      DIUN_NOTIF_MAIL_PASSWORD: xxxxxxxxxxxxxxxxxxxxxx
      DIUN_NOTIF_MAIL_FROM: ops@xxxxxxxxxxxxxx
      DIUN_NOTIF_MAIL_TO: xxxxxxxxxxxxx
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "diun.enable=true"
        - "diun.watch_repo=true"
      placement:
        constraints:
          - node.role == manager
    

volumes:
  diun-data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.31.212,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/volume2/docker_share/diun/data"
```

`diun-data` is a nfsv3 volume and the `duin.db` can be created in it.

### Logs

```
{"level":"info","version":"4.19.0","time":"2021-07-16T14:32:52+08:00","message":"Starting Diun"}
{"level":"info","time":"2021-07-16T14:32:52+08:00","message":"Configuration loaded from 13 environment variable(s)"}
{"level":"fatal","error":"no locks available","time":"2021-07-16T14:32:59+08:00","message":"Cannot initialize Diun"}
```
