### ISSUE TITLE
4.20.1 crashes on startup with `Failed to decode configuration from environment variables`

### ISSUE THREAD

**Issue by aptalca** [crazy-max/diun#484]
## Behaviour
`4.20.1` (and `4.20.0`) crashes on start with the following error:
```
Tue, 07 Sep 2021 12:19:56 EDT INF Starting Diun version=4.20.0
Tue, 07 Sep 2021 12:19:56 EDT DBG No configuration file found
Tue, 07 Sep 2021 12:19:56 EDT FTL Cannot load configuration error="Failed to decode configuration from environment variables: Failed to decode configuration from environment variables: field not found, node: templatetitle"
```

### Steps to reproduce this issue

Updated an existing container with the following compose yaml:
```
  diun:
    image: ghcr.io/crazy-max/diun:4.20.1
    container_name: diun
    hostname: registry
    command: serve
    volumes:
      - "/home/aptalca/appdata/diun:/data"
    environment:
      - "TZ=America/New_York"
      - "LOG_LEVEL=debug"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=10"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_PROVIDERS_DOCKER_ENDPOINT=tcp://dockerproxy:2375"
      - "DIUN_NOTIF_DISCORD_WEBHOOKURL=https://discord.com/api/webhooks/********redacted*****************"
      - "DIUN_NOTIF_DISCORD_TEMPLATETITLE={{ if (eq .Entry.Status \"new\") }}New image {{ .Entry.Image }} has been added{{ else }}Image update for {{ .Entry.Image }}{{ end }}"
      - "DIUN_NOTIF_DISCORD_TEMPLATEBODY=Docker tag {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }} which you subscribed to through {{ .Entry.Provider }} provider has been {{ if (eq .Entry.Status \"new\") }}newly added{{ else }}updated{{ end }} on {{ .Meta.Hostname }}."
      - "DIUN_NOTIF_DISCORD_MENTIONS=@everyone"
    restart: unless-stopped
```

### Expected behaviour

It should start without errors

### Actual behaviour

Crashes on start and gets into a crash/restart loop.
Pinning to tag `4.19.0` makes it work fine again. `4.20.0` also exhibits the above mentioned issue.

## Configuration

* Diun version : `4.20.1`
* Platform (windows/linux) : Ubuntu focal
* System info (type `uname -a`) : `Linux ***redacted*** 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

### Logs

```
Tue, 07 Sep 2021 12:19:56 EDT INF Starting Diun version=4.20.0
Tue, 07 Sep 2021 12:19:56 EDT DBG No configuration file found
Tue, 07 Sep 2021 12:19:56 EDT FTL Cannot load configuration error="Failed to decode configuration from environment variables: Failed to decode configuration from environment variables: field not found, node: templatetitle"
```
