### ISSUE TITLE
Option to set `watch_repo` globally

### ISSUE THREAD

**Issue by markhaehnel** [crazy-max/diun#491]
Is there a way to set `watch_repo` and the corresponding options like `max_tags`, `include_tags` and `exclude_tags` globally or per provider?

The use case for this would be that I want to check all running images (which have precise tags) for new tags, not just updated images.

If not, can you give me info where and how one could implement this in diun and if it would be a beginner friendly pull request?
I would be happy to contribute.

**Comment by crazy-max** [comment]
We can add a `watch.override` opt:

```yaml
watch:
  override:
    watch_repo: true
    notify_on: update
    max_tags: 100
    include_tags:
      - ...
    exclude_tags:
      - ...
```
