### ISSUE TITLE
Docker & Swarm provider on HTTP registry.

### ISSUE THREAD

**Issue by martadinata666** [crazy-max/diun#493]
### Steps to reproduce this issue

1. Deploy image from http registry.
2. Check diun log
3. `Tue, 28 Sep 2021 14:26:16 WIB WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: pinging container registry 192.168.0.2:5050: Get \"https://192.168.0.2:5050/v2/\": http: server gave HTTP response to HTTPS client"`

### Expected behaviour

> Show image added or update available

### Actual behaviour

> Throw HTTP error due request from HTTPS client.

## Configuration

* Diun version : 4.20.1
* Docker
* System info (type `uname -a`) : `Linux homelab 5.4.0-84-generic #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

* Diun config file
```
db:
  path: diun-standalone.db

watch:
  workers: 5
  schedule: "0 */3 * * *"
  firstCheckNotif: true

notif:
  discord:
    webhookURL: someurl
    mentions:
      - "@here"
    timeout: 20s

regopts:
  - name: "someinscurename"
    timeout: 30s
    insecureTLS: true
  - name: "somename"
    selector: image
    username: someuser
    password: sometoken

providers:
  docker:
    watchStopped: true
    watchByDefault: true
    tlsVerify: false
  #swarm:
  #  watchByDefault: false
  file:
    filename: /etc/diun/image.yml

```

### Logs

```
`Tue, 28 Sep 2021 14:26:16 WIB WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: pinging container registry 192.168.0.2:5050: Get \"https://192.168.0.2:5050/v2/\": http: server gave HTTP response to HTTPS client"`
```

Is this intended? I can manually add image through `file` provider and additional regopts option. There is also `tlsVerify: false` for docker and swarm  but doesn't seems making provider fetch manifest via HTTP.
