### ISSUE TITLE
Pushover secrets don't appear to be working

### ISSUE THREAD

**Issue by mpfl** [crazy-max/diun#516]
### Steps to reproduce this issue

1. Create  `/home/diun/secrets/pushover_token` and `/home/diun/secrets/pushover_recipient` containing the correct values from Pushover
2. Verify files have correct permissions
```
root@thyme:/home/diun/secrets# ls -al
total 16
drwxr-xr-x 2 diun diun 4096 Dec  8 06:27 .
drwxr-xr-x 4 diun diun 4096 Dec  8 06:26 ..
-rw-r--r-- 1 diun diun   31 Dec  8 06:27 pushover_recipient
-rw-r--r-- 1 diun diun   31 Dec  8 06:27 pushover_token
```
3. Use docker-compose below to set Diun up - making sure secrets are defined in all the right places and the appropriate environmental variables are set
4. Run sh in container and verify the secrets have loaded properly with `cat /run/secrets/pushover_token` and `cat /run/secrets/pushover_recipient`
5. While still using sh in container, test notifications with `diun notif test`

### Expected behaviour

I expect to receive a test Pushover notification.

### Actual behaviour

I  get an error:

```
diun: error: rpc error: code = Unknown desc = pushover: invalid API token
```

## Configuration

* Diun version : docker latest (4.20.1)
* Platform (windows/linux) : Ubuntu 20.04
* System info (type `uname -a`) : `Linux thyme 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

```yaml
version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    user: 1006:1007
    secrets:
     - pushover_token
     - pushover_recipient
    command: serve
    volumes:
      - "/home/diun/data:/data"
    environment:
      - "TZ=Antarctica/McMurdo"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_ENDPOINT=tcp://diun-docker-socket-proxy:2375"
      - "DIUN_NOTIF_PUSHOVER_TOKENFILE=/run/secrets/pushover_token"
      - "DIUN_NOTIF_PUSHOVER_RECIPIENTFILE=/run/secrets/pushover_recipient"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
    restart: always

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: diun-docker-socket-proxy
    privileged: true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - IMAGES=1
    restart: unless-stopped
    labels:
      - "diun.enable=true"

secrets:
  pushover_token:
    file: /home/diun/secrets/pushover_token
  pushover_recipient:
    file: /home/diun/secrets/pushover_recipient
```

### Logs

```
Wed, 08 Dec 2021 06:34:35 AWST INF Starting Diun version=4.20.1,
Wed, 08 Dec 2021 06:34:35 AWST INF Configuration loaded from 7 environment variable(s),
Wed, 08 Dec 2021 06:34:35 AWST INF Cron triggered,
Wed, 08 Dec 2021 06:34:35 AWST INF Found 18 image(s) to analyze provider=docker,
Wed, 08 Dec 2021 06:34:55 AWST INF Jobs completed added=0 failed=0 skipped=0 unchanged=87 updated=0,
Wed, 08 Dec 2021 06:34:55 AWST INF Cron initialized with schedule 0 */6 * * *,
Wed, 08 Dec 2021 06:34:55 AWST INF Next run in 5 hours 25 minutes (2021-12-08 12:00:00 +0800 AWST),
Wed, 08 Dec 2021 12:00:00 AWST INF Cron triggered,
Wed, 08 Dec 2021 12:00:00 AWST INF Found 18 image(s) to analyze provider=docker,
Wed, 08 Dec 2021 12:00:34 AWST INF Image update found image=docker.io/netdata/netdata:latest provider=docker,
Wed, 08 Dec 2021 12:00:34 AWST ERR Pushover notification failed error="pushover: invalid API token" image=docker.io/netdata/netdata:latest,
Wed, 08 Dec 2021 12:00:34 AWST INF Jobs completed added=0 failed=0 skipped=0 unchanged=86 updated=1,
Wed, 08 Dec 2021 12:00:34 AWST INF Next run in 5 hours 59 minutes (2021-12-08 18:00:00 +0800 AWST)
```
