### ISSUE TITLE
Pushover Notification Customization of sound and priority 

### ISSUE THREAD

**Issue by michaelkrieger** [crazy-max/diun#522]
## Behaviour
Pushover always sends with the default sounds but in many cases this can be delivered silently or with a different priority.

### Steps to reproduce this issue
N/A

### Expected behaviour
The [API](https://pushover.net/api) calls for:

**priority** - send as -2 to generate no notification/alert, -1 to always send as a quiet notification, 1 to display as high-priority and bypass the user's quiet hours, or 2 to also require confirmation from the user

**sound** - the name of one of the sounds supported by device clients to override the user's default sound choice (string)

These should be customizable through configuration or the pushover environment variables.

### Actual behaviour
These are not customizable and it will always play the default sound and priority

## Configuration
* Diun version : 4.20.1
* Platform (windows/linux) : linux
* System info (type `uname -a`) : Debian 11

**Comment by wsc96** [comment]
This would be great.

**Comment by bb3454** [comment]
+1

**Comment by tushev** [comment]
@crazy-max in https://github.com/crazy-max/diun/blob/5d583809a05f29fcccb2634d3c1d98e6ca75c2ff/internal/notif/pushover/client.go#L66 and https://github.com/crazy-max/diun/blob/5d583809a05f29fcccb2634d3c1d98e6ca75c2ff/internal/model/notif_pushover.go#L9 there's already a `Priority`.

Is it somehow possible to set that value in docker-compose?

**Comment by fanaticDavid** [comment]
Priority definitely works, even if it's not documented. I'm using the configuration file `diun.yml`:
```
notif:
  pushover:
    token: [REDACTED]
    recipient: [REDACTED]
    priority: -2
    templateTitle: "{{ .Entry.Image }} released"
    templateBody: |
      Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released.
```
