### ISSUE TITLE
Check if newer semver image tags

### ISSUE THREAD

**Issue by ismarslomic** [crazy-max/diun#556]
Thanks for making our lifes easier with such a nice tool!

I have tried solving my use case with Diun, but Im not sure if I'm doing it wrong, or if it is not supporting my need exactly.

Im using exact image tag versions (semver) in my containers and want to get notified when new (semver) version (compared eith current) is released on Docker Hub. Currently Im checking Docker Hub manually, which is boring! 

I tried with `diun.watch_repo=true` and `diun.include_tags` with version regex, but then I get all versions matching the regex and not only the newer ones. 

Could you please guide me in right direction?

**Comment by crazy-max** [comment]
> I tried with `diun.watch_repo=true` and `diun.include_tags` with version regex, but then I get all versions matching the regex and not only the newer ones.

That's the right way to do it but maybe there is something wrong with your regex or configuration. Please create a proper [bug report](https://github.com/crazy-max/diun/issues/new?assignees=&labels=&template=bug_report.md). Thanks.

**Comment by ismarslomic** [comment]
## Behaviour
I would like Diun to send me Slack notification when there are newer (semver) tag available compared with currently deployed.

To test this I have started Grafana Docker image with version tag 8.4.2, while there are one newer tag 8.4.3. I expected to get notification from Diun that there are one new tag available in Docker Hub. But in stead I got 10 notification for earlier tags as well.

### Steps to reproduce this issue

1. Start Diun docker container
2. Start Grafana docker container
3. Check the channel in Slack where notifications are sent and verify that newer (semver) tag has been notified

### Expected behaviour

Diun should send 1 Slack notification that there are 1 new tag (tag `8.4.3`) released for Grafana Docker Image

### Actual behaviour

Diun sent 10 Slack notification with 10 new tags for Grafana Docker image

## Configuration

* Diun version : 4.21.0
* Platform (windows/linux) : Linux
* System info (type `uname -a`) :  Linux smartnuc 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* diun docker-compose.yml
  ```
  version: "3.8"
  services:
    diun:
      image: crazymax/diun:4.21.0
      container_name: diun
      command: serve
      volumes:
        - "./data:/data"
        - "./config/diun.yml:/diun.yml:ro"
        - "/var/run/docker.sock:/var/run/docker.sock"
      environment:
        - "TZ=Europe/Oslo"
        - "LOG_LEVEL=info"
        - "LOG_JSON=false"
      restart: unless-stopped
  ```

 * diun config file
    ```
    watch:
      workers: 20
      firstCheckNotif: true
      schedule: "0 */1 * * *"
    
    providers:
      docker:
        endpoint: "unix:///var/run/docker.sock"
        watchByDefault: false
        watchStopped: false
    
    notif:
      slack:
        webhookURL: https://hooks.slack.com/services/<hidden>
        renderFields: true
        templateBody: |
          Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released.
    ```

 * grafana docker-compose.yml
    ```
    version: '3.8'
    services:
      grafana:
        container_name: grafana_test
        image: grafana/grafana:8.4.2
        ports:
          - "3005:3000"
        restart: unless-stopped
        labels:
          diun.enable: "true"
          diun.watch_repo: "true"
          diun.include_tags: "^\\d+\\.\\d+.\\d+$$"
          diun.notify_on: "new"
          diun.max_tags: "10"
    ```

### Logs

```
Wed, 16 Mar 2022 14:40:25 CET INF Starting Diun version=4.21.0

Wed, 16 Mar 2022 14:40:25 CET INF Configuration loaded from file: /diun.yml

Wed, 16 Mar 2022 14:40:25 CET INF Configuration loaded from 1 environment variable(s)

Wed, 16 Mar 2022 14:40:25 CET INF Database migration v2...

Wed, 16 Mar 2022 14:40:25 CET INF Cron triggered

Wed, 16 Mar 2022 14:40:25 CET INF Found 1 image(s) to analyze provider=docker

Wed, 16 Mar 2022 14:40:29 CET INF New image found image=docker.io/grafana/grafana:8.4.2 provider=docker

Wed, 16 Mar 2022 14:40:30 CET INF New image found image=docker.io/grafana/grafana:8.4.1 provider=docker

Wed, 16 Mar 2022 14:40:30 CET INF New image found image=docker.io/grafana/grafana:8.3.7 provider=docker

Wed, 16 Mar 2022 14:40:30 CET INF New image found image=docker.io/grafana/grafana:8.4.3 provider=docker

Wed, 16 Mar 2022 14:40:30 CET INF New image found image=docker.io/grafana/grafana:8.3.5 provider=docker

Wed, 16 Mar 2022 14:40:30 CET INF New image found image=docker.io/grafana/grafana:8.3.3 provider=docker

Wed, 16 Mar 2022 14:40:30 CET INF New image found image=docker.io/grafana/grafana:8.3.4 provider=docker

Wed, 16 Mar 2022 14:40:30 CET INF New image found image=docker.io/grafana/grafana:8.3.6 provider=docker

Wed, 16 Mar 2022 14:40:30 CET INF New image found image=docker.io/grafana/grafana:8.3.2 provider=docker

Wed, 16 Mar 2022 14:40:31 CET INF New image found image=docker.io/grafana/grafana:8.4.0 provider=docker

Wed, 16 Mar 2022 14:40:31 CET INF Jobs completed added=10 failed=0 skipped=0 unchanged=0 updated=0

Wed, 16 Mar 2022 14:40:31 CET INF Cron initialized with schedule 0 */1 * * *

Wed, 16 Mar 2022 14:40:31 CET INF Next run in 19 minutes 28 seconds (2022-03-16 15:00:00 +0100 CET)
```
