### ISSUE TITLE
Notification matrix missing access token

### ISSUE THREAD

**Issue by unknownFalleN** [crazy-max/diun#564]
### Steps to reproduce this issue

1. docker-compose up --force-recreate --build

### Expected behaviour

> Notifications in matrix room

### Actual behaviour

> See error messages below. Multiply Errors with `Too Many Requests` after `Missing access token`

## Configuration

* Diun version : 4.21.0
* Platform (windows/linux) : Linux
* System info (type `uname -a`) : `Linux v2202111159193166736 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux`

> Paste your configuration files here
> * docker-compose.yml
```
version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Berlin"
      - "DIUN_WATCH_COMPAREDIGEST=true"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_FIRSTCHECKNOTIF=true"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=*/5 * * * *" # for testing */5 
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true" 
      - "DIUN_NOTIF_MATRIX_HOMESERVERURL=https://matrix.org"
      - "DIUN_NOTIF_MATRIX_USERFILE=./data/userfile.txt"
      - "DIUN_NOTIF_MATRIX_PASSWORDFILE=./data/userpass.txt"
      - "DIUN_NOTIF_MATRIX_ROOMID=!XXXX:matrix.org"
      - "DIUN_NOTIF_MATRIX_MSGTYPE=notice"
    labels:
      - "diun.enable=true"
    restart: unless-stopped
```
create username and password with printf "XXX" > file.txt

### Logs

```
diun    | Thu, 24 Feb 2022 16:45:27 CET INF Starting Diun version=4.21.0
diun    | Thu, 24 Feb 2022 16:45:27 CET INF Configuration loaded from 12 environment variable(s)
diun    | Thu, 24 Feb 2022 16:45:27 CET INF Database migration v2...
diun    | Thu, 24 Feb 2022 16:45:27 CET INF Cron triggered
....
diun    | Thu, 24 Feb 2022 16:45:30 CET INF New image found image=docker.io/mailcow/clamd:1.43 provider=docker
diun    | Thu, 24 Feb 2022 16:45:30 CET INF New image found image=docker.io/mailcow/sogo:1.106 provider=docker
diun    | Thu, 24 Feb 2022 16:45:30 CET INF New image found image=docker.io/mailcow/postfix:1.66 provider=docker
diun    | Thu, 24 Feb 2022 16:45:30 CET ERR Cannot logout error="contents=[XXX] msg=Failed to POST JSON to /_matrix/client/r0/logout code=401 wrapped=M_MISSING_TOKEN: Missing access token"
diun    | Thu, 24 Feb 2022 16:45:30 CET ERR Matrix notification failed error="failed to authenticate Matrix user: contents=[XXX] msg=Failed to POST JSON to /_matrix/client/r0/login code=429 wrapped=M_LIMIT_EXCEEDED: Too Many Requests" image=docker.io/mailcow/clamd:1.43
```
