### ISSUE TITLE
`ntfy.sh` notifier

### ISSUE THREAD

**Issue by muety** [crazy-max/diun#569]
I'd appreciate https://ntfy.sh as an additional notifier, very similar to Gotify.

**Comment by crazy-max** [comment]
Sgtm, PR welcome thx!

**Comment by Joeharrison94** [comment]
This ^^ PLEASE!!!!! this would be amazing to see implemented,

**Comment by mabed-fr** [comment]
Oh yes is my prefered services because is self hosted !

**Comment by binwiederhier** [comment]
I randomly found this issue googling ntfy. I'm the maintainer of ntfy and I'd love to be integrated too :smile: :heart:

**Comment by sbhal** [comment]
I tried using Webhooks integration to make it work with ntfy, but unsuccessful.

**Comment by raphpa** [comment]
I used a script notifier for now:

diun.sh
```
#!/bin/ash

ntfy_url="https://<username>:<password>@ntfy.host.com/<topic>"
ntfy_prio="default"
ntfy_emoji="package"
ntfy_title="Image update detected on Host"
ntfy_message="New image is available for $DIUN_ENTRY_IMAGE"

wget -q -O - --header "Tags: $ntfy_emoji" --header "Priority: $ntfy_prio" --header "Title: $ntfy_title" --post-data "$ntfy_message" $ntfy_url

exit 0
```


docker-compose.yml
```
services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    restart: unless-stopped
    command: serve

    volumes:
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './diun.sh:/diun.sh:ro'

    environment:
      - 'TZ=Europe/Paris'
      - 'LOG_LEVEL=info'
      - 'LOG_JSON=false'
      - 'DIUN_WATCH_WORKERS=20'
      - 'DIUN_WATCH_SCHEDULE=0 */6 * * *'
      - 'DIUN_PROVIDERS_DOCKER=true'
      - 'DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true'
      - 'DIUN_NOTIF_SCRIPT_CMD=sh'
      - 'DIUN_NOTIF_SCRIPT_ARGS=-c,/diun.sh'
```
