### ISSUE TITLE
Trying to use Pushover notification results in error code

### ISSUE THREAD

**Issue by jauderho** [crazy-max/diun#577]
### Steps to reproduce this issue

1. trying to use this compose file with pushover 

```
services:
  diun:
    image: crazymax/diun:latest
    network_mode: "bridge"
    volumes:
      - "./data:/data"
      #- "./diun.yml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=America/Los_Angeles"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_PUSHOVER_RECIPIENT=user"
      - "DIUN_NOTIF_PUSHOVER_TOKEN=password"
    restart: always
    dns_search: .
```

2. do `docker compose run diun notif test`
3. get following error 

`diun: error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:42286: connect: connection refused"`

### Expected behaviour

> Test notification should be sent

### Actual behaviour

> This error message

`diun: error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:42286: connect: connection refused"`

## Configuration

* Diun version : v4.21.0
* Platform (windows/linux) : linux
* System info (type `uname -a`) : `5.13.0-35-generic #40-Ubuntu SMP Mon Mar 7 08:03:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

> Paste your configuration files here
> * docker-compose.yml
> * k8s deployment configuration
> * environment variables
> * diun config file
> * ...

### Logs

```
# paste logs here (set log-level to debug and enable log-caller)
```
