### ISSUE TITLE
Override Image domain/path

### ISSUE THREAD

**Issue by owais-maswala** [crazy-max/diun#586]
I would like to be able to override the domain/path that is used to look up the latest version of an image.

Use Case: Using container images that have been mirrored from upstream providers to private registries. 

For example:

- Public Image: docker.io/nginx:1.21.1
- Private Registry Mirrored image: gcr.io/xxxxxx/nginx:1.21.1

If my container is running the private registry image, I would like to check for new image updates against the docker.io/nginx registry as opposed to the private registry.

**Comment by chrisblech** [comment]
This enhancement would be helpful, even for a different use case:

In my docker-compose file, I need to pin the explicitely semver-named image tag (i.e. `mariadb:10.11.5` - to avoid uncontrolled upgrades), but diun should watch the more general tag (i.e. `mariadb:lts`) and notify me when this tag changes. This occurs every time the `lts` tag moves on, when a new LTS version was published.

This use case can be solved, when it would be able to override the image path via docker label, maybe like this:

```yml
version: "3.5"
services:
  db:
    image: mariadb:10.11.5
    labels:
      - "diun.enable=true"
      - "diun.overrideImagePath=mariadb:lts"
```

**Comment by gjrtimmer** [comment]
I would like this feature

**Comment by major-mayer** [comment]
I would also really like to see this feature.
It would also help in situation where the Dockerfile used to build a service is hosted in a Git repository:

```
 app:
    container_name: custom-nextcloud-container
    build: 
      context: https://github.com/test/test-repo.git
``` 

To my knowledge, there is no way to tell Diun, which image should be watched for updates in this case (e.g. nextcloud:fpm).
