### ISSUE TITLE
Cannot get image digest from HEAD request

### ISSUE THREAD

**Issue by gregeeh** [crazy-max/diun#587]
Hi,

Have just installed version 4.21.0 in a Container on my QNAP NAS.

```
Tue, 29 Mar 2022 13:07:57 AEDT INF Starting Diun version=4.21.0
Tue, 29 Mar 2022 13:07:57 AEDT INF Configuration loaded from file: /root/.config/diun.yml
Tue, 29 Mar 2022 13:07:57 AEDT INF Configuration loaded from 4 environment variable(s)
Tue, 29 Mar 2022 13:07:58 AEDT INF Cron triggered
Tue, 29 Mar 2022 13:07:59 AEDT INF Found 2 image(s) to analyze provider=docker
Tue, 29 Mar 2022 13:08:02 AEDT WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: reading digest latest in docker.io/lscr.io/linuxserver/heimdall: errors:\ndenied: requested access to the resource is denied\nerror parsing HTTP 401 response body: unexpected end of JSON input: \"\"\n" image=docker.io/lscr.io/linuxserver/heimdall:latest provider=docker
Tue, 29 Mar 2022 13:08:03 AEDT INF Jobs completed added=0 failed=1 skipped=0 unchanged=1 updated=0
Tue, 29 Mar 2022 13:08:03 AEDT INF Cron initialized with schedule 0 */1 * * *
Tue, 29 Mar 2022 13:08:03 AEDT INF Next run in 51 minutes 56 seconds (2022-03-29 14:00:00 +1100 AEDT)
```

 diun.yml

```
[notif:
  mail:
    host: mxserver.com.au
    port: 465
    ssl: true
    insecureSkipVerify: false
    from: diun@example.net.au
    to:
      - greg@example.net.au
    username: greg@example.net.au
    password: mypassword
    templateTitle: "{{ .Entry.Image }} released"
    templateBody: |
      Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released.](url)
```
     
Created diun with (Will change DIUN_WATCH_SCHEDULE to 12 hourly once this is fixed):

```
docker run -d --name diun \
  -e "TZ=Australia/Sydney" \
  -e "LOG_LEVEL=info" \
  -e "LOG_JSON=false" \
  -e "DIUN_WATCH_WORKERS=20" \
  -e "DIUN_WATCH_SCHEDULE=0 */1 * * *" \
  -e "DIUN_PROVIDERS_DOCKER=true" \
  -v /share/appdata/diun:/data \
  -v "/var/run/docker.sock:/var/run/docker.sock" \
  -l "diun.enable=true" \
    --restart=always \
  crazymax/diun:latest
```
