### ISSUE TITLE
Spurious newline when parsing Telegran token file

### ISSUE THREAD

**Issue by rockstorm101** [crazy-max/diun#616]
## Behaviour

Using the 'DIUN_NOTIF_TELEGRAM_TOKENFILE' to keep the token info out of the compose file triggers the error shown in the log below. I believe this is due to parsing that file adding a spurious "\n" after the token. The same setup but using 'DIUN_NOTIF_TELEGRAM_TOKEN' instead works perfectly. So I assume something is wrong with the TokenFile variable parsing.

## Configuration

* Diun version : 4.21 (Docker image on ARM)

> Configuration files:
> * docker-compose.yml
```yaml
services:
  diun:
    image: crazymax/diun:4.21
    environment:
      - "TZ=Europe/London"
      - "LOG_LEVEL=debug"
      - "LOG_JSON=false"
      - "DIUN_NOTIF_TELEGRAM_TOKENFILE=/run/secrets/bot-token"
      # - "DIUN_NOTIF_TELEGRAM_TOKEN=110201543:AAHdqTcvCH1vGWJxfSeofSAs0K5PALDsaw"
      - "DIUN_NOTIF_TELEGRAM_CHATIDSFILE=/run/secrets/chat-id"
    volumes:
      - ./diun.yml:/diun.yml:ro
      - ./file-provider.yml:/file-provider.yml:ro
      - diun-db:/data
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - bot-token
      - chat-id

volumes:
  diun-db:
    name: diun-db

secrets:
  bot-token:
    file: ../secrets/telegram-bot-token
  chat-id:
    file: ../secrets/telegram-chatid
```

> * diun config file
```yaml
watch:
  schedule: "0 */6 * * *"
  firstCheckNotif: true

providers:
  file:
    filename: /file-provider.yml
```
> * file-provider.yml file
```yaml
- name: alpine:3.15
```

### Logs

```
Sat, 21 May 2022 20:17:26 BST INF New image found image=docker.io/library/alpine:3.15 provider=file
Sat, 21 May 2022 20:17:26 BST DBG Manifest saved to database image=docker.io/library/alpine:3.15 provider=file
Sat, 21 May 2022 20:17:27 BST DBG Sending telegram notification... image=docker.io/library/alpine:3.15
Sat, 21 May 2022 20:17:27 BST ERR Telegram notification failed error="parse \"https://api.telegram.org/bot110201543:AAHdqTcvCH1vGWJxfSeofSAs0K5PALDsaw\\n/getMe\": net/url: invalid control character in URL" image=docker.io/library/alpine:3.15

```
