### ISSUE TITLE
Notifications only working for updated images, not for new versions

### ISSUE THREAD

**Issue by ontheair81** [crazy-max/diun#637]
## Behaviour

Notifications (by e-mail, in my case) are working great when an _existing image has been updated within it's version number_. However, I am not getting notifications when a _new version_ of an existing image is available.

### Steps to reproduce this issue

1. For example, using the image of webserver nginx:1.**22**.0
2. Diun sends an e-mail when this image has been updated by saying "docker.io/library/nginx:1.22.0 has been _updated_".
3. Wait for the nginx-Maintainers to release version 1.**23**.0
4. Diun is _not_ notifying me about the availability of this new available version - which is the reason for this report.
5. I pull nginx:1.**23**.0, replacing the old version.
6. _Afterwards_ Diun notifies me with "docker.io/library/nginx:1.23.0 is _available_"

### Expected behaviour

I would expect to be notified both when an existing image is updated (with same version number) and when an update to a higher version is available.

### Actual behaviour

There is no notification about when a higher version becomes available.

## Configuration

* Diun version : 4.21.0
* Platform (windows/linux) : Linux
* System info (type `uname -a`) : Linux bigserver 5.10.0-15-amd64 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux

> Paste your configuration files here
> * docker-compose.yml

```
version: "3.5"
services:
  diun:
    image: crazymax/diun:4.21.0
    container_name: diun
    hostname: BIGSERVER
    command: serve
    volumes:
      - "/home/user/bind-mounts/db-diun:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Berlin"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_MAIL_HOST=[removed]"
      - "DIUN_NOTIF_MAIL_PORT=465"
      - "DIUN_NOTIF_MAIL_SSL=true"
      - "DIUN_NOTIF_MAIL_USERNAME=[removed]"
      - "DIUN_NOTIF_MAIL_PASSWORD=[removed]"
      - "DIUN_NOTIF_MAIL_FROM=[removed]"
      - "DIUN_NOTIF_MAIL_TO=[removed]"
    labels:
      - "diun.enable=true"
      - "diun.notify_on=new;update"
    restart: always
```

### Logs

```
Fri, 03 Jun 2022 06:47:27 CEST INF Starting Diun version=4.21.0
Fri, 03 Jun 2022 06:47:27 CEST INF Configuration loaded from 12 environment variable(s)
Fri, 03 Jun 2022 06:47:27 CEST INF Cron triggered
Fri, 03 Jun 2022 06:47:27 CEST INF Found 23 image(s) to analyze provider=docker
Fri, 03 Jun 2022 06:47:30 CEST INF Jobs completed added=0 failed=0 skipped=0 unchanged=23 updated=0
Fri, 03 Jun 2022 06:47:30 CEST INF Cron initialized with schedule 0 */6 * * *
Fri, 03 Jun 2022 06:47:30 CEST INF Next run in 5 hours 12 minutes (2022-06-03 12:00:00 +0200 CEST)
```
### Additional remarks

I guess this is not a bug; for sure I am just doing something wrong ;-) Any help is very appreciated!
Thank you very much for this nice software!
