### ISSUE TITLE
Allow for custom notification message

### ISSUE THREAD

**Issue by Azertooth** [crazy-max/diun#64]
as title: other than the ability to edit in custom text it would be even nicer to be able to add hypertext and markdowns too

**Comment by TUISTERa** [comment]
Hello, Do you have any plans for adding this? At least i want to add a "#duin" at the end of the message , for filtering purpose at my telegram notifications...

**Comment by crazy-max** [comment]
@TUISTERa Yes I've planned to add this through a simple template. Keep you in touch.

**Comment by TheCatLady** [comment]
@crazy-max I'm also very interested in this functionality!  (I have OCD and am on a quest to uniformly style all my Pushover notifications.)  Would be happy to help test once you've implemented it!

**Comment by sintaxx** [comment]
Would this also include the ability to provide a custom name to the bot for example on discord it shows up as DIUN[bot], i'd like to be able to customize the name such as DIUN-Server1name, DIUN-Server2Name so both of my monitored servers can alert the same channel and i can differentiate them.

**Comment by TUISTERa** [comment]
If you can add custom tags In message the botname can be irrelevant. For
example #s1 #plex , #s2 #homeassistant etc...

**Comment by laurentlbm** [comment]
It would be very helpful if notifications included a link to the change log of the release. Unfortunately, that info doesn't seem readily available on docker hub, so a custom message with a link to the GitHub/website of the image would be an ok compromise.

**Comment by crazy-max** [comment]
Working on it for the next release. You will be able to customize the title and text of the message globally as well as for each notification providers. This will be limited to markdown and html rendering for the moment. The JSON or ENV output cill remain immutable.

**Comment by crazy-max** [comment]
You can test this feature with `crazymax/diun:edge`. Documentation for each notifiers can be found [here](https://github.com/crazy-max/diun/tree/master/docs/notif).

Example with `mail`:

```yaml
watch:
  workers: 20
  schedule: "0 */6 * * *"
  firstCheckNotif: false

notif:
  mail:
    host: localhost
    port: 25
    ssl: false
    insecureSkipVerify: false
    from: diun@example.com
    to: webmaster@example.com
    templateTitle: |
      {{ .Entry.Image }} released
    templateBody: |
      Docker tag {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }}
      which you subscribed to through {{ .Entry.Provider }} provider has been {{ if (eq .Entry.Status "new") }}newly added{{ else }}updated{{ end }}.
      This image has been {{ if (eq .Entry.Status "new") }}created{{ else }}updated{{ end }} at
      <code>{{ .Entry.Manifest.Created.Format "Jan 02, 2006 15:04:05 UTC" }}</code> with digest <code>{{ .Entry.Manifest.Digest }}</code>
      for <code>{{ .Entry.Manifest.Platform }}</code> platform.

providers:
  docker:
    watchByDefault: true
```

Documentation about notification template: https://github.com/crazy-max/diun/blob/master/docs/faq.md#notification-template
