### ISSUE TITLE
FTL Cannot load configuration error="At least one provider is required"

### ISSUE THREAD

**Issue by My-Random-Thoughts** [crazy-max/diun#649]
## Behaviour
Getting the error message "FTL Cannot load configuration error="At least one provider is required"" when I start the docker image.  It only started with the new update.  Was working fine before.

### Steps to reproduce this issue
Trying to start the docker image

### Expected behaviour
Image starts correctly

### Actual behaviour
It doesn't start :(

## Configuration

* Diun version : 4.22.0
* Platform (windows/linux) : Linux
* System info (type `uname -a`) : Linux 5.13.0-52-generic x86_64

> Paste your configuration files here
Docker Command:
`sudo docker run -d --name diun --restart unless-stopped --pull=always --network=host -v "$HOME/diun:/data" crazymax/diun:latest`

diun Config File
```
db:
  path: diun.db

watch:
  workers: 10
  schedule: "0 */6 * * *"
  firstCheckNotif: false
  compareDigest: true

notif:
  pushover:
    token: (removed)
    recipient: (removed)
    templateTitle: "{{ .Entry.Image.Path }} updated"
    templateBody: |
      An updated image for {{ .Entry.Image.Path }} has been released.

regopts:
  - name: "docker.io"
    selector: image
    username: myrandomthoughts2
    password: ZJwfdffxpg4w7vjxK7WQzXcureUEcek5

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    tlsVerify: false
    watchByDefault: true
    watchStopped: false

```

### Logs
Sun, 17 Jul 2022 20:42:46 UTC INF Starting Diun version=4.22.0
Sun, 17 Jul 2022 20:42:46 UTC DBG No configuration file found
Sun, 17 Jul 2022 20:42:46 UTC INF Configuration loaded from 1 environment variable(s)
Sun, 17 Jul 2022 20:42:46 UTC FTL Cannot load configuration error="At least one provider is required"

**Comment by crazy-max** [comment]
Can't repro with the following configuration:

```yaml
# config.yml

db:
  path: diun.db

watch:
  workers: 10
  schedule: "0 */6 * * *"
  firstCheckNotif: false
  compareDigest: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    tlsVerify: false
    watchByDefault: true
    watchStopped: false
```

```console
$ diun serve --config config.yml
Sun, 17 Jul 2022 22:59:59 CEST INF Starting Diun version=4.22.0
Sun, 17 Jul 2022 22:59:59 CEST INF Configuration loaded from file: /mnt/x/dev/neard/www/github/go/diun/bin/docker2.yml
Sun, 17 Jul 2022 22:59:59 CEST WRN No notifier available
Sun, 17 Jul 2022 22:59:59 CEST INF Database migration v2...
Sun, 17 Jul 2022 22:59:59 CEST INF Cron triggered
Sun, 17 Jul 2022 22:59:59 CEST INF Found 1 image(s) to analyze provider=docker
Sun, 17 Jul 2022 23:00:03 CEST INF New image found image=docker.io/moby/buildkit:master provider=docker
Sun, 17 Jul 2022 23:00:03 CEST INF Jobs completed added=1 failed=0 skipped=0 unchanged=0 updated=0
Sun, 17 Jul 2022 23:00:03 CEST INF Cron initialized with schedule 0 */6 * * *
Sun, 17 Jul 2022 23:00:03 CEST INF Next run in 59 minutes 56 seconds (2022-07-18 00:00:00 +0200 CEST)
```

Same using the Docker image:

```console
$ docker run --rm --name diun -v $(pwd)/config.yml:/diun.yml -v /var/run/docker.sock:/var/run/docker.sock crazymax/diun:4.22.0
Sun, 17 Jul 2022 22:59:59 CEST INF Starting Diun version=4.22.0
Sun, 17 Jul 2022 22:59:59 CEST INF Configuration loaded from file: /mnt/x/dev/neard/www/github/go/diun/bin/docker2.yml
Sun, 17 Jul 2022 22:59:59 CEST WRN No notifier available
Sun, 17 Jul 2022 22:59:59 CEST INF Database migration v2...
Sun, 17 Jul 2022 22:59:59 CEST INF Cron triggered
Sun, 17 Jul 2022 22:59:59 CEST INF Found 1 image(s) to analyze provider=docker
Sun, 17 Jul 2022 23:00:03 CEST INF New image found image=docker.io/moby/buildkit:master provider=docker
Sun, 17 Jul 2022 23:00:03 CEST INF Jobs completed added=1 failed=0 skipped=0 unchanged=0 updated=0
Sun, 17 Jul 2022 23:00:03 CEST INF Cron initialized with schedule 0 */6 * * *
Sun, 17 Jul 2022 23:00:03 CEST INF Next run in 59 minutes 56 seconds (2022-07-18 00:00:00 +0200 CEST)
```

Looking at your logs:

```
Sun, 17 Jul 2022 20:42:46 UTC DBG No configuration file found
```

And the command used:

```console
sudo docker run -d --name diun --restart unless-stopped --pull=always --network=host -v "$HOME/diun:/data" crazymax/diun:latest
```

It doesn't seem the config file is included in your container. So don't think it would work either in previous releases.

You can mount your config file with `-v $(pwd)/config.yml:/diun.yml`. You also forgot to mount the docker socket with `-v /var/run/docker.sock:/var/run/docker.sock`.
