### ISSUE TITLE
CPU usage while waiting for next CRON trigger

### ISSUE THREAD

**Issue by KptCheeseWhiz** [crazy-max/diun#652]
## Behaviour

The program has a little CPU usage (0.5-1% on a i5-1035G4) while waiting for its next CRON trigger. While it might not be a lot, it makes a big difference over time (~15 mins of CPU time per day) compared to using basic system CRON job (less than 1s of CPU time per day).

### Steps to reproduce this issue

1. Just run the program

### Expected behaviour

> No CPU usage while waiting for its next CRON trigger.

### Actual behaviour

> 0.5-1% CPU usage while waiting for its next CRON trigger.

## Configuration

* Diun version : 4.22.0
* Platform : linux
* System info : 5.15.0-41-generic # 44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

> * docker-compose.yml
```yml
version: "3.9"
services:
  diun:
    image: crazymax/diun:latest
    container_name: "diun"
    hostname: "diun"
    restart: "unless-stopped"
    command: serve --config /config/diun.yml
    volumes:
      - "./data:/data"
      - "./config:/config"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      LOG_LEVEL: "info"
      LOG_JSON: "false"
```
> * diun config file
```yml
watch:
  workers: 1
  schedule: "0 */6 * * *"

db:
  path: "/data/diun.db"

notif:
  discord:
    webhookURL: <REDACTED>
    templateBody: |
      A new update is available for {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }}

providers:
  docker:
    watchStopped: true
    watchByDefault: true
```

### Logs
I will add them in around 24h of execution with logging enabled if needed
