### ISSUE TITLE
Provide source url for notifications

### ISSUE THREAD

**Issue by Nuklon** [crazy-max/diun#654]
Similar to https://github.com/crazy-max/diun/issues/562.

As suggested in https://github.com/crazy-max/diun/issues/562#issuecomment-1067704789, perhaps a source_link can be added and shown in notification, which you can point to GitHub for example. This is different from the hub_link as it's useful to include both in notifications.

**Comment by crazy-max** [comment]
@Nuklon #749 should solve this issue. You can add any kind of metadata you want. In your case you could add a new metadata key `github_url` like:

```yaml
services:
  cloudflared:
    image: crazymax/cloudflared:latest
    labels:
      - "diun.enable=true"
      - "diun.metadata.github_url=https://github.com/crazy-max/docker-cloudflared"
    restart: always
```
