### ISSUE TITLE
Hostname with "_" does not appear correctly in email notifications

### ISSUE THREAD

**Issue by steakhutzeee** [crazy-max/diun#656]
### Steps to reproduce this issue

I added to my compose file:

`hostname: dk_diun`

### Expected behaviour

Hostname to appear in email notification

### Actual behaviour

The hostname in the emails appears like:

(triggered by _dk diun host)

## Configuration

* Diun version : latest
* Platform (windows/linux) : linux
* System info (type `uname -a`) :  `Linux DK 4.14.222-odroidxu4 #1 SMP PREEMPT Mon Nov 22 12:13:27 UTC 2021 armv7l GNU/Linux`

**Comment by crazy-max** [comment]
Can you post your compose file and diun yaml configuration (if applicable) please?

**Comment by steakhutzeee** [comment]
Sure:

```
version: "3.5"
services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    hostname: dk_diun
    environment:
      - TZ=Europe/Rome
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_NOTIF_MAIL_HOST=xxx
      - DIUN_NOTIF_MAIL_PORT=xxx
      - DIUN_NOTIF_MAIL_SSL=true
      - DIUN_NOTIF_MAIL_LOCALNAME=localhost
      - DIUN_NOTIF_MAIL_USERNAME=xxx
      - DIUN_NOTIF_MAIL_PASSWORD=xxx
      - DIUN_NOTIF_MAIL_FROM=xxx
      - DIUN_NOTIF_MAIL_TO=xxx
    volumes:
      - /srv/dev-disk-by-label-HC2/AppData/diun/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - profiler:/profiler
    restart: always
    dns:
      - 1.1.1.1
      - 1.0.0.1
networks:
    default:
      external:
        name: my-net

volumes:
  profiler:
```
