### ISSUE TITLE
Error for images from GHCR

### ISSUE THREAD

**Issue by cfoellmann** [crazy-max/diun#660]
I added the first image from the github container repo ghcr.io and I get the following error in the logs

`Wed, 27 Jul 2022 18:00:02 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: reading digest master in docker.io/ghcr.io/umputun/github-backup-docker: errors:\ndenied: requested access to the resource is denied\nerror parsing HTTP 401 response body: unexpected end of JSON input: \"\"\n" image=docker.io/ghcr.io/umputun/github-backup-docker:master provider=docker`

It seems to be assumed that the image is on the dockerhub `docker.io/ghcr.io/umputun/github-backup-docker`

my container is set in docker-compose

```yaml
services:
  github-backup:
    image: ghcr.io/umputun/github-backup-docker:master
    container_name: "github-backup"
    hostname: "github-backup"
    restart: always
```

How can I fix that? is it a bug or do I need to change anything on my container config?
