### ISSUE TITLE
Can't get sort_tags working

### ISSUE THREAD

**Issue by GeoCookie** [crazy-max/diun#662]
Hi there,

### Steps to reproduce this issue

Use a file as provider with this inside (double dashes are to prevent Github to use bulleted list)

```yaml
  - name: ghcr.io/crazy-max/diun
    watch_repo: true
    max_tags: 10
    sort_tags: semver
    
  - name: crazymax/diun
    watch_repo: true
    max_tags: 10
    sort_tags: semver
```

### Expected behaviour

I expected Diun to get image tags sorted by version, thanks to `sort_tags:semver`
Related to [https://github.com/crazy-max/diun/pull/645](url)

### Actual behaviour

Diun receives the image tags in a random order

![image](https://user-images.githubusercontent.com/43962716/181906273-874f6fb8-b053-40d1-9a40-db5cb443d26c.png)

## Configuration

* Diun version : 4.22
* Platform : linux
* System info (type `uname -a`) : Linux rikku.geocookie.lan 4.19.0-21-amd64 (#)1 SMP Debian 4.19.249-2 (2022-06-30) x86_64 GNU/Linux

I use a Docker run command for my test

```console
  docker run --name diun-test \
    -e TZ=Europe/Paris \
    -e LOG_LEVEL=debug \
    -e LOG_JSON=false \
    -e DIUN_PROVIDERS_FILE_FILENAME=/data/service.yml \
    -v diun-test_diun-test_data:/data \
    ghcr.io/crazy-max/diun:4.22
```

### Logs

The logs are quite long. Tell me if you need them (I searched in them and I can't find the word "semver" or "sort_tags"
