### ISSUE TITLE
Gotify tokenFile as environement variable dont work

### ISSUE THREAD

**Issue by anup92k** [crazy-max/diun#665]
### Steps to reproduce this issue

1. Run diun on docker (I'm using Docker Compose)
2. Set `DIUN_NOTIF_GOTIFY_TOKENFILE` to a file containing the Gotify token
3. Run `diun notif test`

### Expected behaviour

I expected to get the notification on my Gotify instance like when I'm using `DIUN_NOTIF_GOTIFY_TOKENFILE`.

### Actual behaviour

Got this message from the CLI :
> diun: error: rpc error: code = Unknown desc = 401 Unauthorized: you need to provide a valid access token or user credentials to access this api

## Configuration

* Diun version : 4.22.0
* Platform (windows/linux) : Ubuntu (server) 20.04 LTS
* System info (type `uname -a`) : `Linux 4b24f558d9fd 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 Linux`

> Paste your configuration files here
> * docker-compose.yml

```yaml
version: "3.8"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun-app
    restart: unless-stopped
    command: serve
    environment:
      - TZ=${MY_TZ}
      - LOG_LEVEL=${MY_LOG_LEVEL}
      - LOG_JSON=${MY_LOG_JSON}
      - DIUN_WATCH_WORKERS=${MY_DIUN_WATCH_WORKERS}
      - DIUN_WATCH_SCHEDULE=${MY_DIUN_WATCH_SCHEDULE}
      - DIUN_PROVIDERS_DOCKER=${MY_DIUN_PROVIDERS_DOCKER}
      - DIUN_NOTIF_GOTIFY_ENDPOINT=${MY_DIUN_NOTIF_GOTIFY_ENDPOINT}
      # - DIUN_NOTIF_GOTIFY_TOKEN=${MY_DIUN_NOTIF_GOTIFY_TOKEN}
      - DIUN_NOTIF_GOTIFY_TOKENFILE=${MY_DIUN_NOTIF_GOTIFY_TOKENFILE}
      - DIUN_NOTIF_GOTIFY_PRIORITY=${MY_DIUN_NOTIF_GOTIFY_PRIORITY}
      - DIUN_NOTIF_GOTIFY_TEMPLATETITLE=${MY_DIUN_NOTIF_GOTIFY_TEMPLATETITLE}
      - DIUN_NOTIF_GOTIFY_TEMPLATEBODY=${MY_DIUN_NOTIF_GOTIFY_TEMPLATEBODY}
    volumes:
      - /etc/gotify.token:/etc/gotify.token:ro
      - /var/lib/diun/data/:/data/
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - diun.enable=true
```

> * k8s deployment configuration

None

> * environment variables

```
MY_TZ=Europe/Paris
MY_LOG_LEVEL=info
MY_LOG_JSON=false
MY_DIUN_WATCH_WORKERS=20
MY_DIUN_WATCH_SCHEDULE=0 */6 * * *
MY_DIUN_PROVIDERS_DOCKER=true
MY_DIUN_NOTIF_GOTIFY_ENDPOINT=https://gotify.mydomain.tld
MY_DIUN_NOTIF_GOTIFY_TOKEN=AZERTY
MY_DIUN_NOTIF_GOTIFY_TOKENFILE=/etc/gotify.token
MY_DIUN_NOTIF_GOTIFY_PRIORITY=5
MY_DIUN_NOTIF_GOTIFY_TEMPLATETITLE={{ .Entry.Image }} {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }}
MY_DIUN_NOTIF_GOTIFY_TEMPLATEBODY=Docker tag {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }} {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }} on {{ .Entry.Image.Domain }} registry.
```
*I've changed the URL and Token here*

> * diun config file

None

### Tests

When on the CLI (running `docker exec -it diun-app /bin/sh`), the env variable seems to be working fine because

```
cat $DIUN_NOTIF_GOTIFY_TOKENFILE
```
give me the token I've set on the file.
