### ISSUE TITLE
email notification through gmail

### ISSUE THREAD

**Issue by jerome6994** [crazy-max/diun#684]
Hello,

I'm having trouble setting up email notification on my gmail box.
I had several errors following my diun.yml configuration like :

```diun: error: rpc error: code = Unknown desc = EOF```
or
```diun: error: rpc error: code = Unknown desc = tls: first record does not look like a TLS handshake```

my settings are as follows
```
notif:
  mail:
    host: smtp.gmail.com
    port: 587
    ssl: false
    insecureSkipVerify: false
    from: my_mail@gmail.com
    password: my_app_password (2FA)
    to:
      - my_mail@gmail.com
    templateTitle: "xxxxxxx"
    tempateBody: "yyyyyyyyy"
```

Do you have an example of settings that would work ?
Can you tell me how to correct this setting ?

Thanks

Jérôme

**Comment by navierb** [comment]
I don't use the default templates, but for me this is working fine
```
notif:
  mail:
    host: smtp.gmail.com
    port: 25
    ssl: false
    insecureSkipVerify: false
    username: myemailadress
    password: my-super-secure-password
    from: myemailadress@gmail.com
    to: myemailadress@gmail.com
```

**Comment by JaneDilbert** [comment]
Hi,

I've been trying to make this work, also with Gmail. I have tried with and without the @gmail.com, with port 25 and 465, with and without SSL... No luck, I always end up with
```
diun: error: main.NotifTestCmd.Run(): rpc error: code = Unknown desc = 535 5.7.8 Username and Password not accepted. For more information, go to
             5.7.8  https://support.google.com/mail/?p=BadCredentials - gsmtp
```

Below my compose.yml:
```
services:
  diun:
    container_name: diun
    hostname: diun
    image: crazymax/diun
    restart: unless-stopped
    # container
    command: serve
    environment:
      - TZ=Pacific/Auckland
      - DIUN_NOTIF_MAIL_FROM=[my_mail]@gmail.com
      - DIUN_NOTIF_MAIL_HOST=smtp.gmail.com
      - DIUN_NOTIF_MAIL_PASSWORD=aaaabbbbccccdddd # App password because 2FA
      - DIUN_NOTIF_MAIL_PORT=25
      - DIUN_NOTIF_MAIL_TEMPLATETITLE=Image {{ if (eq .Entry.Status "new") }}is available{{ else }}update available{{ end }}
      - DIUN_NOTIF_MAIL_TEMPLATEBODY={{ .Entry.Image.Path }} {{ if (eq .Entry.Status "new") }}created{{ else }}updated{{ end }} on {{ .Entry.Manifest.Created.Format "2006-02-02 15:04" }}
      - DIUN_NOTIF_MAIL_TO=
        - [some_email@some_domain]
      - DIUN_NOTIF_MAIL_USERNAME=[my_mail]@gmail.com
      - DIUN_NOTIF_MAIL_SSL=false
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_WATCH_SCHEDULE=0 10 * * *
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    # resources
    cpu_shares : 10
    cpuset: "0"
    mem_limit : 512M
    volumes:
      - ./diun:/data"
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    # network
    networks:
      bridge0:
        ipv4_address: 172.21.0.106
#    ports:
#      - 8080:8080 # Web UI port

networks:
  bridge0:
    external: true
    name: bridge-custom
```

Any help will be appreciated!
