### ISSUE TITLE
[Feature request] Local notification option

### ISSUE THREAD

**Issue by blotsome** [crazy-max/diun#685]
I am looking for a way to help my workflow in updating docker containers (previous workflow was not to update ever, unless something broke). I came across diun and it seems great. However, I am old and don't use discord or telegram. I want something like the Ubuntu MOTD that tells you if you have updates when you ssh into a server. Is there a way to just have the update information in a single text file that another script (MOTD script) could parse? Has anyone done something like this before, seems a bit daunting to start from scratch.

**Comment by eriol** [comment]
@blotsome you may want to look at https://crazymax.dev/diun/notif/script/ to generate the first file. Never used this it but according to documentation you should get all the information you need in environment variables specified at the top of that page.

**Comment by crazy-max** [comment]
`cmd` must be a command or script to execute.

This should work:

```yaml
notif:
  script:
    cmd: "/bin/sh"
    args:
      - "echo $DIUN_ENTRY_IMAGE >> /data/diun_notfiy.txt"
```

Or just create a shell script and mount it to the container:

```shell
#!/usr/bin/env sh
# ./myscript.sh
echo $DIUN_ENTRY_IMAGE >> diun_notfiy.txt
```

```yaml
# ./diun.yml

watch:
  workers: 20
  schedule: "0 */6 * * *"
  firstCheckNotif: false

providers:
  docker:
    watchByDefault: true

notif:
  script:
    cmd: "/myscript.sh"
```

```yaml
# ./docker-compose.yml

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - "./data:/data"
      - "./diun.yml:/diun.yml:ro"
      - "./myscript.sh:/myscript.sh:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
```
