### ISSUE TITLE
Feature request: when using Swarm provider, diun should list images present in all nodes

### ISSUE THREAD

**Issue by josejsarmento** [crazy-max/diun#690]
### Steps to reproduce this issue

1. On manager node, `docker exec -it diun_service1 sh`
2. Run `diun image list`

### Expected behaviour

Last command should output all images available in all nodes.

### Actual behaviour

It only outputs images in the manager node.

## Configuration

* Diun version : 4.22.0
* Platform (windows/linux) : linux

Stack .yaml file:

```yaml
version: "3.5"

services:
  diun_app:
    image: docker.io/crazymax/diun:latest
    volumes:
      - "diun-data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      TZ: Europe/Lisbon
      LOG_LEVEL: 'info'
      LOG_JSON: 'false'
      DIUN_DB_PATH: '/data/diun.db'
      DIUN_WATCH_WORKERS: '20'
      DIUN_WATCH_SCHEDULE: '0 */6 * * *'
      DIUN_PROVIDERS_SWARM: 'true'
    deploy:
      placement:
        constraints:
          - node.role == manager
volumes:
  diun-data:
```
