### ISSUE TITLE
/diun.yml is a directory (docker-compose)

### ISSUE THREAD

**Issue by JmL40240** [crazy-max/diun#713]
Hi, i'm not able to create container with docker compose on Portainer (with stack function)

### Steps to reproduce this issue

Trying to define a compose file with docker compose and portainer

>   diun:
>     image: crazymax/diun:latest
>     container_name: diun
>     command: serve
>     volumes:
>       - /srv/dev-disk-by-uuid-000ee8dd-f79d-4e00-894b-6a16f2bd8f34/diun/diun.yml:/diun.yml
>       - /srv/dev-disk-by-uuid-000ee8dd-f79d-4e00-894b-6a16f2bd8f34/diun/:/data   
>       - /var/run/docker.sock:/var/run/docker.sock
>     environment:
>       - TZ=Europe/Paris
>       - LOG_LEVEL=info
>       - LOG_JSON=false
>       - DIUN_WATCH_WORKERS=20
>       - DIUN_WATCH_SCHEDULE=*/2 * * * *
>       - DIUN_PROVIDERS_DOCKER=true       
>     labels:
>       - diun.enable=true
>     restart: always

### Logs
Log returns
```
./diun.yml is a directory
```

Thanks

**Comment by tobidemski** [comment]
Do you have an existing file in your path: "/srv/dev-disk-by-uuid-000ee8dd-f79d-4e00-894b-6a16f2bd8f34/diun/diun.yml"?
You have to create a yml file with your definition in order to a file bind .

**Comment by JmL40240** [comment]
Hi,

I try again by creating a diun.yml file in the host directory, but same problem, cannot find diun configuration.

My docker-compose :

`services:
  diun:
    image: crazymax/diun:latest
    container_name: diun_test
    command: serve
    volumes:
      - /srv/dev-disk-by-uuid-000ee8dd-f79d-4e00-894b-6a16f2bd8f34/diun_test/:/data
      - /srv/dev-disk-by-uuid-000ee8dd-f79d-4e00-894b-6a16f2bd8f34/diun_test/diun.yml:/diun.yml:ro   
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Paris
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=*/2 * * * *
      - DIUN_PROVIDERS_DOCKER=true  
    labels:
      - diun.enable=true
      - diun.watch_repo=true
    restart: always
`

My diun.yml file 

`notif:
  mail:
    host: smtp.gmail.com
    port: 465
    ssl: true
    insecureSkipVerify: false
	username:xxxx@xxxx.com
	password:xxxxxxxxxxx
    from: xxxx@xxxx.com
    to:
      - xxxx@xxxx.com  
    templateTitle: "{{ .Entry.Image }} released"
    templateBody: |
      Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released.
`

Container log 

`
Wed, 02 Nov 2022 22:15:49 CET FTL Cannot load configuration error="Failed to decode configuration from file: read /diun.yml: is a directory"
Wed, 02 Nov 2022 22:16:49 CET INF Starting Diun version=4.22.0
`

**Comment by tobidemski** [comment]
Not sure but maybe this works. Try to use quotes:

- "/srv/dev-disk-by-uuid-000ee8dd-f79d-4e00-894b-6a16f2bd8f34/diun_test/diun.yml:/diun.yml:ro"

**Comment by hugalafutro** [comment]
Couldn't you use more "normal" path, such as `/some/thing/diun.yml`? Is your directory really called `dev-disk-by-uuid-000ee8dd-f79d-4e00-894b-6a16f2bd8f34` ? That to me looks like a part of line from fstab unless you're mounting device `dev-disk-by-uuid-000ee8dd-f79d-4e00-894b-6a16f2bd8f34` into a directory `dev-disk-by-uuid-000ee8dd-f79d-4e00-894b-6a16f2bd8f34`. In my experience the more special characters there is in the path and the longer it is the more issues like this crop up

**Comment by XamYp** [comment]
Hello same issue here :
```yaml
version: "3.5"
services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - "/home/docker/diun/data:/data"
      - "/home/docker/diun/data/diun.yml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - TZ=Europe/Paris
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 5,12 * * *
      - DIUN_PROVIDERS_DOCKER=true
    labels:
      - diun.enable=true
      - diun.watch_repo=true
    restart: unless-stopped
```
