### ISSUE TITLE
"Cannot get image digest from HEAD request" for some images.

### ISSUE THREAD

**Issue by hugalafutro** [crazy-max/diun#723]
## Behaviour
I run about 70 containers spread across 3 pi's and 1 vm, so pretty much never a day goes by I wouldn't get at least 1 image update notification from diun. Last 2 days I got none, looking at the log it seems diun can't contact lscr.io / ghcr.io. I can ping both addresses successfully from both the host and inside diun container. Some images check ok, some don't `diun  | Fri, 25 Nov 2022 15:20:14 UTC INF github.com/crazy-max/diun/v4/internal/app/diun.go:185 > Jobs completed added=0 failed=15 skipped=0 unchanged=30 updated=0`

This is happening on machines both connected directly to internet and via wireguard vpn (mullvad) connection.

### Steps to reproduce this issue

1. run diun as normally
2. ???
3. observe logs

### Expected behaviour

diun should be able to check for updates

### Actual behaviour

I think it doesn't check for updates for lscr/ghcr.io images

## Configuration

* Diun version : 4.22.0
* Platform (windows/linux) : linux
* System info (type `uname -a`) : `Linux vm-docker 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

> Paste your configuration files here
> * docker-compose.yml
```
version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    hostname: vm-docker_diun
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=${TIMEZONE}"
      - "LOG_LEVEL=debug"
      - "LOG_CALLER=true"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 12 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_TELEGRAM_TOKEN=${TELE_TOKEN}"
      - "DIUN_NOTIF_TELEGRAM_CHATIDS=${TELE_CHATID}"
    restart: unless-stopped
    labels:
      containermon.enable: true
```
> * k8s deployment configuration
n/a
> * environment variables
```
TIMEZONE=Europe/London
TELE_TOKEN=[REDACTED]
TELE_CHATID=[REDACTED]
```
> * diun config file
n/a

### Logs

https://o.o5.ddns.net/JRjOc
