### ISSUE TITLE
Cannot get image digest from HEAD request: too many requests to registry

### ISSUE THREAD

**Issue by XamYp** [crazy-max/diun#731]
## Behaviour
Hello, I have some problems with Diun. I put the label "diun.enable" to "true" on all the desired containers.

## Configuration

* Diun version : sha256:712017b86c4b7a5c1248113a84b5051628dee83f7e89d84176746fe0dc9d8547 
* Platform (windows/linux) : Linux
* System info (type `uname -a`) : Linux 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux 
My file "diun.yml" :

```yaml
notif:
  discord:
    webhookURL: https://discord.com/api/webhooks/xxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxx
    mentions:
      - "@here"
      - "@everyone"
    renderFields: true
    timeout: 10s
    templateBody: |
      Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released.
```

```yaml
---
version: "3.5"
services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - "/home/docker/diun/data:/data"
      - "/home/docker/diun/data/diun.yml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - TZ=Europe/Paris
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 18,23 * * *
      - DIUN_PROVIDERS_DOCKER=true
    labels:
      - diun.enable=true
      - diun.watch_repo=true
    restart: unless-stopped
```

### Logs

```
Fri, 16 Dec 2022 15:04:02 CET INF Starting Diun version=4.22.0
Fri, 16 Dec 2022 15:04:02 CET INF Configuration loaded from file: /diun.yml
Fri, 16 Dec 2022 15:04:02 CET INF Configuration loaded from 4 environment variable(s)
Fri, 16 Dec 2022 15:04:02 CET INF Cron triggered
Fri, 16 Dec 2022 15:04:03 CET INF Found 13 image(s) to analyze provider=docker
Fri, 16 Dec 2022 15:04:11 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=86 updated=0
Fri, 16 Dec 2022 15:04:11 CET INF Cron initialized with schedule 0 18,23 * * *
Fri, 16 Dec 2022 15:04:11 CET INF Next run in 2 hours 55 minutes (2022-12-16 18:00:00 +0100 CET)
Fri, 16 Dec 2022 18:00:00 CET INF Cron triggered
Fri, 16 Dec 2022 18:00:00 CET INF Found 13 image(s) to analyze provider=docker
Fri, 16 Dec 2022 18:00:03 CET WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: too many requests to registry" image=docker.io/crazymax/diun:3.0.0-beta.4 provider=docker
Fri, 16 Dec 2022 18:00:03 CET WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: too many requests to registry" image=docker.io/crazymax/diun:2.3.0 provider=docker
Fri, 16 Dec 2022 18:00:04 CET WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: too many requests to registry" image=docker.io/crazymax/diun:1.3.0 provider=docker
Fri, 16 Dec 2022 18:00:04 CET WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: too many requests to registry" image=docker.io/crazymax/diun:1.0.2 provider=docker
Fri, 16 Dec 2022 18:00:04 CET WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: too many requests to registry" image=docker.io/crazymax/diun:1.0.1 provider=docker
Fri, 16 Dec 2022 18:00:04 CET WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: too many requests to registry" image=docker.io/crazymax/diun:0.2.0 provider=docker
Fri, 16 Dec 2022 18:00:05 CET WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: too many requests to registry" image=docker.io/plexinc/pms-docker:latest provider=docker
Fri, 16 Dec 2022 18:00:05 CET INF Jobs completed added=0 failed=7 skipped=0 unchanged=79 updated=0
Fri, 16 Dec 2022 18:00:05 CET INF Next run in 4 hours 59 minutes (2022-12-16 23:00:00 +0100 CET)
```

I do not receive any notification, Diun stops and does not check all the images and in addition I have these error messages.

Thanks for the help
