### ISSUE TITLE
Consider Supporting Healthchecks

### ISSUE THREAD

**Issue by wkelton** [crazy-max/diun#78]
See [Healthchecks.io](https://healthchecks.io).

This would prevent silent failures (for example, the host goes down).

This could perhaps be configured with a sub-dict under `watch`:
```
watch:
  schedule: "0 0 * * *"
  healthchecks:
    url: https://hc-ping.com/uuid
```
