### ISSUE TITLE
question using portainer setup

### ISSUE THREAD

**Issue by mfscorp** [crazy-max/diun#795]
I setup a stack in portainer with Diun with a .yml file set locally
upon configuring the mail notif i cant get the passwordFile to work
The file for some  reason it does not read it out, plain txt file just to try it out.
it reads the usernameFile correctly because i get an error:
```
/ # diun notif test
diun: error: rpc error: code = Unknown desc = 535 5.7.0 SMTP301 Authentication failed for user mymail@ziggo.nl ;id=Ua5########;sid=Ua5######;mta=smtp1.tb;d=20230221;t=222217[CET];ipsrc=myipaddress;
/ #
```

I also tried .env setups but also here i run into the issue the variable is not known inside the container(question is which container portainer(impossible to hide env inside this one) or diun or local)
Local i tried to setup but does not take it.
In Diun container tried to set it up but it does not load on container start, also i will loose setup manually done inside the container like to refrain from that.

putting in plain pass into the local .yml works as designed.

What am i doing wrong?

What i would like in the end is or use .env variables or gpg encrypted file (so reading the pass after decrypt) within portainer setup
 
**Setup stack in portainer:**
```
services:
  diun:
    image: crazymax/diun:latest
    #container_name: diun
    hostname: diun
    command: serve
    volumes:
      - "/mylocal/path/to/diun/data:/data"
      - "/mylocal/path/to/diun/diun.yml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Amsterdam"
      - "LOG_LEVEL=debug"
      - "LOG_JSON=false"
    restart: always
```

**contents of diun.yml file:**                                                                                   
```
watch:
  workers: 20
  schedule: "0 */6 * * *"
  firstCheckNotif: false

providers:
  docker:
    watchByDefault: true

notif:
  mail:
    host: smtp.ziggo.nl
    port: 587
    ssl: false
    insecureSkipVerify: false
    usernameFile: /data/.test1
    passwordFile: /data/.test2
    from: diun@test.com
    to: mymail@ziggo.nl
    templateTitle: |
      {{ .Entry.Image }} {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }}
    templateBody: |
      Docker tag {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }}
      which you subscribed to through {{ .Entry.Provider }} provider {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }}
      on **{{ .Entry.Image.Domain }}** registry (triggered by _{{ escapeMarkdown .Meta.Hostname }}_ host).

      This image has been {{ if (eq .Entry.Status "new") }}created{{ else }}updated{{ end }} at
      <code>{{ .Entry.Manifest.Created.Format "Jan 02, 2006 15:04:05 UTC" }}</code> with digest <code>{{ .Entry.Manifest.Digest }}</code>
      for <code>{{ .Entry.Manifest.Platform }}</code> platform.

      Need help, or have questions? Go to {{ .Meta.URL }} and leave an issue.
```

**setup .test files:**
test1 contains user
test2 contains password
