### ISSUE TITLE
Unsupported external secret

### ISSUE THREAD

**Issue by mfscorp** [crazy-max/diun#799]
## Behaviour
starting stack in portainer (swarm active) with secrets setup: 

_failed to deploy a stack: 
Network diun_default Creating 
Network diun_default Created 
Container diun Creating 
unsupported external secret mailuser1_

### Steps to reproduce this issue
start new stack in portainer

### Expected behaviour
That it reads the secrets from portainer

### Actual behaviour
not supported by container ?

## Configuration
1. Setup secrets in portainer
   mailuser1
   mailpassword1
![image](https://user-images.githubusercontent.com/34352826/221367917-e7a15563-0782-4bdb-a8b2-7b1db5c76987.png)

2. Portainer stack setup:
```
Version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - "/path/in/host/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - TZ=Europe/Amsterdam
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE="0 */6 * * *"
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_NOTIF_MAIL_HOST=smtp.ziggo.nl
      - DIUN_NOTIF_MAIL_PORT=587
      - DIUN_NOTIF_MAIL_SSL=false
      - DIUN_NOTIF_MAIL_INSECURESKIPVERIFY=false
      - DIUN_NOTIF_MAIL_LOCALNAME=diuntest
      - DIUN_NOTIF_MAIL_USERNAMEFILE=/run/secrets/mailuser1
      - DIUN_NOTIF_MAIL_PASSWORDFILE=/run/secrets/mailpassword1
      - DIUN_NOTIF_MAIL_FROM=diun@test.com
      - DIUN_NOTIF_MAIL_TO=/run/secrets/mailuser1
      - DIUN_NOTIF_MAIL_TEMPLATETITLE={{ .Entry.Image }} {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }}
      - DIUN_NOTIF_MAIL_TEMPLATEBODY=Docker tag {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }}
                                     which you subscribed to through {{ .Entry.Provider }} provider {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }}
                                     on **{{ .Entry.Image.Domain }}** registry (triggered by _{{ escapeMarkdown .Meta.Hostname }}_ host).
                                     
                                     This image has been {{ if (eq .Entry.Status "new") }}created{{ else }}updated{{ end }} at
                                     <code>{{ .Entry.Manifest.Created.Format "Jan 02, 2006 15:04:05 UTC" }}</code> with digest <code>{{ .Entry.Manifest.Digest }}</code>
                                     for <code>{{ .Entry.Manifest.Platform }}</code> platform.
                                     
                                     Need help, or have questions? Go to {{ .Meta.URL }} and leave an issue.
    labels:
      - diun.enable=true
    secrets:
      - mailuser1
      - mailpassword1
    restart: always

secrets:
  mailuser1:
    external: true
  mailpassword1:
    external: true
```

* Diun version :  latest (4.24)
* Platform (windows/linux) : linux
