### ISSUE TITLE
Error when running notif test and diun image list 

### ISSUE THREAD

**Issue by zilexa** [crazy-max/diun#800]
## Behaviour
```
diun serve   
Sun, 26 Feb 2023 11:42:31 CET INF Starting Diun version=dev
Sun, 26 Feb 2023 11:42:31 CET INF Configuration loaded from file: /etc/diun/diun.yml
Sun, 26 Feb 2023 11:42:31 CET INF Cron triggered
Sun, 26 Feb 2023 11:42:31 CET INF Found 21 image(s) to analyze provider=docker
Sun, 26 Feb 2023 11:42:34 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=21 updated=0
diun notif test                                                                             ✔ 
diun: error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:42286: connect: connection refused"
diun image list                                                                             ✔ 
diun: error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:42286: connect: connection refused"
```

### Steps to reproduce this issue

1. installed via AUR
2. config created (see below)
3. ran diun serve twice

### Expected behaviour
first run lists the images, second run shows the above. All fine. Until I run `diun notif test`. I expect a successful test

### Actual behaviour
error as shown. 

## Configuration
```
notif:
  mail:
    host: mail.smtp2go.com
    port: 587
    ssl: false
    insecureSkipVerify: true
    username: removed
    password: removed
    from: removed@mydomain.com
    to: my@email.com

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watchByDefault: true
    watchStopped: true
```

* Diun version : 4.24.0-2 (dev)
* Platform (windows/linux) : Manjaro Gnome
* System info (type `uname -a`) : `Linux obelix 5.15.94-1-MANJARO #1 SMP PREEMPT Tue Feb 14 19:45:58 UTC 2023 x86_64 GNU/Linux`

Note I tried to install diun-bin from AUR: https://aur.archlinux.org/packages/diun-bin
but there is an issue with it, so I used the package that builds locally: 
https://aur.archlinux.org/packages/diun
