### ISSUE TITLE
Help with custom build images

### ISSUE THREAD

**Issue by kekec777** [crazy-max/diun#815]
Hi everyone
Im quite new to Diun and need some help..

I have installed Diun with docker-compose like this:

```yaml
diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    networks:
        DockerNet:
            ipv4_address: 192.168.1.222
    restart: unless-stopped
    volumes:
      - "/srv/dev-disk-by-uuid-2d63569d-15a7-41a3-8009-e9b487095e11/docker/config/diun/data:/data"
      - "/srv/dev-disk-by-uuid-2d63569d-15a7-41a3-8009-e9b487095e11/docker/config/diun/diun.yml:/diun.yml:ro"
      - "/srv/dev-disk-by-uuid-2d63569d-15a7-41a3-8009-e9b487095e11/docker/config/dockercompose/dockerfiles:/dockerfiles"
      - "/root/.docker/config.json:/root/.docker/config.json:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Copenhagen"
      - "LOG_LEVEL=debug"
      - "LOG_JSON=false"
      - "CONFIG=/diun.yml"
    labels:
      - com.centurylinklabs.watchtower.enable=true  # Watchtower will update this container True/False
```

My diun.yml look like this:

```yaml
watch:

  workers: 20
    schedule: "0 */6 * * *" 
  jitter: 30s
  firstCheckNotif: false
  compareDigest: true
notif:
  telegram:
    token: SecretToken
    chatIDs:
      - SecretChatID
    templateBody: |
      Docker tag {{ if .Entry.Image.HubLink }}[{{ .Entry.Image }}]({{ .Entry.Image.HubLink }}){{ else }}{{ .Entry.Image }}{{ end }} which you subscribed to through {{ .Entry.Provider }} provider has been {{ if (eq .Entry.Status "new") }}newly added{{ else }}updated{{ end }} on {{ escapeMarkdown .Meta.Hostname }}.

regopts:
  - name: "docker.io"
    selector: image
    usernameFile: /data/.username
    passwordFile: /data/.password

providers:
  dockerfile:
    patterns:
      - dockerfiles/elkarbackup/Dockerfile
      - dockerfiles/wordpress/Dockerfile
      - dockerfiles/jdownloader/Dockerfile
```

So i have 3 images i want to "keep an eye on" as you can see.
And every Dockerfile is starting with:
`# diun.notify_on=new;update`

so it should notify me when there's an update.

But im not sure if this is working , i have tested to send notification and thats working:
docker-compose exec diun diun notif test

so there was an update to Wordpress and i did NOT get any notification on my telegram.. why?

**Comment by crazy-max** [comment]
What's your dockerfiles look like?:

```yaml
providers:
  dockerfile:
    patterns:
      - dockerfiles/elkarbackup/Dockerfile
      - dockerfiles/wordpress/Dockerfile
      - dockerfiles/jdownloader/Dockerfile
```

Would also need logs with debug enabled.
