### ISSUE TITLE
Matrix Notification rate limiting

### ISSUE THREAD

**Issue by elia-blue** [crazy-max/diun#845]
### Steps to reproduce this issue

1. Enable the Matrix notification
2. Have 40 or so images notify you at once

### Expected behaviour

I'd expect all notifications to get sent.

### Actual behaviour

Only the first couple of notifications are sent, the remaining not sent and logged with the error `M_LIMIT_EXCEEDED: Too Many Requests`. 

## Configuration

* Diun version : v4.24.0
* Platform (windows/linux) : Linux (docker)
* System info (type `uname -a`) : `Linux hostname 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux`

```yaml
# compose.yaml
version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    command: serve --config /diun.yaml
    volumes:
      - "./data:/data"
      - "./diun.yaml:/diun.yaml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      TZ: Europe/Berlin
      LOG_LEVEL: info
      LOG_JSON: false
    restart: always
```

```yaml
# diun.yaml
watch:
  workers: 10
  schedule: "0 */6 * * *"
  jitter: 30s
  firstCheckNotif: true

notif:
  mail:
    host: mail.epicblu.net
    port: 587
    ssl: false
    insecureSkipVerify: false
    username: diun@epicblu.net
    password: acahr7Miy6OphahgeefireephahmeiPu3HiWaingohnieF3y
    from: diun@epicblu.net
    to:
      - vps@elia.blue
  matrix:
    homeserverURL: https://matrix.epicblu.net
    user: "@bot_diun:epicblu.net"
    password: ieyia6uivah5tooth5Aefae5Ey0EeY3m
    roomID: "!hsyBTkDBboxrwsotPK:epicblu.net"
    msgType: text
    templateBody: 'Docker tag {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }} which you subscribed to through {{ .Entry.Provider }} provider {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }} on {{ .Entry.Image.Domain }} registry (triggered by vps.elia.blue).'

providers:
  docker:
    watchStopped: true
    watchByDefault: true
```

### Logs

```
...snip...
17-diun-diun-1  | Mon, 17 Apr 2023 10:50:28 CEST ERR Matrix notification failed error="failed to authenticate Matrix user: contents=[123 34 101 114 114 99 111 100 101 34 58 34 77 95 76 73 77
73 84 95 69 88 67 69 69 68 69 68 34 44 34 101 114 114 111 114 34 58 34 84 111 111 32 77 97 110 121 32 82 101 113 117 101 115 116 115 34 44 34 114 101 116 114 121 95 97 102 116 101 114 95 109
115 34 58 51 51 49 54 48 53 125] msg=Failed to POST JSON to /_matrix/client/r0/login code=429 wrapped=M_LIMIT_EXCEEDED: Too Many Requests" image=docker.io/library/caddy:2
17-diun-diun-1  | Mon, 17 Apr 2023 10:50:28 CEST ERR Cannot logout error="contents=[123 34 101 114 114 99 111 100 101 34 58 34 77 95 77 73 83 83 73 78 71 95 84 79 75 69 78 34 44 34 101 114 114 111 114 34 58 34 77 105 115 115 105 110 103 32 97 99 99 101 115 115 32 116 111 107 101 110 34 125] msg=Failed to POST JSON to /_matrix/client/r0/logout code=401 wrapped=M_MISSING_TOKEN: Mis
sing access token"
...snip...
```
---

It would be nice to have a configurable back-off timer, but I don't know how much work that would require.
