### ISSUE TITLE
discord webhook not working

### ISSUE THREAD

**Issue by onthecliff** [crazy-max/diun#886]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/diun/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Diun not reaching the webhook when I test it.

### Expected behaviour

I expect the test to be successful.

### Actual behaviour

When I run 'diun notif test' I get 'diun: error: rpc error: code = Unknown desc = Post "https://discord.com/api/webhooks/...": context deadline exceeded (Client.Timeout exceeded while awaiting headers)'.

However, when I run

wget --post-data='{"content":"test message"}' --header='Content-Type: application/json' https://discordapp.com/api/webhooks/...

From diun, it gives me

Connecting to discordapp.com (162.159.129.233:443)
saving to '[...]'
'[...]' saved

and a test message is sent in the server.

### Steps to reproduce

.

### Diun version

crazymax/diun:latest 	48.4 MB 	2022-12-29 06:25:32

### Docker info

```text
.
```

### Docker Compose config

```yaml
version: "3.5"
services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - /mypath:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/New_York
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_NOTIF_DISCORD_WEBHOOKURL=https://discord.com/api/webhooks/...
      - DIUN_NOTIF_DISCORD_RENDERFIELDS=true
      - DIUN_NOTIF_DISCORD_TIMEOUT=10
      - DIUN_NOTIF_DISCORD_TEMPLATEBODY="Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released."
    restart: always
```

### Logs

```text
.
```

### Additional info

.
