### ISSUE TITLE
WRN "No image found"

### ISSUE THREAD

**Issue by tborychowski** [crazy-max/diun#90]
#### Steps to reproduce this issue

1. Started with `docker-compose up -d`
2. run `docker-compose logs`
3. See the following error
```
Attaching to diun
diun    | Sat, 06 Jun 2020 18:04:54 IST INF Starting Diun 3.0.0
diun    | Sat, 06 Jun 2020 18:04:54 IST INF Cron triggered
diun    | Sat, 06 Jun 2020 18:04:54 IST WRN No image found
diun    | Sat, 06 Jun 2020 18:04:54 IST INF Cron initialized with schedule 0 * * * *
```

#### Expected behaviour
I don't know :-)
Is the warning acceptable? What does it mean?

#### Actual behaviour
I see the warning, and am concerned :-)

### Configuration

* Diun version : 3.0.0
* Platform (windows/linux) : linux
* System info (type `uname -a`) : ubuntu 20.04 

```yaml
db:
  path: diun.db

watch:
  workers: 10
  schedule: "0 * * * *"
  first_check_notif: false

notif:
  slack:
    webhook_url: ---redacted---

regopts:
  dockerhub:
    username: ---redacted---
    password: ---redacted---
    timeout: 20

providers:
  docker:
    watch_stopped: true
```

### Logs

```
# paste logs here (set log-level to debug and enable log-caller)
```
