### ISSUE TITLE
Provide a way to healthcheck the diun container itself

### ISSUE THREAD

**Issue by YurNaybor** [crazy-max/diun#938]
### Description

Hello,

I would like to have a healthcheck for the diun container, so I can monitor it within Docker (Swarm). This is different from the healthchecks integration, because it does not need any other service. Maybe we can have a diun sub command that returns an exit code depending on the state of diun. This command could then be used in the healthcheck of Docker, e.g. in a compose file:

```
  [...]
services:
  diun:
    [...]
    healthcheck:
      test: "diun ping"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
```
