### ISSUE TITLE
Running diun behind proxy

### ISSUE THREAD

**Issue by Matsched** [crazy-max/diun#944]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/diun/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I want to run diun behind a squid. I can tell my OS to use proxy and Docker to use proxy. But how i can tell diun to use proxy?

### Expected behaviour

Diun can ping container registry from "example" lscr.io over the proxy.

### Actual behaviour

Diun dont use proxy. Theres no option to set that diun will use it.

### Steps to reproduce

1. Create a restricted network
2. Install a squid, configure it and configure the firewall that you can use the squid in your network
3. Install Debian or other OS, export the HTTPS_PROXY variables, install docker and configure proxy settings there aswell
4. Pull Diun and start it

### Diun version

4.25.0

### Docker info

```text
Docker version 24.0.5 (compose)
```

### Docker Compose config

```yaml
diun:
    container_name: diun
    image: crazymax/diun:latest
    restart: always
    volumes:
      - ./data/diun:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "Europe/Berlin"
      LOG_LEVEL: "info"
      LOG_JSON: "false"
      DIUN_WATCH_WORKERS: "20"
      DIUN_WATCH_SCHEDULE: "0 16 * * *"
      DIUN_PROVIDERS_DOCKER: "true"
      DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT: "true"
      DIUN_NOTIF_TELEGRAM_TOKEN: "REDACTED"
      DIUN_NOTIF_TELEGRAM_CHATIDS: "REDACTED"
      DIUN_NOTIF_TELEGRAM_TEMPLATEBODY: >
        "REDACTED"
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.01'
          memory: 256M
```

### Logs

```text
`diun  | Sat, 02 Sep 2023 19:02:42 CEST INF Starting Diun version=v4.25.0
diun  | Sat, 02 Sep 2023 19:02:42 CEST INF Configuration loaded from 8 environment variable(s)
diun  | Sat, 02 Sep 2023 19:02:42 CEST INF Cron triggered
diun  | Sat, 02 Sep 2023 19:02:42 CEST INF Found 9 image(s) to analyze provider=docker
diun  | Sat, 02 Sep 2023 19:02:42 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: pinging container registry lscr.io: Get \"https://lscr.io/v2/\": dial tcp 3.77.103.135:443: connect: connection refused" image=lscr.io/linuxserver/redacted:latest provider=docker
diun  | Sat, 02 Sep 2023 19:02:42 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: pinging container registry lscr.io: Get \"https://lscr.io/v2/\": dial tcp 3.77.103.135:443: connect: connection refused" image=lscr.io/linuxserver/redacted:latest provider=docker
diun  | Sat, 02 Sep 2023 19:02:42 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: pinging container registry lscr.io: Get \"https://lscr.io/v2/\": dial tcp 3.77.103.135:443: connect: connection refused" image=lscr.io/linuxserver/redacted:latest provider=docker
diun  | Sat, 02 Sep 2023 19:02:42 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: pinging container registry lscr.io: Get \"https://lscr.io/v2/\": dial tcp 3.77.103.135:443: connect: connection refused" image=lscr.io/linuxserver/redacted:latest provider=docker
diun  | Sat, 02 Sep 2023 19:02:42 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: pinging container registry lscr.io: Get \"https://lscr.io/v2/\": dial tcp 3.77.103.135:443: connect: connection refused" image=lscr.io/linuxserver/redacted:latest provider=docker
diun  | Sat, 02 Sep 2023 19:02:42 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: pinging container registry registry-1.docker.io: Get \"https://registry-1.docker.io/v2/\": dial tcp 3.216.34.172:443: connect: connection refused" image=docker.io/containrrr/watchtower:latest provider=docker
diun  | Sat, 02 Sep 2023 19:02:42 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: pinging container registry registry-1.docker.io: Get \"https://registry-1.docker.io/v2/\": dial tcp 3.216.34.172:443: connect: connection refused" image=docker.io/redacted:latest provider=docker
diun  | Sat, 02 Sep 2023 19:02:42 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: pinging container registry registry-1.docker.io: Get \"https://registry-1.docker.io/v2/\": dial tcp 3.216.34.172:443: connect: connection refused" image=docker.io/crazymax/diun:latest provider=docker
diun  | Sat, 02 Sep 2023 19:02:42 CEST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: pinging container registry registry-1.docker.io: Get \"https://registry-1.docker.io/v2/\": dial tcp 3.216.34.172:443: connect: connection refused" image=docker.io/library/postgres:latest provider=docker
diun  | Sat, 02 Sep 2023 19:02:42 CEST INF Jobs completed added=0 failed=9 skipped=0 unchanged=0 updated=0
diun  | Sat, 02 Sep 2023 19:02:42 CEST INF Cron initialized with schedule 0 16 * * *
diun  | Sat, 02 Sep 2023 19:02:42 CEST INF Next run in 20 hours 57 minutes (2023-09-03 16:00:20.849655733 +0200 CEST)`
```
