### ISSUE TITLE
Error "invalid character '<' looking for beginning of value" when trying to use ntfy

### ISSUE THREAD

**Issue by Kalooth** [crazy-max/diun#986]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/diun/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When trying to use ntfy for notifications, it always throws the error:

ERR Ntfy notification failed error="invalid character '<' looking for beginning of value" image=docker.io/netdata/netdata:latest

This even occurs when attempting to use the test command:
_docker compose exec diun diun notif test_

diun: error: main.NotifTestCmd.Run(): rpc error: code = Unknown desc = invalid character '<' looking for beginning of value

--------
Running via docker compose (replaced _ENDPOINT with my endpoint):
version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    command: serve
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=America/Chicago"
      - "LOG_LEVEL=debug"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true"
      - "DIUN_WATCH_FIRSTCHECKNOTIF=true"
      - "DIUN_NOTIF_NTFY_ENDPOINT=https://ntfy.example.com"
      - "DIUN_NOTIF_NTFY_TOPIC=diun_updates"
    labels:
      - "diun.enable=true"
    restart: unless-stopped

### Expected behaviour

No errors when pushing notifications via ntfy

### Actual behaviour

Error: code = Unknown desc = invalid character '<' looking for beginning of value

### Steps to reproduce

1. Setup self hosted ntfy instance
2. Setup diun via docker compose, connect endpoint to ntfy instance
3. Execute the test notify command - docker compose exec diun diun notif test
4. Notice error regarding invalid character '<'

### Diun version

4.26

### Docker info

```text
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 23
  Running: 20
  Paused: 0
  Stopped: 3
 Images: 23
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.0-26-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.56GiB
 Name: p
 ID: eda8ca4c-10c4-4f07-8d29-179da8f2138d
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Docker Compose config

```yaml
name: diun
services:
  diun:
    command:
    - serve
    environment:
      DIUN_NOTIF_NTFY_ENDPOINT: https://ntfy.example.com
      DIUN_NOTIF_NTFY_TOPIC: diun_updates
      DIUN_PROVIDERS_DOCKER: "true"
      DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT: "true"
      DIUN_PROVIDERS_DOCKER_WATCHSTOPPED: "true"
      DIUN_WATCH_FIRSTCHECKNOTIF: "true"
      DIUN_WATCH_JITTER: 30s
      DIUN_WATCH_SCHEDULE: 0 */6 * * *
      DIUN_WATCH_WORKERS: "20"
      LOG_LEVEL: debug
      TZ: America/Chicago
    image: crazymax/diun:latest
    labels:
      diun.enable: "true"
    networks:
      default: null
    restart: unless-stopped
    volumes:
    - type: bind
      source: /home/n/Documents/diun/data
      target: /data
      bind:
        create_host_path: true
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      bind:
        create_host_path: true
networks:
  default:
    name: diun_default
```

### Logs

```text
n/a
```
