### ISSUE TITLE
Discord mentions not working

### ISSUE THREAD

**Issue by BNWEIN** [crazy-max/diun#992]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/diun/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Im sure this is a "me" issue rather than a bug, but i am unable to get the mentions functioning in discord notifications.

It posts the correct name in discord, but with no mention? You can see in the screenshot below whilst it has @Mrusername its not highlighted like a usually mention (second screen shot) which means we do not get a ping

![image](https://github.com/crazy-max/diun/assets/28929905/100abdd9-0954-427a-9bd8-140197723135)

### Expected behaviour

Expected behaviour  is a ping 

![image](https://github.com/crazy-max/diun/assets/28929905/5ae78481-3e6c-4c36-9c99-09ff7f1480c9)

### Actual behaviour

Not being pinged or notified. 

### Steps to reproduce

```yaml
discord:
    webhookURL: https://discord.com/api/webhooks/apiid/apidiid
    mentions:
      - "@mruser"
    renderFields: true
    timeout: 10s
    templateBody: |
      Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released.
```

### Diun version

4.26.0

### Docker info

```text
Dont think this is needed
```

### Logs

```text
Dont think its needed
```

**Comment by maurxce** [comment]
Have you tried using your discord id instead?

**Comment by maurxce** [comment]
^ I would like to add that this is the preferred way of pinging users in discord.js afaik. So I guess it would also apply to webhooks

**Comment by BNWEIN** [comment]
> s

I have tried both.  Although my config looks different to what you have provided

```
`notif:
  discord:
    webhookURL: <MyURL>
    mentions:
      - '@myid'
    renderFields: true
    timeout: 10s
    templateBody: |
      Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released.`
      
```
 Is there something wrong with the config?
